### ISSUE TITLE
after python update autokey does not start anymore

### ISSUE THREAD

**Issue by DarioDarko** [autokey/autokey#1000]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [X] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [X] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [X] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

endeavourOS

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.96.0-6

### How did you install AutoKey?

AUR / yay

### Can you briefly describe the issue?

after updating my OS, including a new version of python (and many python packages), autokey-gtk does not start anymore (module autokey not found). after a reinstallation theres a different python module missing (imghdr)

you can see the error messages and the updated packages below

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. up-to-date arch (based) distro
2. install autokey-gtk from AUR
3. try to start autokey-gtk

### What should have happened?

autokey launching

### What actually happened?

autokey crashes on start

### Can you provide the output of the AutoKey command?

```bash
# before reinstall

~ autokey-gtk

Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 5, in <module>
    from autokey.gtkui.__main__ import main
ModuleNotFoundError: No module named 'autokey'

# after reinstall

~ autokey-gtk

Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 5, in <module>
    from autokey.gtkui.__main__ import main
  File "/usr/lib/python3.13/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3.13/site-packages/autokey/gtkapp.py", line 39, in <module>
    from autokey import service, monitor
  File "/usr/lib/python3.13/site-packages/autokey/service.py", line 37, in <module>
    import autokey.scripting
  File "/usr/lib/python3.13/site-packages/autokey/scripting/__init__.py", line 24, in <module>
    from . import highlevel
  File "/usr/lib/python3.13/site-packages/autokey/scripting/highlevel.py", line 9, in <module>
    import imghdr
ModuleNotFoundError: No module named 'imghdr'
```

### Anything else?

[2024-12-23T10:18:30+0100] [ALPM] upgraded python (3.12.7-1 -> 3.13.1-1)
[2024-12-23T10:18:30+0100] [ALPM] upgraded python-dbus (1.3.2-4 -> 1.3.2-5)
[2024-12-23T10:18:30+0100] [ALPM] upgraded python-capng (0.8.5-2 -> 0.8.5-3)
[2024-12-23T10:18:30+0100] [ALPM] upgraded python-gobject (3.50.0-1 -> 3.50.0-2)
[2024-12-23T10:18:31+0100] [ALPM] upgraded python-psutil (6.1.0-1 -> 6.1.1-1)
[2024-12-23T10:18:31+0100] [ALPM] upgraded python-defusedxml (0.7.1-6 -> 0.7.1-7)
[2024-12-23T10:18:31+0100] [ALPM] upgraded python-orjson (3.10.11-1 -> 3.10.12-1)
[2024-12-23T10:18:31+0100] [ALPM] upgraded python-annotated-types (0.7.0-1 -> 0.7.0-2)
[2024-12-23T10:18:31+0100] [ALPM] upgraded python-typing_extensions (4.12.2-1 -> 4.12.2-3)
[2024-12-23T10:18:31+0100] [ALPM] upgraded python-pydantic-core (1:2.23.4-1 -> 1:2.27.2-1)
[2024-12-23T10:18:31+0100] [ALPM] upgraded python-pydantic (2.9.2-1 -> 2.10.4-1)
[2024-12-23T10:18:31+0100] [ALPM] upgraded python-packaging (24.2-1 -> 24.2-3)
[2024-12-23T10:18:31+0100] [ALPM] upgraded python-distro (1.9.0-2 -> 1.9.0-3)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-attrs (23.2.0-3 -> 23.2.0-4)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-autocommand (2.2.2-6 -> 2.2.2-7)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-pyproject-hooks (1.2.0-1 -> 1.2.0-3)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-build (1.2.2-1 -> 1.2.2-3)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-certifi (2024.08.30-1 -> 2024.12.14-1)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-charset-normalizer (3.4.0-1 -> 3.4.0-5)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-colorama (0.4.6-3 -> 0.4.6-5)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-docopt (0.6.2-13 -> 0.6.2-14)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-h11 (0.14.0-4 -> 0.14.0-6)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-idna (3.10-1 -> 3.10-2)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-installer (0.7.0-8 -> 0.7.0-10)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-more-itertools (10.3.0-1 -> 10.5.0-1)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-jaraco.functools (4.0.2-1 -> 4.1.0-1)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-jaraco.context (5.3.0-1 -> 5.3.0-3)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-jaraco.text (4.0.0-1 -> 4.0.0-2)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-jaraco.collections (5.0.1-1 -> 5.0.1-2)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-keyutils (0.6-10 -> 0.6-11)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-outcome (1.3.0.post0-4 -> 1.3.0.post0-5)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-pillow (11.0.0-1 -> 11.0.0-3)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-platformdirs (4.3.6-1 -> 4.3.6-2)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-yaml (6.0.2-1 -> 6.0.2-2)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-pyaml (24.9.0-1 -> 24.9.0-2)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-pycups (2.0.4-2 -> 2.0.4-3)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-pyinotify (0.9.6-14 -> 0.9.6-15)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-pyqt5-sip (12.16.1-1 -> 12.16.1-2)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-pyqt5 (5.15.11-1 -> 5.15.11-2)
[2024-12-23T10:18:36+0100] [ALPM] installed python-chardet (5.2.0-6)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-reportlab (4.2.2-1 -> 4.2.2-5)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-urllib3 (1.26.20-3 -> 1.26.20-4)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-requests (2.32.3-1 -> 2.32.3-4)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-setproctitle (1.3.3-2 -> 1.3.4-1)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-wheel (0.45.0-1 -> 0.45.0-3)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-setuptools (1:75.2.0-2 -> 1:75.2.0-4)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-shtab (1.7.1-2 -> 1.7.1-3)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-six (1.16.0-9 -> 1.16.0-10)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-sniffio (1.3.1-3 -> 1.3.1-4)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-sortedcontainers (2.4.0-6 -> 2.4.0-7)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-termcolor (2.4.0-2 -> 2.4.0-3)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-trio (0.26.2-1 -> 0.26.2-2)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-wsproto (1.2.0-4 -> 1.2.0-5)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-trio-websocket (0.11.1-3 -> 0.11.1-4)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-websocket-client (1.8.0-1 -> 1.8.0-2)
[2024-12-23T10:18:36+0100] [ALPM] upgraded python-xlib (0.33-3 -> 0.33-4)
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #1000</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @DarioDarko</code> (replace <code>20</code> with the amount, and <code>@DarioDarko</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by JThundley** [comment]
This happened because the imghdr module was moved out of the standard library in Python 3.13: https://peps.python.org/pep-0594/#imghdr

**Comment by JThundley** [comment]
The Arch autokey package manager just released an update that fixes this. I think it's including the python-magic package which likely contains imghdr.

**Comment by DarioDarko** [comment]
yep, works again! 🙂

**Comment by josephj11** [comment]
For others not using Arch, this bug is being fixed in issue #997,  PR #961.

We will get this merged ASAP, but we have no immediate plans for a new release as we don't currently have a developer to create one. There are notes in the links above about how you can fix this locally so you don't have to wait for a new release.
