### ISSUE TITLE
Pyperclip not working

### ISSUE THREAD

**Issue by gituser823** [autokey/autokey#120]
## Classification:

Bug

## Reproducibility:

Always

## Summary

Pyperclip does not work as a Python-Script with Autokey-GTK on Mint 18.1 Cimmamon 64-bit.

## Steps to Reproduce

try to execute this script:
```
# Enter script code
import pyperclip
pyperclip.copy('The text to be copied to the clipboard.')
spam = pyperclip.paste()
```
## Expected Results

Variable spam should be set to The text to be copied to the clipboard.

## Actual Results

I get a Python Error:
```
Script name: 'pyper'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 460, in execute
    exec(script.code, scope)
  File "<string>", line 3, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyperclip/__init__.py", line 138, in copy_gtk
    cb = gtk.Clipboard()
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 64, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```

If helpful, submit screenshots of the issue to help debug. `autokey-gtk --verbose` output is also useful.

## Version

AutoKey-GTK 0.93.10
installed via ppa:troxor/autokey

If the problem is known to be present in more than one version, please list all of those.

Installed via: sudo pip3 install pyperclip

Distro:
Mint 18.1 Cimmamon 64-bit
## Notes

When I execute the Script via Python3-Console directly, it works as expected.

Describe any debugging steps you've taken yourself.

If you've found a workaround, provide it here.

**Comment by josephj11** [comment]
Don't know why this doesn't work. However, if that's exactly what you want to do, why not just use the [AutoKey API](https://autokey.github.io/index.html)?

clipboard.fill_clipboard(contents)

**Comment by gituser823** [comment]
I don't remember why I didn't use clipboard.fill_clipboard(contents) , I will will test it out.

Although I still would like to know why it fails.

How can I verify if everything is okay with my Autokey version?

**Comment by luziferius** [comment]
It fails because of this: `AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183`
Autokey uses the first. Pyperclip uses the latter `import gobject`. Both are mutually exclusive, thus importing Pyperclip fails.

This should work, if you use the Qt UI, because it does not use `gi.repository` and therefore does not conflict.
