### ISSUE TITLE
prblems with parameters to dialog.save_file

### ISSUE THREAD

**Issue by jack99999** [autokey/autokey#124]
## Classification: Bug

(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement)

## Reproducibility: Always

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)

## Summary
various problems with parameters to dialog.save_file. sometimes dialog fails completely, sometimes it doesn't work as expected.

## Steps to Reproduce

Mint 18.3
Autokey 0.93.10
Zenity 3.18.1.1 
Python 3.5.2 

`retCode, fName = dialog.save_file(title="Save As")`
`### this works`

`retCode, dirName = dialog.choose_directory(title='Select Directory', initialDir='/tmp/')`
`### dialog is displayed but shows ~ directory rather than /tmp`

`retCode, fName = dialog.save_file(title='Save As',fileTypes='*|All Files')`
`### dialog fails with exit code 255`

`retCode, fName = dialog.save_file(title='Save file', rememberAs='1234')`
`### dialog fails with exit code 255`

`retCode, fName = dialog.save_file(title='Save file', rememberAs=None)`
`### dialog fails:`
`### Traceback (most recent call last):`
`###   File "/usr/lib/python3/dist-packages/autokey/service.py", line 460, in execute`
`###     exec(script.code, scope)`
`###   File "<string>", line 13, in <module>`
`###   File "/usr/lib/python3/dist-packages/autokey/scripting.py", line 615, in save_file`
`###     return self.__runZenity(title, ["--file-selection", "--save"], kwargs)`
`###   File "/usr/lib/python3/dist-packages/autokey/scripting.py", line 464, in __runZenity`
`###     with subprocess.Popen(["zenity", "--title", title] + args, stdout=subprocess.PIPE) as p:`
`###   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__`
`###     restore_signals, start_new_session)`
`###   File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child`
`###     restore_signals, start_new_session, preexec_fn)`
`### TypeError: Can't convert 'NoneType' object to str implicitly`

## Version

AutoKey-Py3 version 0.93.10
Mint 18.3
Autokey 0.93.10
Zenity 3.18.1.1 
Python 3.5.2 

Installed via: (PPA, pip, …). can't remember.

Distro: Mint 18.3

## Notes

see Steps to Reproduce section.

**Comment by jack99999** [comment]
arrrgggghhh. mixed up between Qt and Gtk. closing.
