### ISSUE TITLE
When installed via pip, gir1.2-appindicator3-0.1 required

### ISSUE THREAD

**Issue by iMartyn** [autokey/autokey#129]
## Classification:

UI/Usability

## Reproducibility:

Always

## Summary

Attempting to install via pip3 on recent debian has no problem until you attempt to launch the gui.  It depends on the package 

## Steps to Reproduce

- pip3 install autokey
- for good measure install libappindicator-3 (and -dev)
- fix any more missing pip3 dependancies
- pip3 install autokey
- autokey-gtk

## Expected Results

- The gui should start

## Actual Results

$ autokey-gtk                                                                                                                                                                            (minikube/kube-system)
Traceback (most recent call last):
  File "/home/ranyardm/.local/bin/autokey-gtk", line 7, in <module>
    from autokey.gtkui.__main__ import main
  File "/home/ranyardm/.local/lib/python3.5/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/ranyardm/.local/lib/python3.5/site-packages/autokey/gtkapp.py", line 31, in <module>
    from autokey.gtkui.notifier import get_notifier
  File "/home/ranyardm/.local/lib/python3.5/site-packages/autokey/gtkui/notifier.py", line 22, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

If helpful, submit screenshots of the issue to help debug. `autokey-gtk --verbose` output is also useful.

## Version

0.93.10

If the problem is known to be present in more than one version, please list all of those.

Installed via: pip3 install autokey

Distro:

latest debian (9.4)

Describe any debugging steps you've taken yourself.

Lots of googling, eventually found a solution

If you've found a workaround, provide it here.

apt install gir1.2-appindicator3-0.1

^^ The above should be in the README.md, the wiki somewhere or somewhere much more obvious than it is.

**Comment by josephj11** [comment]
Thanks. I started adding a [subsection](https://github.com/autokey/autokey/wiki/Installing#Installing-Debian-dependencies) on installing Debian dependencies to the Install wiki. I haven't installed 0.93/0.94 yet, so I don't know what else needs to be added. Any input would be appreciated on [Gitter](https://gitter.im/autokey/autokey) or on our [list](url). Or, you can edit the wiki directly if you're confident about the added content.

**Comment by roseswe** [comment]
Same error message with openSUSE 15.0!
Installed as root via pip3 install git+https://github.com/autokey/autokey

$ autokey-gtk --verbose
Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 11, in <module>
    load_entry_point('autokey==0.94.1', 'console_scripts', 'autokey-gtk')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3.6/site-packages/autokey/gtkapp.py", line 45, in <module>
    from autokey.gtkui.notifier import get_notifier
  File "/usr/lib/python3.6/site-packages/autokey/gtkui/notifier.py", line 23, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

There is no gir1.2-appindicator3*  available on openSUSE

**Comment by roseswe** [comment]
Same issue with autokey 0.95.2
