### ISSUE TITLE
Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'

### ISSUE THREAD

**Issue by stndrf** [autokey/autokey#166]
## Classification:

Bug or missconfigure  on my system, not sure.

## Reproducibility:

Always, just start it.

## Summary

I can't start autokey-gtk. 

## Steps to Reproduce

i run `autokey-gkt -l -c` 

## Expected Results

Seeing the gui

## Actual Results

I get this error:

`2018-07-11 09:54:44,891 ERROR - root - Error starting interface: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'`

Complete Log:

```
λ › autokey-gtk -l -c --verbose                                                                                                                              ~
2018-07-11 09:59:49,144 INFO - root - Initialising application
2018-07-11 09:59:49,159 INFO - root - Initialise global hotkeys
2018-07-11 09:59:49,159 INFO - config-manager - Loading config from existing file: /home/benedikt/.config/autokey/autokey.json
2018-07-11 09:59:49,160 DEBUG - config-manager - Loading folder at '/home/benedikt/.config/autokey/data/Sample Scripts'
2018-07-11 09:59:49,162 DEBUG - config-manager - Loading folder at '/home/benedikt/.config/autokey/data/My Phrases'
2018-07-11 09:59:49,163 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2018-07-11 09:59:49,163 DEBUG - inotify - Adding watch for /home/benedikt/.config/autokey/data/Sample Scripts
2018-07-11 09:59:49,164 DEBUG - inotify - Adding watch for /home/benedikt/.config/autokey/data/My Phrases
2018-07-11 09:59:49,164 DEBUG - inotify - Adding watch for /home/benedikt/.config/autokey/data/My Phrases/Addresses
2018-07-11 09:59:49,164 INFO - config-manager - Successfully loaded configuration
2018-07-11 09:59:49,164 DEBUG - inotify - Adding watch for /home/benedikt/.config/autokey/data
2018-07-11 09:59:49,164 DEBUG - inotify - Adding watch for /home/benedikt/.config/autokey
2018-07-11 09:59:49,164 DEBUG - config-manager - Global settings: {'isFirstRun': True, 'serviceRunning': True, 'menuTakesFocus': False, 'showTrayIcon': True, 'sortByUsageCount': True, 'promptToSave': False, 'enableQT4Workaround': False, 'interfaceType': 'XRecord', 'undoUsingBackspace': True, 'windowDefaultSize': [600, 400], 'hPanePosition': 150, 'columnWidths': [150, 50, 100], 'showToolbar': True, 'notificationIcon': 'autokey-status', 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'triggerItemByInitial': False, 'scriptGlobals': {}}
2018-07-11 09:59:49,165 INFO - service - Starting service
2018-07-11 09:59:49,180 ERROR - root - Error starting interface: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/autokey/gtkapp.py", line 147, in initialise
    self.service.start()
  File "/usr/lib/python3.6/site-packages/autokey/service.py", line 81, in start
    self.mediator = IoMediator(self)
  File "/usr/lib/python3.6/site-packages/autokey/iomediator/_iomediator.py", line 50, in __init__
    self.interface = XRecordInterface(self, service.app)
  File "/usr/lib/python3.6/site-packages/autokey/interface.py", line 207, in __init__
    self.__initMappings()
  File "/usr/lib/python3.6/site-packages/autokey/interface.py", line 260, in __initMappings
    self.localDisplay = display.Display()
  File "/usr/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.6/site-packages/Xlib/protocol/display.py", line 167, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'
Gtk-Message: 09:59:49.315: GtkDialog mapped without a transient parent. This is discouraged.
2018-07-11 09:59:54,578 DEBUG - phrase-menu - Sorting phrase menu by usage count
2018-07-11 09:59:54,578 DEBUG - phrase-menu - Triggering menu item by position in list
2018-07-11 09:59:54,581 DEBUG - root - Created DBus service
2018-07-11 09:59:54,582 INFO - root - Displaying configuration window
Gtk-Message: 09:59:54.623: GtkDialog mapped without a transient parent. This is discouraged.

(autokey-gtk:10855): Gdk-CRITICAL **: 09:59:54.778: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
2018-07-11 09:59:57,476 ERROR - root - Fatal error starting AutoKey: 'Service' object has no attribute 'phraseRunner'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/autokey/gtkapp.py", line 98, in __init__
    self.initialise(options.configure)
  File "/usr/lib/python3.6/site-packages/autokey/gtkapp.py", line 161, in initialise
    if configure: self.show_configure()
  File "/usr/lib/python3.6/site-packages/autokey/gtkapp.py", line 257, in show_configure
    self.configWindow = ConfigWindow(self)
  File "/usr/lib/python3.6/site-packages/autokey/gtkui/configwindow.py", line 803, in __init__
    menu = self.app.service.phraseRunner.macroManager.get_menu(self.on_insert_macro)
AttributeError: 'Service' object has no attribute 'phraseRunner'
```

## Version

0.95.1-2

Installed via: AUR

Distro: Arch

**Comment by stndrf** [comment]
Output of `pgrep -a X`

```
λ › pgrep -a X                                                                                                                                      ~/.autokey
775 /usr/lib/Xorg :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
```

**Comment by luziferius** [comment]
That is probably a misconfiguration on your system. 
I googled `Invalid MIT-MAGIC-COOKIE-1 key`, and it seems this is related to `xauth` (`λ › man xauth`) and an invalid authentication cookie in `$HOME/.Xauthority`. Those cookies seem to be used for remote GUI forwarding over ssh and such. Because AutoKey monitors the keyboard for its functionality, it may need privileges that get rejected because of an invalid cookie.

Many people suggest just deleting `$HOME/.Xauthority`, but there might be a more elegant solution.
- Backup your `$HOME/.Xauthority`
- Use `λ › xauth list` to list all cookies. Lookout for invalid stuff. Mine looks like `thomas-laptop/unix:0  MIT-MAGIC-COOKIE-1  40ac8ccbc8440c967329386e3ed0241c`
- Then use the `xauth` tool to remove stuff that looks bad or unexpected.
- Retry starting autokey.

**Comment by luziferius** [comment]
Does it still occur or did those steps fix it?
