### ISSUE TITLE
Can not install on Mint 18

### ISSUE THREAD

**Issue by gituser823** [autokey/autokey#182]
## Classification:

Bug

## Reproducibility:

Always

## Summary

I installed these successfully as root:
common dependencies
apt-get install python3-pyinotify wmctrl xautomation imagemagick
dependencies for GTK GUI, install only if you intend to use the GTK GUI.
apt-get install python3-gi gir1.2-gtk-3.0 gir1.2-gtksource-3.0 gir1.2-glib-2.0 gir1.2-notify-0.7 python3-dbus zenity

But when I run
execute as non root
pip3 install --user python3-xlib

I get Errors.

## Steps to Reproduce (if applicable)

Follow installation instruction for GTK at https://github.com/guyt101z/autokey-py3

## Expected Results

Autokey-py3 should be installed

## Actual Results

- Instead, this happens. :(

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please put the output into a block quote (enclose in triple backticks).
```
gituser823@gituser823-laptop ~ $ pip3 install --user python3-xlib
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 267, in run
    with self._build_session(options) as session:
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/lib/python3/dist-packages/pip/download.py", line 321, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3/dist-packages/pip/download.py", line 97, in user_agent
    zip(["lib", "version"], platform.libc_ver()),
  File "/usr/lib/python3.6/platform.py", line 187, in libc_ver
    glibcverinfo = glibcversion.split('.')
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 245, in main
    timeout=min(5, options.timeout)) as session:
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/lib/python3/dist-packages/pip/download.py", line 321, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3/dist-packages/pip/download.py", line 97, in user_agent
    zip(["lib", "version"], platform.libc_ver()),
  File "/usr/lib/python3.6/platform.py", line 187, in libc_ver
    glibcverinfo = glibcversion.split('.')
AttributeError: 'NoneType' object has no attribute 'split'
```

## Version

AutoKey version: 

Used GUI (Gtk, Qt, or both): 

Autokey-py3, gtk version

Installed via: pip3

Distro: Mint 18

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

**Comment by luziferius** [comment]
The fork you took the instructions from wasn’t updated since 2016.
The package you are looking for is in the official ubuntu packages and is called [`python3-xlib`](https://packages.ubuntu.com/xenial/python3-xlib).

You can install it using `sudo apt install python3-xlib`.
