### ISSUE TITLE
Emoji are not printed 0.95.1

### ISSUE THREAD

**Issue by Zulgrib** [autokey/autokey#241]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.1

Used GUI (Gtk, Qt, or both): GTK

If the problem is known to be present in more than one version, please list all of those.

Installed via: PPA

Linux Distribution: Mint19

## Summary

When expanding text from a txt file that contain emojis, the emojis are ignored and not typed.

## Steps to Reproduce (if applicable)

- Add "🔧" to an example phrase
- Set an expension shortcut (I used dollar tmain)
- Write the trigger string

## Expected Results

- My txt is printed as is without alterations

## Actual Results

- Instead, all text is printed excluding the emojis

## Notes

The emojis are properly displayed in the GTK interface and in xed/gedit.

Paste using keyboard

**Comment by luziferius** [comment]
Typing symbols is a bit brittle. If you check the log file, you’ll probably notice some warnings about AutoKey failing to map the symbol. It means that AutoKey failed to register a new X11 key code for the symbol, i.e. failed to create a virtual key that creates the requested symbol.

Switching to clipboard pasting should make the symbols appear. It will also work better with long phrases.

**Comment by Zulgrib** [comment]
Indeed it works.

Looks like keyboard mode is to be kept strictly for key-presses and not writing text.

Fantastic work.

**Comment by luziferius** [comment]
Writing text works, but is a bit slow. Anything below about 100 characters should work within reasonable time. But it only works with characters that you can type using your physical keyboard.

Using the clipboard for longer texts is the way to go. It will also work better with slower applications, like Firefox or LibreOffice, which choke when confronted with the AutoKey typing speed, like in #151.

But you need the keyboard typing if you want to use navigation keys or other special keys inside your phrase.

**Comment by rodrigograca31** [comment]
I'm here to show support for emojis

I'm trying to do something like:
```
keyboard.send_keys("👍")
keyboard.send_keys("<enter>")
```
Also tried:
```
keyboard.send_keys("\U+1F44D")
```
And doesnt type the emoji.

Codepoint at the bottom: https://emojipedia.org/thumbs-up/

**Comment by josephj11** [comment]
@rodrigograca31 Try using

```
clipboard.fill_clipboard("👍")
keyboard.send_keys("<ctrl>+v")
```

That should work in most applications. If you're in a terminal, you'd need

```
keyboard.send_keys("<ctrl>+<shift>+v")
```

**Comment by rodrigograca31** [comment]
For the record. The solution provided by @josephj11 works after installing the latest version `.deb` file [from here](https://github.com/autokey/autokey/releases/) `autokey-common_0.95.10-0_all.deb` and `autokey-gtk_0.95.10-0_all.deb` for me at this moment. (yours might not be gtk...)

but I realized this way of doing it messes with the clipboard which sucks a bit.

Trying to use the `keyboard` method again gives this error when doing a trace:
```
2020-04-18 12:37:09,027 DEBUG - service - Raw key: <Key.NP_ADD: '<np_add>'>, modifiers: [], Key: Key.NP_ADD
2020-04-18 12:37:09,027 DEBUG - service - Window visible title: 'autokey-gtk -l', Window class: 'gnome-terminal-server.Gnome-terminal'
2020-04-18 12:37:09,027 INFO - service - Matched Script "thums up" with hotkey and prompt=False
2020-04-18 12:37:09,027 DEBUG - service - Script runner executing: Script('thums up')
2020-04-18 12:37:09,028 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
2020-04-18 12:37:09,028 DEBUG - iomediator - Send via event interface
2020-04-18 12:37:09,029 DEBUG - iomediator - Send via event interface
2020-04-18 12:37:09,029 DEBUG - interface - Sending string: '👍'
2020-04-18 12:37:09,033 DEBUG - interface - Send special key: ['<enter>']
```

Reading the log seems it worked and sent the 👍 but it does nothing.

Also: if I try the escaping the code point method again `keyboard.send_keys("\U+1F44D")` after updating my autokey version theres this error:
```
2020-04-18 12:42:13,208 DEBUG - service - Raw key: <Key.NP_ADD: '<np_add>'>, modifiers: [], Key: Key.NP_ADD
2020-04-18 12:42:13,208 DEBUG - service - Window visible title: 'Untitled Document 1 - gedit', Window class: 'gedit.Gedit'
2020-04-18 12:42:13,209 INFO - service - Matched Script "thums up" with hotkey and prompt=False
2020-04-18 12:42:13,209 DEBUG - service - Script runner executing: Script('thums up')
2020-04-18 12:42:13,209 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
2020-04-18 12:42:13,210 ERROR - service - Script error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 485, in execute
    exec(script.code, scope)
  File "<string>", line 2
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \UXXXXXXXX escape
```

**Comment by josephj11** [comment]
As I mentioned on Gitter, you can design your script to save and restore the previous contents of the clipboard as long as you handle the case of trying to get the contents of an initially empty clipboard which will throw an exception.

**Comment by rodrigograca31** [comment]
For those interested I did it this way:

```python
# Enter script code
import time
cb = clipboard.get_clipboard()
clipboard.fill_clipboard("👍🏻")
keyboard.send_keys("<ctrl>+v")

time.sleep(.1)
clipboard.fill_clipboard(cb)
```

If the previous clipboard had too much info or an image it might not work as expected but works overall.

**Comment by Fazendaaa** [comment]
> For those interested I did it this way:
> 
> ```python
> # Enter script code
> import time
> cb = clipboard.get_clipboard()
> clipboard.fill_clipboard("👍🏻")
> keyboard.send_keys("<ctrl>+v")
> 
> time.sleep(.1)
> clipboard.fill_clipboard(cb)
> ```
> 
> If the previous clipboard had too much info or an image it might not work as expected but works overall.

Works perfectly to me... I'm using this 🔗👈 in my case
