### ISSUE TITLE
0.95.5 - Still: GtkDialog mapped without a transient parent. This is discouraged

### ISSUE THREAD

**Issue by roseswe** [autokey/autokey#252]
## Classification:

Crash/Hang/Data Loss
## Reproducibility:

always

## Version

AutoKey version: 0.95.5 (8. Feb 2019)

Used GUI (Gtk, Qt, or both): Gtk

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).   pip3 

Linux Distribution:  openSUSE 15.0 Leap

## Summary
```
ralph@p5520:0:~ > autokey-gtk  -c -l 
2019-02-08 12:43:49,605 INFO - root - Initialising application
2019-02-08 12:43:49,619 INFO - root - Initialise global hotkeys
2019-02-08 12:43:49,620 INFO - config-manager - Loading config from existing file: /home/ralph/.config/autokey/autokey.json
2019-02-08 12:43:49,621 DEBUG - config-manager - Loading folder at '/home/ralph/.config/autokey/data/My Phrases'
2019-02-08 12:43:49,624 DEBUG - config-manager - Loading folder at '/home/ralph/.config/autokey/data/Sample Scripts'
2019-02-08 12:43:49,625 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-02-08 12:43:49,625 DEBUG - inotify - Adding watch for /home/ralph/.config/autokey/data/My Phrases
2019-02-08 12:43:49,626 DEBUG - inotify - Adding watch for /home/ralph/.config/autokey/data/My Phrases/Addresses
2019-02-08 12:43:49,626 DEBUG - inotify - Adding watch for /home/ralph/.config/autokey/data/Sample Scripts
2019-02-08 12:43:49,626 INFO - config-manager - Successfully loaded configuration
2019-02-08 12:43:49,626 DEBUG - inotify - Adding watch for /home/ralph/.config/autokey/data
2019-02-08 12:43:49,626 DEBUG - inotify - Adding watch for /home/ralph/.config/autokey
2019-02-08 12:43:49,627 DEBUG - config-manager - Global settings: {'isFirstRun': True, 'serviceRunning': True, 'menuTakesFocus': False, 'showTrayIcon': True, 'sortByUsageCount': True, 'promptToSave': False, 'enableQT4Workaround': False, 'interfaceType': 'XRecord', 'undoUsingBackspace': True, 'windowDefaultSize': [600, 400], 'hPanePosition': 150, 'columnWidths': [150, 50, 100], 'showToolbar': True, 'notificationIcon': 'autokey-status', 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'triggerItemByInitial': False, 'scriptGlobals': {}}
2019-02-08 12:43:49,627 INFO - service - Starting service
2019-02-08 12:43:49,636 ERROR - root - Error starting interface: Can't connect to display ":0": b'No protocol specified\n'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/autokey/gtkapp.py", line 149, in initialise
    self.service.start()
  File "/usr/lib/python3.6/site-packages/autokey/service.py", line 81, in start
    self.mediator = IoMediator(self)
  File "/usr/lib/python3.6/site-packages/autokey/iomediator/_iomediator.py", line 50, in __init__
    self.interface = XRecordInterface(self, service.app)
  File "/usr/lib/python3.6/site-packages/autokey/interface.py", line 213, in __init__
    self.__initMappings()
  File "/usr/lib/python3.6/site-packages/autokey/interface.py", line 266, in __initMappings
    self.localDisplay = display.Display()
  File "/usr/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.6/site-packages/Xlib/protocol/display.py", line 160, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
2019-02-08 12:44:41,904 DEBUG - phrase-menu - Sorting phrase menu by usage count
2019-02-08 12:44:41,904 DEBUG - phrase-menu - Triggering menu item by position in list
2019-02-08 12:44:41,908 DEBUG - root - Created DBus service
2019-02-08 12:44:41,908 INFO - root - Displaying configuration window
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(autokey-gtk:10726): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
2019-02-08 12:45:01,587 ERROR - root - Fatal error starting AutoKey: 'Service' object has no attribute 'phraseRunner'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/autokey/gtkapp.py", line 98, in __init__
    self.initialise(options.configure)
  File "/usr/lib/python3.6/site-packages/autokey/gtkapp.py", line 164, in initialise
    self.show_configure()
  File "/usr/lib/python3.6/site-packages/autokey/gtkapp.py", line 260, in show_configure
    self.configWindow = ConfigWindow(self)
  File "/usr/lib/python3.6/site-packages/autokey/gtkui/configwindow.py", line 803, in __init__
    menu = self.app.service.phraseRunner.macroManager.get_menu(self.on_insert_macro)
AttributeError: 'Service' object has no attribute 'phraseRunner'
```
## Steps to Reproduce (if applicable)

At startup

**Comment by luziferius** [comment]
It’s actually this:
`ERROR - root - Error starting interface: Can't connect to display ":0": b'No protocol specified\n'`

Duplicate of #175 
This is some kind of spurious permission issue on OpenSuse. AutoKey is not allowed to access the X server, thus fails to start.
You’ll have to grant AutoKey access to the X server. Running the _workaround_ `xhost +localhost` grants all local applications full access to the X server and thus allows AutoKey to start.

Those other warnings are caused by the old GTK GUI using outdated style attributes in the gui XML files. At some time, it will need a rewrite.

**Comment by roseswe** [comment]
$> xhost +localhost
localhost being added to access control list

$> autokey-gtk 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Killed

No cure, same behaviour

**Comment by Cardosaum** [comment]
I'm facing this same issue. 

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 30 (Thirty)
Release:        30
Codename:       Thirty

Autokey: autokey-qt-0.95.7-2.fc30.noarch

**Comment by josephj11** [comment]
Is anyone still experiencing this issue? Is this a deficiency in AutoKey or something fixed upstream?

There have been no further comments here in over six years.

It sounds like our GTK GUI needs some work.
