### ISSUE TITLE
Hangs when using abbreviation to send text via script

### ISSUE THREAD

**Issue by andrisz** [autokey/autokey#286]
## Classification:

Hang

## Reproducibility:

Always

## Version

AutoKey version: 
0.95.7
Qt version
Installed with debian packages from github (https://github.com/autokey/autokey/releases).
Debian 9.9
Python version: 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]

## Summary

When using script to send some keys triggered by abbreviation it often hangs if 'Remove typed abbreviation' is enabled.

## Steps to Reproduce (if applicable)

- create script 
```
title = window.get_active_title()
keyboard.send_keys("Window: %s" % title)
```
- Assing longer abbreviation (jr-commit for example), enable 'Remove typed abbreviation', 'Trigger when typed', 'Trigger immediately' in abbreviation settings.
- type abbreviation several times

## Expected Results

- each abbreviation is replaced with Window: <window title> text

## Actual Results

- often hangs, usually takes 1-5 tries

```
2019-05-21 21:49:04,357 DEBUG - service - Window visible title: '(Untitled) * SciTE', Window class: 'scite-bin.Scite-bin'
2019-05-21 21:49:04,363 INFO - service - Matched Script "JIRA test" having abbreviations "['jr-commit']" against current input
2019-05-21 21:49:04,364 DEBUG - service - Script runner executing: Script('JIRA test')
2019-05-21 21:49:04,371 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2019-05-21 21:49:04,372 DEBUG - service - Input queue at end of handle_keypress: deque([], maxlen=150)
2019-05-21 21:49:04,373 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
```

## Notes

Adding time delay (sleep for 0.1s at the start of the script) seems to fix it (or drastically reduce the probability of freezes). My guess that 'Remove typed abbreviation' erases the typed text by sending bunch of backspaces, which conflicts with the keyboard.send_keys() that is invoked right at the start. It might also not be noticeable with shorted abbreviations, as there ar less backspaces sent.

**Comment by luziferius** [comment]
This is a duplicate of #86 

I still haven’t found a fix for this. The `window.get_active_title()` function somehow causes a thread to spin in an infinite loop. That threads holds a mutex, which blocks the interface functionality for other scripts or phrases.

I can reproduce it here, but I’m somewhat unable to get any Stacktrace, so can’t really find the root cause.

**Comment by andrisz** [comment]
Oh, right you are. Played around a bit more and posted my observations in #86 
Regarding stacktrace, sometimes I was getting
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 242, in __eventLoop
    method(*args)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 800, in __sendKey
    self.__sendKeyCode(self.__lookupKeyCode(keyName))
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 995, in __sendKeyCode
    self.__sendKeyPressEvent(keyCode, modifiers, theWindow)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1020, in __sendKeyPressEvent
    focus = self.localDisplay.get_input_focus().focus
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 566, in get_input_focus
    return request.GetInputFocus(display = self.display)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/rq.py", line 1478, in __init__
    self.reply()
  File "/usr/lib/python3/dist-packages/Xlib/protocol/rq.py", line 1490, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 643, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 727, in parse_request_response
    % (req._serial, sno))
RuntimeError: Expected reply for request 2129, but got 2130.  Can't happen!
```
Is it relevant? I could imagine keyboard.send_keys() grabbing window.get_active_title() response from Xlib, but that's just a wild guess, have no idea what's happening there :/

**Comment by luziferius** [comment]
Those API calls are largely synchronous or processed through a serializing queue. Maybe the serialization is not 100% reliable. And XLib does not like multithreaded applications (like AutoKey)

It’ll lock up even without this Exception being thrown.

When this happens, you should be able to observe that AutoKey uses 100% of one CPU core. The GUI still reacts, but trying to exit AK will result in a hang.

**Comment by markplagge** [comment]
Hey I wanted to chime in and add to what @luziferius said. I have been
experiencing the same issue. First off, I don't know if this helps, but
I've been running on a RHEL 7.6 system. I've tried using the system
python install, as well as various Anaconda installs. I'd be happy to
provide more info about the system config - but what I really want to
add is that adding the sleep for 0.1 has eliminated the problem. I
played with various spots to add a delay, including adding it to the
`window.get_active_class()` function. However, even when I had a delay
inside the `get_active_class()` and/or the get title functions, I would
still get the hang. 

What worked for me was adding it to the section of my keyboard script
*before* any calls to `keyboard.send_keys()`. I'm including an example
from one of my scripts below, hopefully this helps.


```
if window.get_active_class() != 'gnome-terminal-server.Gnome-terminal' and "mate-terminal" not in  window.get_active_class():
    if "jetbrains" in window.get_active_class():
        time.sleep(.01)
        keyboard.send_keys("<meta>+c")
    else:
        time.sleep(.01)
        keyboard.send_keys("<ctrl>+c")
else:
    time.sleep(.01)
    keyboard.send_keys("<ctrl>+<shift>+c")
```


Hope that this helps anyone who is experiencing hard freezes with this
amazing software.

**Comment by Yekutiel** [comment]
I have set up AutoKey so that when I type in, for example, `.abc` AutoKey is supposed to replace  `.abc` with something like `A bunch of carrots`.

"Hangs when using abbreviation to send text via script"... seems to essentially describe the problem I'm having with AutoKey phrases. AutoKey will work properly a few times for me yet after, say, three or four or five times of typing in abbreviations such as `.abc`  my machine will partially or completely freeze up. I end up restarting my machine with a hard reboot. This bug essentially makes AutoKey worthless to me.

I don't know how to write Python scripts and frankly, prefer not to learn how to write them. Therefore, I have a feature request... **Delay of X seconds to help prevent AutoKey from hanging**.

Use case: I'd put , say, 0.1 seconds into **Delay of X seconds to help prevent AutoKey from hanging** to, hopefully, prevent my machine from eventually hanging when I'm using AutoKey.

Interestingly, about twenty years ago I had a very similar problem with a [Perfect Keyboard](https://www.pitrinec.com/products/perfect-keyboard) "...an autotext and text expander macro software for Windows." Perfect Keyboard was hanging when I created "macros" (that's what they were called in Perfect Keyboard) to cause abbreviations to be replaced by large blocks of text. By adding short delays to Perfect Keyboard I was able to prevent it from hanging.

If that's too much trouble, then how about creating a very simple Python script (which I presume would be a text file) for non-technical users (like me) that would enable us to create simple Python scripts with delays of X seconds similar to what @markplagge described in https://github.com/autokey/autokey/issues/286#issuecomment-523084682 so that we would be able to add a delay of X seconds to AutoKey phrases such as `.abc` to be replaced by `A bunch of carrot`? 

I presume this Python script for non-technical users would contain an example such as, `.def` to be replaced by `A dog entertaining a family` with comments explaining the purpose and use of the delay of X seconds as well as also explaining where in the directory tree to place that Python script.

Sure, fixing the bug would be ideal. It always is. But practically speaking, if I could easily circumvent the bug, then, for me at least, that would function in lieu of an actual bug fix.

In my experience, developers enjoy development and dislike fixing bugs. This is probably even more pronounced with FOSS projects wherein developers are volunteering their time. Regardless of the reason, the facts are unequivocal: generally-speaking unsolved bugs tend to pile up. Therefore, circumventing bugs is sometimes the most feasible course of action.

**Comment by josephj11** [comment]
It would of course be better if we could find and fix the source of this problem. However, as Thomas notes above, this isn't so easy. If you want to try a workaround script for this, it woud just be

```
import time
time.sleep(0.1)
keyboard.send_keys("the text you want to emit")
```

To use it, you would create a new script in AutoKey and paste the above code into it, replacing the text argument with your desired text.

You need to do it from inside AutoKey because AutoKey will automatically generate a file of metadata for the script so it knows how to process it later. This is a (hidden) file with the same name as your new script with a prefix of "." to make it hidden and a suffix of ".json".

You could also create this file manually by editing a copy of a template file, but if you're not comfortable with programming, it might be easier just to let AutoKey create it for you.
AutoKey will also create the files in the right location without you having to do so manually.

As for development, your concern is valid in general. However, Thomas has been working very diligently on this project for over a year now.  I haven't done any tallies, but I would bet that around 95% of his efforts have been on bug fixes and the few that are enhancements have been things that "should" work, but don't. We haven't added any really new features in a long time.

However, as you can see by my references to "Thomas", instead of "the developers", we have only one current developer (and a few people who occasionally submit small fixes and documentation), so it takes time to get to everything and when a fix is problematic, it tends to get put aside so that other things which are more straight forward can get done.

**Comment by Yekutiel** [comment]
Hi @josephj11,

Thank you for your prompt and helpful reply. In particular I appreciate your **clear instructions**. 
 
I pasted the following text into a new script which I just created  in AutoKey...
```
import time
time.sleep(0.1)
keyboard.send_keys("testing123")
```
and I was able to successfully trigger it by typing in “.abc”! **Yeah!!!**
 
Please see the screenshot which I have attached to this message.
 
By the way, I suggest that you  consider suggesting to users that they prepend a “.” or a “,” to their abbreviations when using an abbreviation in AutoKey.
 
I realize that fixing some bugs can be vexing and time-consuming. At the end of the day the overwhelming majority of users are interested in functionality. What you provided to me it is a simple yet very functional solution. Therefore, as long as it continues to work for me I don't care if the bug which I indicated in my previous message is ever fixed at all. Of course I realize that  most software developers do not like glaring bugs to be left “hanging around.” But I am not a software developer. 
 
Also, I was glad to create the script from within AutoKey  because I don't want to mess around with Python scripts unless I need to. I'm merely an ordinary user not a software developer. Over the decades I've been told that I should learn CP/M, MS-DOS, Fortran, Pascal and all sorts of other technical mumbo-jumbo which I have assiduously avoided learning.  Some people manufacturer automobiles; others repair automobiles; and finally  some people drive automobiles. In that analogy I would be a driver.
 
I appreciate Thomas' efforts and your efforts. Frankly I don't see any reason whatsoever for him to fix the the bug I indicated in my previous message. Like I indicated in my previous message usually workarounds are easier than difficult bug fixes.  I have worked with many engineers.  When a difficult bug is encountered, I've learned to prefer workarounds in favor of bug fixes.
 
As for adding new features, I don't see any new features which I would want to see added to AutoKey. It seems to be a simple little utility that is remarkably powerful and useful, which unsurprisingly, is my favorite kind of utility.

Keep up the good work!

Thank you for your help!

Yekutiel

**Comment by Yekutiel** [comment]
Hi @josephj11,

The following works for sentences but not for paragraphs...

> import time
> time.sleep(0.1)
> keyboard.send_keys("the text you want to emit")

For example,

```
import time
time.sleep(0.1)
keyboard.send_keys("testing123")
```

works fine. But,

```
import time
time.sleep(0.1)
keyboard.send_keys("This is sentence 1.

This is sentence 2.

This is sentence 3.")
```
does not work. 

When I run the script that begins with "This is sentence 1" I receive the following error message...

"The script XYZ encountered an error" where XYZ = the name of the script that begins with "This is sentence 1".

Do you have another quick and easy workaround for me?

If you don't then I am willing to learn how to create Python scripts.

Thanks,

Yekutiel

**Comment by Yekutiel** [comment]
For anyone who might be interested, I found the answer here...

[How To Format Text in Python 3](https://www.digitalocean.com/community/tutorials/how-to-format-text-in-python-3)

Multiple Lines

Printing strings on multiple lines can make text more readable to humans. With multiple lines, strings can be grouped into clean and orderly text, formatted as a letter, or used to maintain the linebreaks of a poem or song lyrics.

**To create strings that span multiple lines, triple single quotes ''' or triple double quotes """ are used to enclose the string.**

'''
This string is on 
multiple lines
within three single 
quotes on either side.
'''

"""
This string is on 
multiple lines
within three double 
quotes on either side.
"""

With triple quotes, you can print strings on multiple lines to make text, especially lengthy text, easier to read.

**Comment by josephj11** [comment]
@Yekutiel I'm a Python newbie, so I'm sure there's a much better way to do this, but this will work:

```
import time
time.sleep(0.1)
keyboard.send_keys("This is sentence 1.<enter>\
<enter>\
This is sentence 2.<enter>\
<enter>\
This is sentence 3.<enter>")
```
The backslashes are the last character on the line. They escape the newline at the end of the line so Python sees the whole thing as one line.

In fact, since this method explicitly adds the newlines `<enter>`, you could put the whole thing on one line. It would just be harder for humans to read the script.

Probably the "right"/Pythonic way to do this is with a block quote:

```
import time
time.sleep(0.1)
keyboard.send_keys(
'''
This is sentence 1.

This is sentence 2.

This is sentence 3.
'''
)
```

**Comment by Yekutiel** [comment]
@josephj11 

> Probably the "right"/Pythonic way to do this is with a block quote:
> 
> ```
> import time
> time.sleep(0.1)
> keyboard.send_keys(
> '''
> This is sentence 1.
> 
> This is sentence 2.
> 
> This is sentence 3.
> '''
> )
> ```

Thanks for your suggestion. Actually your suggestion is essentially what I indicated in https://github.com/autokey/autokey/issues/286#issuecomment-550888219

**Comment by josephj11** [comment]
I was editing/testing when you posted.

When we get into issues of how to do things (as opposed to working on AutoKey issues/bugs/enhancements), it is much better and often faster to post on our [support list](https://groups.google.com/forum/#!forum/autokey-users). There are more people there who can help and more who may benefit by finding the discussions later.

**Comment by Yekutiel** [comment]
@josephj11 

Thanks for letting me know. I intend to post a question to the AutoKey support list soon.
