### ISSUE TITLE
Error on start up

### ISSUE THREAD

**Issue by THMonster** [autokey/autokey#301]
## Classification:

Crash(gui only)

## Reproducibility:

Always

## Version

AutoKey version: 0.95.7

Used GUI (Gtk, Qt, or both): Qt

Installed via: AUR

Linux Distribution: Archlinux

## Summary

```
2019-08-06 21:59:47,966 ERROR - root - Fatal error starting AutoKey: <built-in function connectSlotsByName> returned a result with an error set
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/qtapp.py", line 132, in __init__
    self.configWindow = ConfigWindow(self)
  File "/usr/lib/python3.7/site-packages/autokey/qtui/configwindow.py", line 44, in __init__
    self.setupUi(self)
  File "<string>", line 12, in setupUi
  File "/usr/lib/python3.7/site-packages/autokey/qtui/centralwidget.py", line 40, in __init__
    self.setupUi(self)
  File "<string>", line 38, in setupUi
  File "/usr/lib/python3.7/site-packages/autokey/qtui/phrasepage.py", line 34, in __init__
    self.setupUi(self)
  File "<string>", line 46, in setupUi
  File "/usr/lib/python3.7/site-packages/autokey/qtui/settingswidget.py", line 40, in __init__
    self.hotkey_settings_dialog = HotkeySettingsDialog(self)
  File "/usr/lib/python3.7/site-packages/autokey/qtui/dialogs/hotkeysettings.py", line 49, in __init__
    self.setupUi(self)
  File "<string>", line 58, in setupUi
SystemError: <built-in function connectSlotsByName> returned a result with an error set
```

## Steps to Reproduce (if applicable)

- just run autokey-qt

## Expected Results

Show gui normally.

## Actual Results

Cannot open gui.
![image](https://user-images.githubusercontent.com/5125031/62546715-92434c80-b896-11e9-809c-b44d1c885428.png)

**Comment by THMonster** [comment]
Due to the new version of pyqt?
![image](https://user-images.githubusercontent.com/5125031/62547173-59f03e00-b897-11e9-8f90-56e439194380.png)

**Comment by josephj11** [comment]
This will require the attention of Thomas, our current developer.

While you're waiting, can you use the autokey-gtk front end?

Is this a new install or is it the case that AutoKey was already installed and working and only broke after you updated some other packages such as the one you mentioned?

**Comment by THMonster** [comment]
@josephj11 autokey-gtk works well.
And this is not a new installation, autokey-qt worked good before.
But I'm not using it everyday, so I'm not sure it broked since when.

**Comment by The-Dark-Passenger** [comment]
I too am having this issue. I am currently trying to run AutoKey on Slackware64 -current. I have Qt 5.13 and PyQt5 5.12.3 installed. The errors I see are exactly the same as @IsoaSFlus

**Comment by DonaldSch** [comment]
I have also just developed this problem after updating Manjaro Linux.
I can use autokey-gtk but not autokey-qt which gives the same error dialog as above.
The following is the logging output I get.

autokey-qt -l
2019-08-22 15:17:11,962 INFO - root - Initialising application
2019-08-22 15:17:11,990 INFO - root - Initialise global hotkeys
2019-08-22 15:17:11,990 INFO - config-manager - Loading config from existing file: /home/donald/.config/autokey/autokey.json
2019-08-22 15:17:11,991 DEBUG - config-manager - Loading folder at '/home/donald/.config/autokey/data/Phrases'
2019-08-22 15:17:11,993 DEBUG - config-manager - Loading folder at '/home/donald/.config/autokey/data/Scripts'
2019-08-22 15:17:11,994 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2019-08-22 15:17:11,994 DEBUG - inotify - Adding watch for /home/donald/.config/autokey/data/Phrases
2019-08-22 15:17:11,995 DEBUG - inotify - Adding watch for /home/donald/.config/autokey/data/Phrases/Addresses
2019-08-22 15:17:11,995 DEBUG - inotify - Adding watch for /home/donald/.config/autokey/data/Phrases/ecwid
2019-08-22 15:17:11,995 DEBUG - inotify - Adding watch for /home/donald/.config/autokey/data/Phrases/ecwid/email
2019-08-22 15:17:11,995 DEBUG - inotify - Adding watch for /home/donald/.config/autokey/data/Scripts
2019-08-22 15:17:11,995 INFO - config-manager - Successfully loaded configuration
2019-08-22 15:17:11,995 DEBUG - inotify - Adding watch for /home/donald/.config/autokey/data
2019-08-22 15:17:11,995 DEBUG - inotify - Adding watch for /home/donald/.config/autokey
2019-08-22 15:17:11,995 DEBUG - config-manager - Global settings: {'isFirstRun': False, 'serviceRunning': True, 'menuTakesFocus': False, 'showTrayIcon': True, 'sortByUsageCount': False, 'promptToSave': True, 'enableQT4Workaround': False, 'interfaceType': 'XRecord', 'undoUsingBackspace': True, 'windowDefaultSize': [1312, 735], 'hPanePosition': 308, 'columnWidths': [100, 47, 268], 'showToolbar': True, 'notificationIcon': 'autokey-status', 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'triggerItemByInitial': False, 'scriptGlobals': {}}
2019-08-22 15:17:11,996 INFO - service - Starting service
2019-08-22 15:17:12,014 DEBUG - interface - Enabling sending using Alt-Grid
2019-08-22 15:17:12,014 DEBUG - interface - Modifier masks: {<Key.SHIFT: '<shift>'>: 1, <Key.CAPSLOCK: '<capslock>'>: 2, <Key.CONTROL: '<ctrl>'>: 4, <Key.ALT: '<alt>'>: 8, <Key.ALT_GR: '<alt_gr>'>: 128, <Key.SUPER: '<super>'>: 64, <Key.HYPER: '<hyper>'>: 64, <Key.META: '<meta>'>: 8, <Key.NUMLOCK: '<numlock>'>: 16}
2019-08-22 15:17:12,040 DEBUG - interface - Alt-Grid: XK_ISO_Level3_Shift, 65027
2019-08-22 15:17:12,041 DEBUG - interface - X Server Keymap, listing unmapped keys.
2019-08-22 15:17:12,041 DEBUG - iomediator - Set modifier Key.CAPSLOCK to False
2019-08-22 15:17:12,041 DEBUG - iomediator - Set modifier Key.NUMLOCK to True
2019-08-22 15:17:12,042 DEBUG - interface - Grabbing hotkey: ['<super>'] 'k'
2019-08-22 15:17:12,042 DEBUG - interface - Grabbing hotkey: ['<shift>', '<super>'] 'k'
2019-08-22 15:17:12,042 DEBUG - interface - __flushEvents: Entering event loop.
2019-08-22 15:17:12,042 DEBUG - interface - Grabbing hotkey: ['<alt>'] 'a'
2019-08-22 15:17:12,042 INFO - iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2019-08-22 15:17:12,042 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>'] 'd'
2019-08-22 15:17:12,043 DEBUG - interface - Grabbing hotkey: ['<ctrl>'] '<f7>'
2019-08-22 15:17:12,043 DEBUG - interface - Grabbing hotkey: ['<ctrl>'] '<f9>'
2019-08-22 15:17:12,043 DEBUG - interface - Grabbing hotkey: ['<ctrl>'] '<f8>'
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 274, sequence_number = 35, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 274, sequence_number = 36, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 274, sequence_number = 37, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 274, sequence_number = 38, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 274, sequence_number = 39, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 274, sequence_number = 40, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 274, sequence_number = 41, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 274, sequence_number = 42, major_opcode = 33, minor_opcode = 0
2019-08-22 15:17:12,049 INFO - interface - XRecord interface thread starting
2019-08-22 15:17:12,049 INFO - service - Service now marked as running
2019-08-22 15:17:12,049 DEBUG - root.Qt-GUI.System-tray-notifier - Creating system tray icon notifier.
2019-08-22 15:17:12,055 INFO - root.Qt-GUI.System-tray-notifier - Creating static context menu actions.
2019-08-22 15:17:12,056 DEBUG - root.Qt-GUI.System-tray-notifier - Show tray icon enabled in settings: True
2019-08-22 15:17:12,056 INFO - root.Qt-GUI.System-tray-notifier - Rebuilding model item actions, adding all items marked for access through the tray icon.
2019-08-22 15:17:12,056 DEBUG - phrase-menu - Sorting phrase menu by item name/title
2019-08-22 15:17:12,058 DEBUG - root.Qt-GUI.System-tray-notifier - About to show the tray icon.
2019-08-22 15:17:12,061 INFO - root.Qt-GUI.System-tray-notifier - System tray icon notifier created.
2019-08-22 15:17:12,062 DEBUG - root.Qt-GUI.CentralWidget - CentralWidget instance created.
2019-08-22 15:17:12,117 ERROR - root - Fatal error starting AutoKey: <built-in function connectSlotsByName> returned a result with an error set
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/qtapp.py", line 132, in __init__
    self.configWindow = ConfigWindow(self)
  File "/usr/lib/python3.7/site-packages/autokey/qtui/configwindow.py", line 44, in __init__
    self.setupUi(self)
  File "<string>", line 12, in setupUi
  File "/usr/lib/python3.7/site-packages/autokey/qtui/centralwidget.py", line 40, in __init__
    self.setupUi(self)
  File "<string>", line 38, in setupUi
  File "/usr/lib/python3.7/site-packages/autokey/qtui/phrasepage.py", line 34, in __init__
    self.setupUi(self)
  File "<string>", line 46, in setupUi
  File "/usr/lib/python3.7/site-packages/autokey/qtui/settingswidget.py", line 40, in __init__
    self.hotkey_settings_dialog = HotkeySettingsDialog(self)
  File "/usr/lib/python3.7/site-packages/autokey/qtui/dialogs/hotkeysettings.py", line 49, in __init__
    self.setupUi(self)
  File "<string>", line 58, in setupUi
SystemError: <built-in function connectSlotsByName> returned a result with an error set

KDE plasma 5.16.4
KDE Frameworks 5.60.0
Qt 5.13.0
Kernel 4.19.66-1 MANJARO
Autokey 0.95.7

**Comment by josephj11** [comment]
@IsoaSFlus Why did you close this issue? Was the problem resolved somehow? Two other users commented that they have encountered the same issue.

**Comment by THMonster** [comment]
@josephj11  I'm sorry. But I don't have this issue anymore. So I think it is obviously resolved. If you want, I can reopen it.

**Comment by Roboron3042** [comment]
I can confirm this issue seems to be resolved - with no updates from Autokey. Probably it was resolved from QT.

**Comment by luziferius** [comment]
I wasn’t around during summer, so I didn’t notice this earlier. There _was_ an issue with AutoKey. With Python 3.7.4, PyQt5 between 5.11 and 5.13.0 stopped swallowing certain error messages previously silenced inside PyQt5. Those started to be reported when these versions were combined that way. You probably got the 5.13.1 update for PyQt5 which silenced those again.

I just fixed this on AutoKey’s side for everyone running into it again. If you are curious: It was triggered inside a GUI class by the combination of using Python properties and loading the GUI type from Qt Designer UI files. Using Python properties caused PyQt5 to access attributes that were not available while `setupUI` ran during `__init__()`. Not using properties prevents this from happening.

@The-Dark-Passenger @DonaldSch This is fixed in the current `master` branch and the fix will be included in the next bugfix release. To be released in the next few days.
