### ISSUE TITLE
Autokey-Qt doesn't work

### ISSUE THREAD

**Issue by VladimirMikulic** [autokey/autokey#310]
## Summary

When I try to run the app, I get this:
```
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 11, in <module>
    load_entry_point('autokey==0.95.7', 'console_scripts', 'autokey-qt')()
  File "/home/vlado/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/vlado/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/vlado/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/vlado/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/autokey/qtui/__main__.py", line 23, in <module>
    from autokey.qtapp import Application
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 41, in <module>
    from autokey.qtui.configwindow import ConfigWindow
  File "/usr/lib/python3/dist-packages/autokey/qtui/configwindow.py", line 40, in <module>
    class ConfigWindow(*autokey.qtui.common.inherits_from_ui_file_with_name("mainwindow")):
  File "/usr/lib/python3/dist-packages/autokey/qtui/common.py", line 146, in load_ui_from_file
    base_type = uic.loadUiType(ui_file, from_imports=True)
  File "/home/vlado/.local/lib/python3.6/site-packages/PyQt5/uic/__init__.py", line 203, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 292, in <module>
  File "/usr/lib/python3/dist-packages/autokey/qtui/centralwidget.py", line 35, in <module>
    class CentralWidget(*ui_common.inherits_from_ui_file_with_name("centralwidget")):
  File "/usr/lib/python3/dist-packages/autokey/qtui/common.py", line 146, in load_ui_from_file
    base_type = uic.loadUiType(ui_file, from_imports=True)
  File "/home/vlado/.local/lib/python3.6/site-packages/PyQt5/uic/__init__.py", line 203, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 67, in <module>
  File "/usr/lib/python3/dist-packages/autokey/qtui/scriptpage.py", line 20, in <module>
    from PyQt5 import Qsci
ImportError: cannot import name 'Qsci'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_autokey-qt.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 11, in <module>
    load_entry_point('autokey==0.95.7', 'console_scripts', 'autokey-qt')()
  File "/home/vlado/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/vlado/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/vlado/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/vlado/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/autokey/qtui/__main__.py", line 23, in <module>
    from autokey.qtapp import Application
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 41, in <module>
    from autokey.qtui.configwindow import ConfigWindow
  File "/usr/lib/python3/dist-packages/autokey/qtui/configwindow.py", line 40, in <module>
    class ConfigWindow(*autokey.qtui.common.inherits_from_ui_file_with_name("mainwindow")):
  File "/usr/lib/python3/dist-packages/autokey/qtui/common.py", line 146, in load_ui_from_file
    base_type = uic.loadUiType(ui_file, from_imports=True)
  File "/home/vlado/.local/lib/python3.6/site-packages/PyQt5/uic/__init__.py", line 203, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 292, in <module>
  File "/usr/lib/python3/dist-packages/autokey/qtui/centralwidget.py", line 35, in <module>
    class CentralWidget(*ui_common.inherits_from_ui_file_with_name("centralwidget")):
  File "/usr/lib/python3/dist-packages/autokey/qtui/common.py", line 146, in load_ui_from_file
    base_type = uic.loadUiType(ui_file, from_imports=True)
  File "/home/vlado/.local/lib/python3.6/site-packages/PyQt5/uic/__init__.py", line 203, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 67, in <module>
  File "/usr/lib/python3/dist-packages/autokey/qtui/scriptpage.py", line 20, in <module>
    from PyQt5 import Qsci
ImportError: cannot import name 'Qsci'
```

**Comment by josephj11** [comment]
Our developer has been inactive for a couple of months. Try `autokey-gtk` as a workaround until someone can look at this.

**Comment by luziferius** [comment]
This depends on how you installed AutoKey and how your distribution handles Qt5 and PyQt5 packages. You need the Qsci Qt module, which provides the text editor with syntax highlighting that AutoKey uses.

Some distributions bundle it, some, like Ubuntu, put it into additional and optional packages.

Search your package repositories for `Qsci` and install the Python 3 & Qt 5 compatible package.

For reference, this exactly defines the dependencies for Debian-based distributions: https://github.com/autokey/autokey/blob/master/debian/control

As far as I know, KDE Neon is based on Debian, so it should be:
https://github.com/autokey/autokey/blob/86e7a85d723753143f78e0684290a362bf6789c6/debian/control#L79
Note that you also need the SVG module, due to a workaround for a Qt bug in place.

**Comment by VladimirMikulic** [comment]
I've installed all dependencies, but error persists.

**Comment by luziferius** [comment]
Sorry, my fault. I always mix up the meaning of `ImportError` and think it's a `ModuleNotFoundError` on first sight... This particular error is normally caused by a cyclic import. Here it seems to be a somewhat  messed up Python module system.

What seems strange: Your Python loads the `distutils` package (that in turn is used to load AutoKey) from `.local/lib/python3.6`, meaning that `distutils` or `setuptools` is a local `pip3` installation. Such local overwrites may break packages in strange ways. (I experiences those breakages first-hand.) I recommend removing all locally installed Python packages you don't require from `.local/lib/python3.6` by using a `pip3 uninstall` on them. 

But first, try to run AutoKey from the Python prompt to circumvent the setuptools call. Open a terminal, run `python3`.

There execute
``` python
import autokey.qtapp
autokey.qtapp.Application()
```

This will run AutoKey without the setuptools launcher.
Beware: It may start silently in the background. Look out for the icon in the hidden part of the system tray. No console output is mostly a good thing.

If AutoKey starts this way, your local Python environment should be cleaned up.

**Comment by luziferius** [comment]
Now I've seen it. You have a local PyQt5 installation in `.local/lib/python3.6/site-packages`. This _shadows_ the global installation and misses the required add-ons:

> `File "/home/vlado/.local/lib/python3.6/site-packages/PyQt5/uic/__init__.py", line 203, in loadUiType`

Either remove it and use the system provided version, or (not recommended) install the Qsci plug-in from PyPI if you require that specific PyQt5 version for some reason.

**Comment by VladimirMikulic** [comment]
@luziferius removing `.local/lib/python3.6/site-packages` fixed my issue. Thanks a lot!

**Comment by luziferius** [comment]
Glad to hear.

And as an additional tip: Clean now-broken symlinks and python setuptools-generated launchers in `.local/bin` as well, to keep your system tidy. In the future you can use `pip3 uninstall <PACKAGENAME>` (without root rights) to cleanly uninstall locally installed Python apps and libs. :)

When installing things with pip, it is sometimes way too greedy and installes too much, duplicating already installed libs and causing such issues you just experienced.

**Comment by VladimirMikulic** [comment]
> And as an additional tip: Clean now-broken symlinks and python setuptools-generated launchers in `.local/bin` as well, to keep your system tidy. In the future you can use `pip3 uninstall <PACKAGENAME>` (without root rights) to cleanly uninstall locally installed Python apps and libs. :)
> 
> When installing things with pip, it is sometimes way too greedy and installes too much, duplicating already installed libs and causing such issues you just experienced.

I didn't know pip is such a monster :)
