### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by Mrodent** [autokey/autokey#314]
## Classification:

N/A installation problem

## Reproducibility:

Always - on my sys

## Version

AutoKey version: 0.95

Used GUI (Gtk, Qt, or both): 

If the problem is known to be present in more than one version, please list all of those.

Tried downloaded .debs as per installation  instructions. I can't really seem to use pip3 because your instructions say use "dbus-python" from your local repository. But my Synaptic repo doesn't have "dbus-python".  Although it has several "dbus-*" and also "python-dbus". Are these relevant?

Linux Distribution: Linux Mint 18.3 (based on Ubuntu Xenial).

## Summary

Can't install v0.95

## Expected Results

Installation

## Actual Results

```
 sudo dpkg --install autokey-common_0.95.7-0_all.deb autokey-gtk_0.95.7-0_all.deb 
[sudo] password for chris: 
Selecting previously unselected package autokey-common.
(Reading database ... 262082 files and directories currently installed.)
Preparing to unpack autokey-common_0.95.7-0_all.deb ...
Unpacking autokey-common (0.95.7-0) ...
Selecting previously unselected package autokey-gtk.
Preparing to unpack autokey-gtk_0.95.7-0_all.deb ...
Unpacking autokey-gtk (0.95.7-0) ...
dpkg: dependency problems prevent configuration of autokey-common:
 autokey-common depends on python3-pyinotify; however:
  Package python3-pyinotify is not installed.

dpkg: error processing package autokey-common (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of autokey-gtk:
 autokey-gtk depends on autokey-common (= 0.95.7-0); however:
  Package autokey-common is not configured yet.

dpkg: error processing package autokey-gtk (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for desktop-file-utils (0.22+linuxmint1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 autokey-common
 autokey-gtk


```
If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

## Notes

Describe any debugging steps you've taken yourself.

NB this is what happened when I tried to use pip3 in a virtual environment to install dbus-python:

```
(test_venv369) chris@M17A ~ $  pip3 install dbus-python
Collecting dbus-python
  Using cached https://files.pythonhosted.org/packages/b6/85/7b46d31f15a970665533ad5956adee013f03f0ad4421c3c83304ae9c9906/dbus-python-1.2.12.tar.gz
Installing collected packages: dbus-python
    Running setup.py install for dbus-python ... error
    ERROR: Command errored out with exit status 1:
     command: /home/chris/python_venvs/test_venv369/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dnkkklb_/dbus-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dnkkklb_/dbus-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ma9_x8gj/install-record.txt --single-version-externally-managed --compile --install-headers /home/chris/python_venvs/test_venv369/include/site/python3.6/dbus-python
         cwd: /tmp/pip-install-dnkkklb_/dbus-python/
    Complete output (138 lines):
    running install
    running build
    creating /tmp/pip-install-dnkkklb_/dbus-python/build
    creating /tmp/pip-install-dnkkklb_/dbus-python/build/temp.linux-x86_64-3.6
    [...]
    checking for a version of Python >= '2.7'... yes
    checking for the distutils Python package... yes
    checking for Python include path... -I/usr/include/python3.6m
    checking for Python library path... -L/usr/lib -lpython3.6m
    checking for Python site-packages path... /home/chris/python_venvs/test_venv369/lib/python3.6/site-packages
    checking python extra libraries... -lpthread -ldl  -lutil -lm
    checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
    checking consistency of all components of python development environment... no
    configure: error: in `/tmp/pip-install-dnkkklb_/dbus-python/build/temp.linux-x86_64-3.6':
    configure: error:
      Could not link test program to Python. Maybe the main Python library has been
      installed in some non-standard library path. If so, pass it to configure,
      via the LIBS environment variable.
      Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
      ============================================================================
       ERROR!
       You probably have to install the development version of the Python package
       for your distribution.  The exact name of this package varies among them.
      ============================================================================
    
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dnkkklb_/dbus-python/setup.py", line 111, in <module>
        tests_require=['tap.py'],
      File "/home/chris/python_venvs/test_venv369/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/chris/python_venvs/test_venv369/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-dnkkklb_/dbus-python/setup.py", line 64, in run
        cwd=builddir)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-dnkkklb_/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/home/chris/python_venvs/test_venv369/bin/python3.6', '--prefix=/tmp/pip-install-dnkkklb_/dbus-python/build/temp.linux-x86_64-3.6/prefix']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/chris/python_venvs/test_venv369/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dnkkklb_/dbus-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dnkkklb_/dbus-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ma9_x8gj/install-record.txt --single-version-externally-managed --compile --install-headers /home/chris/python_venvs/test_venv369/include/site/python3.6/dbus-python Check the logs for full command output.

```

If you've found a workaround, please provide it here.

**Comment by luziferius** [comment]
Which instructions did you use? You may have stumbled upon some outdated resources.
The _Installing_ Wiki page here (https://github.com/autokey/autokey/wiki/Installing) tells to run
`sudo apt --fix-broken install` after running `dpkg`. This’ll take care of installing all dependencies.

I think I’ll update that page to make this step more clear.

Edit: Ok, I’ve put more emphasis on running `sudo apt --fix-broken install` in the instructions.

The commands that install all dependencies upfront is placed a bit below on the Wiki page. To be precise, it is here: https://github.com/autokey/autokey/wiki/Installing#installing-dependencies-for-debian. The package you want is called `python3-dbus` on Debian/Ubuntu. 

And about the `dbus` situation. Yeah, this whole thing is unfortunate. If you try to use a virtual environment, it’ll try to compile the C library bindings and require the dbus development headers. Those can’t be installed from PyPI, as those are not a Python library. Thus the headers have to be installed from the Distro’s repositories anyways. If you actually manage to build the package from PyPI, it starts to _shadow_ plugins required by other software and breaks those. Let’s just say that I tried several days to get it working in a virtual environment and finally gave up…

**Comment by Mrodent** [comment]
Thanks for responding.  Will try again when I get a chance.

**Comment by BlueDrink9** [comment]
@josephj11 this seems to have been abandoned, can probably close
