### ISSUE TITLE
Moving multiple files in GTK GUI deletes half of them

### ISSUE THREAD

**Issue by dovry** [autokey/autokey#317]
## Version

AutoKey version: 0.95.1

Used GUI: GTK

Installed via: PPA

Linux Distribution: Ubuntu 18.04

## Summary

Ctrl+Selecting multiple files deletes around half of the files selected, without warning, and rarely, but sometimes moves about a quarter to the desired location, rest is unmoved.

## Steps to Reproduce (if applicable)

1. Create 10 new files and 1 folder
1. Ctrl+Select all the new files
1. While still holding Ctrl, drag any of the selected files to the newly created folder
1. Panic because you just lost about half of your hotkeys/scripts

## Expected Results

All the selected files should move to the desired folder

## Actual Results

Half of the files are deleted without warning

[debug log](https://termbin.com/zewb)

## Notes

Workaround with GTK is to go into the default folder in a file explorer/terminal and move the files there.

Qt does not have this problem. I have switched to that now as it is more responsive and looks better.

**Comment by Dovry** [comment]
Qt does not have this problem. I have switched to that now as it is more responsive and looks better.

**Comment by josephj11** [comment]
While this appears to be a valid bug, I think any mass changes such as this are easier to do in a file manager/terminal. You just have to remember to also move the hidden .json files along with the visible phrase and script files (and to restart AutoKey afterward so it sees the changes.)

Of course, scripts and phrases take a lot of work to create and maintain, so they should be backed up regularly. Panic == bad!  ;)

Speculation:
I believe (unverified) that AutoKey sometimes deletes things because it creates directories (possibly without checking if they already exist.) You'd have to experiment with this, but I expect that if you create a new (empty) directory first from inside AutoKey and then drag things into it - probably even including subdirectories - everything will get there in one piece.

If you do experiment with this, we need feedback to narrow down exactly what the problem is.

Notes:
AutoKey allows you to specify the location of a folder when you create it, so it can be external to the AutoKey configuration directories. Using external folders preserves your phrases and scripts even if you uninstall or purge AutoKey when debugging/upgrading.

While 0.95.1 is fairly recent, you should consider upgrading to the current release, 0.95.7. (We don't have write access to the PPA to update it.) Instructions are [here](https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives).

This is unlikely to affect this particular issue, but it will help you avoid lots of others and it will be where a new release which hopefully fixes this issue will be once it is created.

**Comment by dovry** [comment]
>Of course, scripts and phrases take a lot of work to create and maintain, so they should be backed up regularly. Panic == bad! ;)

100% correct, which is why I was trying to organize my scripts to prepare them for back ups... I've since upgraded to the latest Qt release, as you have advised.

I might try QA'ing more in GTK later, for now I will start rewriting what I lost :disappointed:

**Comment by luziferius** [comment]
There is definitely something fishy. I lost some placeholder items i created for this.

And I was able to generate this stacktrace while playing around with Drag&Drop in the GTK GUI:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 830, in _getiter
    aiter = self.get_iter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 867, in get_iter
    raise ValueError("invalid tree path '%s'" % path)
ValueError: invalid tree path '2:0:1:1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/Daten/Projekte/autokey/lib/autokey/gtkui/configwindow.py", line 1407, in on_drag_data_received
    self.__removeItem(theModel, theModel[path].iter)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 842, in __getitem__
    aiter = self._getiter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 832, in _getiter
    raise IndexError("could not find tree path '%s'" % key)
IndexError: could not find tree path '2:0:1:1'
```
These functions are responsible for drag&drop, but I have no idea how exactly they work…:

https://github.com/autokey/autokey/blob/fddd8fe7d54dc59f0b40f919a6df8d8272190b3a/lib/autokey/gtkui/configwindow.py#L1357-L1360

https://github.com/autokey/autokey/blob/fddd8fe7d54dc59f0b40f919a6df8d8272190b3a/lib/autokey/gtkui/configwindow.py#L1393-L1426

https://github.com/autokey/autokey/blob/fddd8fe7d54dc59f0b40f919a6df8d8272190b3a/lib/autokey/gtkui/configwindow.py#L1428-L1437

https://github.com/autokey/autokey/blob/fddd8fe7d54dc59f0b40f919a6df8d8272190b3a/lib/autokey/gtkui/configwindow.py#L1439-L1476

**Comment by dovry** [comment]
@luziferius was this resolved with the latest release?

**Comment by luziferius** [comment]
I think this is something different. The latest release fixed AutoKey deleting unknown user files by using an unchecked `shutil.rmtree()` on the folder path on disk.
This issue is present in the GTK GUI only. It somehow loses the reference to some items when doing a mass drag&drop. (D&D is implemented as "delete the source and recreate at the destination".) I haven’t really found out the root cause.

The GUI is set to only accept single item selections. That you are able to select multiple items by using certain key combinations is unintended, I think.
