### ISSUE TITLE
AutoKey Stops Running Macros And Phrases

### ISSUE THREAD

**Issue by josephj11** [autokey/autokey#34]
Sometimes (I don't know how to recreate it), AutoKey stops running macros. It seems like part of it has crashed. The main Window is still accessible and I can quit AutoKey, but nothing seems to fix the problem until I kill (pkill autokey) the remaining AutoKey process and restart it.

At this point I'm just registering the existence of the problem. I don't know how to document it further.

This is autokey 0.09.4.1 (gtk) running under Kubuntu Precise (12.04) with KDE 4.14.2.

**Comment by jpwgarrison** [comment]
Same issue with Ubuntu 14.04, I3 here. I have a cronjob kill and restart it every 10 minutes and this mostly works, unless I happen to try an expansion as the cronjob runs. 20 minutes was too long.

**Comment by josephj11** [comment]
It only happens to me once every few days. Since you see it so much more often, maybe you can gather some clues as to what's happening.

Can you run AutoKey in trace mode and let it happen?

[](https://github.com/autokey/autokey/wiki/Problem-Reporting-Guide)

If you can do that, we can see what it was trying to do when it froze.
Also, does anything appear in the system log? It would be at the end if you catch it right when it happens. Otherwise you'll have to save it to a file so you can search through and then cut and paste anything suspicious into a post here.
`dmesg`

**Comment by bienstock** [comment]
I've encountered the same issue (software stops pasting passwords after some time) and have found the following errors appear in the log file several times:

2017-01-15 11:58:56,002 ERROR - interface - Error in X event loop thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/autokey/interface.py", line 116, in __eventLoop
    method(*args)
  File "/usr/lib/python2.7/dist-packages/autokey/interface.py", line 807, in __handleKeyPress
    focus = self.localDisplay.get_input_focus().focus
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 566, in get_input_focus
    return request.GetInputFocus(display = self.display)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1478, in __init__
    self.reply()
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1490, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 656, in parse_response
    gotreq = self.parse_error_response(request) or gotreq
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 710, in parse_error_response
    self.default_error_handler(e)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 716, in default_error_handler
    sys.stderr.write('X protocol error:\n%s\n' % err)
IOError: [Errno 5] Input/output error

**Comment by josephj11** [comment]
Thanks. It's about time somebody found something concrete on this one!

Unfortunately, we don't have a developer to address problems in the code. (But the autokey-py3 branch does have an active developer.)
