### ISSUE TITLE
Circular import trying to test dialogs

### ISSUE THREAD

**Issue by BlueDrink9** [autokey/autokey#372]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: Develop

Used GUI (Gtk, Qt, or both): both

## Description

If you go to https://github.com/BlueDrink9/autokey/tree/regex and run the tests, you'll see that one test fails because of a circular import. This makes it very difficult to mock and test UI code, because importing it fails.

Can you please take a look and see if it is totally necessary to have that order of imports there?

**Comment by luziferius** [comment]
The GUI code currently is somewhat tightly coupled, which makes it hard do move stuff around and isolate parts.

Your circular imports error is weird.
```
thomas@Thomas-PC:/mnt/Daten/Projekte/autokey$ LC_ALL=C git branch
  bugfix/issue_206
  bugfix/issue_291
  bugfix/issue_332
  bugfix/issue_334
  develop
  feature/add_send_mode_option_to_keyboard_send_keys
  feature/better_script_error_handling
  feature/create_configured_phrases_using_api_calls
  feature/libxdo_interface
  implement_mouse_movement_in_the_scripting_api
  improve_phrase_macro_parsing
  master
  phrase_expansion_timing_issues_test
* regex
thomas@Thomas-PC:/mnt/Daten/Projekte/autokey$ LC_ALL=C git pull
Already up to date.
Current branch regex is up to date.
thomas@Thomas-PC:/mnt/Daten/Projekte/autokey$ LC_ALL=C python3 setup.py test
running pytest
running egg_info
writing lib/autokey.egg-info/PKG-INFO
writing dependency_links to lib/autokey.egg-info/dependency_links.txt
writing entry points to lib/autokey.egg-info/entry_points.txt
writing requirements to lib/autokey.egg-info/requires.txt
writing top-level names to lib/autokey.egg-info/top_level.txt
reading manifest file 'lib/autokey.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lib/autokey.egg-info/SOURCES.txt'
running build_ext
=========================================================================================================== test session starts ============================================================================================================
platform linux -- Python 3.7.5, pytest-4.6.6, py-1.8.0, pluggy-0.12.0
rootdir: /mnt/Daten/Projekte/autokey
collected 312 items                                                                                                                                                                                                                        

tests/test_iomediator.py ......                                                                                                                                                                                                      [  1%]
tests/test_macro.py ...................s.............                                                                                                                                                                                [ 12%]
tests/test_phrase.py ............................................................................................................xxxxxxxxxxxxx                                                                                       [ 51%]
tests/test_phrase_runner.py ........................................................................................                                                                                                                 [ 79%]
tests/UIs/test_baseUIActions.py .                                                                                                                                                                                                    [ 79%]
tests/UIs/test_dialogs_gtk.py s                                                                                                                                                                                                      [ 80%]
tests/UIs/test_dialogs_qt.py F                                                                                                                                                                                                       [ 80%]
tests/scripting_api/test_engine.py ..........................s                                                                                                                                                                       [ 89%]
tests/scripting_api/test_keyboard.py ................................                                                                                                                                                                [ 99%]
tests/scripting_api/test_system.py ..                                                                                                                                                                                                [100%]

================================================================================================================= FAILURES =================================================================================================================
___________________________________________________________________________________________________ test_WindowFilterSettingsDialog_save ___________________________________________________________________________________________________

    def test_WindowFilterSettingsDialog_save():
>       dialog=MagicMock(autokey.qtui.dialogs.windowfiltersettings.WindowFilterSettingsDialog)
E       AttributeError: module 'autokey' has no attribute 'qtui'

tests/UIs/test_dialogs_qt.py:26: AttributeError
======================================================================================= 1 failed, 295 passed, 3 skipped, 13 xfailed in 0.96 seconds ========================================================================================
thomas@Thomas-PC:/mnt/Daten/Projekte/autokey$
```
Sidenote: The tests import some modules in `__init__.py`, which somehow magically resolves some of those circular import issues…
https://github.com/autokey/autokey/blob/9e0560356ed37d791f7cf44584bd155777545d56/tests/__init__.py#L24-L27

**Comment by BlueDrink9** [comment]
Huh. I'll take another look.

**Comment by luziferius** [comment]
`AttributeError: module 'autokey' has no attribute 'qtui'`:
Python does not automatically import stuff recursively. So `autokey.qtui.dialogs` has to be imported explicitly.
https://github.com/BlueDrink9/autokey/blob/4a946cca7b9dccce93384d524c4497426ae1e33f/tests/UIs/test_dialogs_qt.py#L20-L22

**Comment by luziferius** [comment]
I tried this and was able to reproduce it:
```
thomas@Thomas-PC:/mnt/Daten/Projekte/autokey/lib$ ptpython
>>> import autokey.qtui.dialogs                                                                                                                                                                                                             
/mnt/Daten/Projekte/autokey/lib/autokey/qtui/common.py:38: UserWarning: Compiled Qt resources file not found. If autokey is launched directly from the source directory, this is expected and harmless. If not, this indicates a failure in the resource compilation.
  warnings.warn(warn_msg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/Daten/Projekte/autokey/lib/autokey/qtui/dialogs/__init__.py", line 36, in <module>
    from .abbrsettings import AbbrSettingsDialog
  File "/mnt/Daten/Projekte/autokey/lib/autokey/qtui/dialogs/abbrsettings.py", line 27, in <module>
    from autokey import model
  File "/mnt/Daten/Projekte/autokey/lib/autokey/model.py", line 28, in <module>
    from autokey.iomediator.key import Key, NAVIGATION_KEYS
  File "/mnt/Daten/Projekte/autokey/lib/autokey/iomediator/__init__.py", line 20, in <module>
    from ._windowgrabber import WindowGrabber
  File "/mnt/Daten/Projekte/autokey/lib/autokey/iomediator/_windowgrabber.py", line 21, in <module>
    from ._iomediator import IoMediator
  File "/mnt/Daten/Projekte/autokey/lib/autokey/iomediator/_iomediator.py", line 4, in <module>
    from autokey.configmanager.configmanager import ConfigManager
  File "/mnt/Daten/Projekte/autokey/lib/autokey/configmanager/configmanager.py", line 36, in <module>
    import autokey.configmanager.predefined_user_files
  File "/mnt/Daten/Projekte/autokey/lib/autokey/configmanager/predefined_user_files.py", line 26, in <module>
    from autokey.model import Folder, Script, Phrase, TriggerMode
ImportError: cannot import name 'Folder' from 'autokey.model' (/mnt/Daten/Projekte/autokey/lib/autokey/model.py)

cannot import name 'Folder' from 'autokey.model' (/mnt/Daten/Projekte/autokey/lib/autokey/model.py)
```

**Comment by luziferius** [comment]
I think reworking the model class hierarchy should solve this.
- Move `model.py` content into a new `model` package
- Move `autokey.iomediator.key` from `autokey.iomediator` to the to-be-created `autokey.model`

The `Key` class and related don’t belong to the iomediator stuff. It feels more like a model class.
Because it is used by the model, it creates this bi-directional dependency.

**Comment by BlueDrink9** [comment]
I'll try work on that

**Comment by luziferius** [comment]
If you wish. I have some plan in mind for those model classes, because I don’t like the current relationship between them. 
Just moving `Key` should hopefully resolve the circular import.

Below is my wish-list for future refinements:

Currently, the model uses multiple inheritance using three base classes that implement hotkeys, abbreviations and window filters. But those abstract classes depend on each other by using each other’s methods internally. So they aren’t really decoupled. It only works because the concrete classes (`Folder`, `Script`, `Phrase`) do inherit all three. A hypothetical forth concrete class that inherits from one or two base classes only will never work, because the abstract base’s methods will fail with `AttributeError`s.

My plan is to switch the dependencies from inheritance to composition:

- Have concrete classes `Hotkey`, `Abbreviation`, `WindowFilter`
- Have `AbstractItem` (or similarly named) class that holds each a _list_ of `Hotkey`, `Abbreviation`, `WindowFilter` instances [*]
- `AbstractItem` defines some `@abstractmethod` abstract methods that define the interface of concrete implementations
- `Folder`, `Script`, `Phrase` inherit from `AbstractItem`, each implementing the required concrete behaviour.
- If it proves necessary to have a dependency between `Hotkey`, `Abbreviation`, `WindowFilter`, define a clear API. Either couple the classes via a `parent-of`-relationship, or use a callback mechanic and let the parent set the required methods by setting appropriate fields to the respective function objects. (The first one seems to be better, regarding the possibility of having a many-to-many relationship.)

[*] Currently, `AbstractAbbreviation` internally handles multiple abbreviations, whilst the filter and hotkey class each only handle a single filter and hotkey. By switching to lists of instances, AutoKey gains support of multiple hotkeys per item, which is a regularly requested feature and possibly multiple window filters. The exact semantics of multiple window filters has to be defined, though.

**Comment by BlueDrink9** [comment]
I'll probably start out just increasing test coverage, since that will be ideal for any refactoring.
