### ISSUE TITLE
with KDE 5.18 (even 5.18.1) several problems

### ISSUE THREAD

**Issue by DoctorSubtilis** [autokey/autokey#375]
## Version: 0.95.10

Used GUI (Gtk, Qt, or both): both

Installed via: (PPA, pip3, …) .deb files

Linux Distribution: KDE Neon 5.18.1

## Summary

There are _several problems_, but  

1. the most important is that keyboard stops working (often). So you have to **kill** autokey (impossible to close it "gently"). And afterwards usually it works.  
2. Another problem is that, using ctrl+v to avoid a problem with libreoffice, sometimes instead of expand the desired phrase, it expand clipboard content.  
3. Third: with the new release of KDE after a bracket or comma or like, abbreviation doesn't expand. For example "(exp" doesn't expand to "(experience", as in the recent past, but you have to write "( exp".  
Probably I forget something, but three bugs are enough currently.  

Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

**Comment by luziferius** [comment]
1. When the keyboard locks up, does it still work in the AutoKey window? If so, there is a keyboard grab somewhere in the code that still is not released properly. I already fixed several of those issues. I’ll have to look around, if I can find another location.
2. Please see here: This function is used to restore the clipboard. Because the GUI toolkit does not allow us to wait until the clipboard is properly filled, we do some guesswork by waiting 200ms. It seems that this is still insufficient on KDE 5.18. https://github.com/autokey/autokey/blob/c0c2e2939f2352a1d3d83c8edafc9007848d6a1e/lib/autokey/interface.py#L630-L635
If you wish, you can edit `/usr/lib/python3/dist-packages/autokey/interface.py` as root and increase the delay in line 634 to `0.3` or `0.4`. If you do, please report back if it helps. If you don’t want to fiddle with it yourself, this is fine. I’ll then build some patched Debian packages.
3. I’m running 5.18.1 myself, but don’t use punctuation in my abbreviations, so haven’t noticed the issues. I’ll try to reproduce it here.

Edit: I tried this and it works fine in Kate, Konsole, Firefox and LibreOffice:
![375](https://user-images.githubusercontent.com/2143820/75297831-25db6b00-5831-11ea-95fc-408f29d11b46.png)

```
Operating System: Kubuntu 19.10
KDE Plasma Version: 5.18.1
KDE Frameworks Version: 5.67.0
Qt Version: 5.12.4
Kernel Version: 5.5.2-050502-generic
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31,3 GiB
```

**Comment by DoctorSubtilis** [comment]
Thank you. I will try your suggestions.  
But now my PC is being updated to 5.18.2: maybe this new release fix (all? some of?) these problems...  
I will report afterwards the news from my KDE Neon ;)

**Comment by DoctorSubtilis** [comment]
Today, _so far_, a good news with KDE 5.18.2: I didn't notice **1** and **2** (my first and second bug above spoken about).
Sometimes **3**: (almost) always in browsers, only once in LibreWriter (solved by closing the files opened and re-opening them).  
Tomorrow I will try again.

**Comment by DoctorSubtilis** [comment]
Today, once the "2" (when I was writing a post in facebook: 9 times ok, 1 time I got the clipboard content).  
So I changed ad you said in interface.py 0.2 to 0.4.  
I will see.

**Comment by luziferius** [comment]
Thanks for trying this.
The problem here is that AutoKey uses the clipboard management built into the GUI toolkit of the used GUI. And in case of Qt, the toolkit _immediately_ returns success when writing. If you query the clipboard immediately after writing, the new value is returned. But then it takes an arbitrary amount of time for X11 to actually process the new content and make it available to other applications. Therefore we can only guess the time needed. But waiting a whole second or so feels like an eternity, if you look at your desktop waiting for the automation.

**Comment by DoctorSubtilis** [comment]
Today some cases of pasting from clipboard content, in LO, even after changing time.sleep in interface.py 0.2 to 0.4.  
But if I re-try, after a few seconds, the same abbreviation: it worked correctly...

**Comment by DoctorSubtilis** [comment]
Because of many errors today evening I shift from 0.4 to 0.8, the time.sleep value, as above said.

**Comment by luziferius** [comment]
Hmmm. I'm really unsure why it takes this much time to programmatically set the clipboard sometimes.

Maybe the program code handling this is swapped or unloaded from memory, as it seems to only happen at the first use after some time? (rhetorical question)

Anyways, I'll try something: I'll look up a different python library for clipboard manipulation and use that in two ways: First, I'll replace the `sleep()` with a polling loop to measure the maximum time required for the set operation. And later try using the library to set the clipboard. Maybe the current way implemented in AutoKey is not the best and using something else might give better results.

**Comment by DoctorSubtilis** [comment]
I'm look forward your promise. It would be nice. Thank you.

**Comment by luziferius** [comment]
Hmm. A simple busy waiting loop that periodically checks if the content is updated seems to cause deadlocks that trigger timeouts…
```
2020-04-03 14:09:03,676 ERROR - root - callback event failed: <bound method XInterfaceBase._send_string_clipboard of <XRecordInterface(XInterface-thread, started daemon 139837625595648)>> ('clipboard test', <SendMode.CB_CTRL_V: '<ctrl>+v'>)
Traceback (most recent call last):
  File "/mnt/Daten/Projekte/autokey/lib/autokey/qtapp.py", line 375, in customEvent
    callback(*args)
  File "/mnt/Daten/Projekte/autokey/lib/autokey/interface.py", line 626, in _send_string_clipboard
    self.clipboard.text = string
  File "/mnt/Daten/Projekte/autokey/lib/autokey/interface.py", line 140, in text
    clipboard_helpers.wait_for_clipboard(new_content)
  File "/mnt/Daten/Projekte/autokey/lib/autokey/clipboard_helpers.py", line 52, in wait_for_clipboard
  File "/mnt/Daten/Projekte/autokey/lib/autokey/clipboard_helpers.py", line 40, in _wait_for_text
  File "/usr/lib/python3.7/tkinter/__init__.py", line 807, in clipboard_get
    return self.tk.call(('clipboard', 'get') + self._options(kw))
_tkinter.TclError: selection owner didn't respond
```

Seems that I have to use a mutex and a separate polling thread. That might work…
