### ISSUE TITLE
'utf8' codec can't decode byte 0xac in position 0: invalid start byte"

### ISSUE THREAD

**Issue by el3ctron** [autokey/autokey#40]
just oppening autokey, appear this:

"Error starting interface. Keyboard monitoring will be disabled.
Check your system/configuration.

'utf8' codec can't decode byte 0xac in position 0: invalid start byte"

i try to delete my configuration on my home but is not working, it seems that autokey is reading some file that have a byte 0xac in position 0, but i dont know what file is, or how to repair it.

could be great if someone can help me because autokey is my right hand, a very apreciated piece of software.

**Comment by josephj11** [comment]
Sorry for the late reply. I monitor our listserv/group
https://groups.google.com/forum/#!forum/autokey-users
closely, but get here less frequently.

We need a better problem report to know how to proceed. A trace wouldn't hurt either.

Everyone needs to keep in mind that each computer and setup is somewhat unique. We really need to know about yours where the problem occurred. Also, since it worked "before" for you, what changed?

See:
https://github.com/autokey/autokey/wiki/Problem-Reporting-Guide

Initial comments:
1) Since it appears to be character set related, please also provide your locale settings. Run

locale

in a terminal and post the results here. 

2) What happens if you terminate AutoKey and then run the following from a terminal:

LC_ALL=C  LC_CTYPE=C autokey-gtk

or

LC_ALL=C  LC_CTYPE=C autokey-qt

depending on which front end you have installed?

Character sets and collating sequences are still a rough patch in Linux. There are even bugs in some of the character sets themselves.

Joe

**Comment by palloy** [comment]
Same error message using Lubuntu 14.04, and autokey-gtk 0.90.4 . 
It appears to happen after failure to connect to dbus, due to a dbus problem - there is no listening socket /tmp/dbus-* .  The result is a warning, but autokey continues and tries to parse a null string, hence the non-UTF-8 character.

```
$ autokey-gtk -l

** (autokey-gtk:7515): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-8CRvv4ZlgA: Connection refused
2016-03-20 08:50:21,599 INFO - root - Initialising application
2016-03-20 08:50:21,614 INFO - root - Initialise global hotkeys
2016-03-20 08:50:21,615 INFO - config-manager - Loading config from existing file: /home/dk/.config/autokey/autokey.json
2016-03-20 08:50:21,616 DEBUG - config-manager - Loading folder at '/home/dk/.config/autokey/data/My Phrases'
2016-03-20 08:50:21,620 DEBUG - config-manager - Loading folder at '/home/dk/.config/autokey/data/Sample Scripts'
2016-03-20 08:50:21,622 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2016-03-20 08:50:21,623 DEBUG - inotify - Adding watch for /home/dk/.config/autokey/data/My Phrases
2016-03-20 08:50:21,623 DEBUG - inotify - Adding watch for /home/dk/.config/autokey/data/My Phrases/Addresses
2016-03-20 08:50:21,624 DEBUG - inotify - Adding watch for /home/dk/.config/autokey/data/Sample Scripts
2016-03-20 08:50:21,624 INFO - config-manager - Successfully loaded configuration
2016-03-20 08:50:21,624 DEBUG - inotify - Adding watch for /home/dk/.config/autokey/data
2016-03-20 08:50:21,625 DEBUG - inotify - Adding watch for /home/dk/.config/autokey
2016-03-20 08:50:21,625 DEBUG - config-manager - Global settings: {'showTrayIcon': True, 'sortByUsageCount': True, 'scriptGlobals': {}, 'undoUsingBackspace': True, 'notificationIcon': u'autokey-status', 'enableQT4Workaround': False, 'promptToSave': False, 'menuTakesFocus': False, 'interfaceType': u'XRecord', 'windowDefaultSize': [600, 400], 'showToolbar': True, 'serviceRunning': True, 'columnWidths': [150, 50, 100], 'workAroundApps': u'.*VirtualBox.*|krdc.Krdc', 'hPanePosition': 150, 'isFirstRun': True}
2016-03-20 08:50:21,626 INFO - service - Starting service
2016-03-20 08:50:21,668 ERROR - root - Error starting interface: 'utf8' codec can't decode byte 0xc0 in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/autokey/gtkapp.py", line 131, in initialise
    self.service.start()
  File "/usr/lib/python2.7/dist-packages/autokey/service.py", line 78, in start
    self.mediator = IoMediator(self)
  File "/usr/lib/python2.7/dist-packages/autokey/iomediator.py", line 142, in __init__
    self.interface = XRecordInterface(self, service.app)
  File "/usr/lib/python2.7/dist-packages/autokey/interface.py", line 88, in __init__
    self.__initMappings()
  File "/usr/lib/python2.7/dist-packages/autokey/interface.py", line 140, in __initMappings
    self.localDisplay = display.Display()
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/connect.py", line 93, in get_auth
    return getattr(mod, modname).get_auth(sock, dname, host, dno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/unix_connect.py", line 116, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/lib/python2.7/dist-packages/Xlib/xauth.py", line 84, in __init__
    self.entries.append((family, addr.decode('UTF-8'),
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 0: invalid start byte
2016-03-20 08:50:28,722 INFO - root - Entering main()
```

**Comment by tkossak** [comment]
I have the same problem.
My os:
```
System:    Kernel: 3.19.0-32-generic x86_64 (64 bit gcc: 4.8.2) Desktop: Cinnamon 2.8.8 (Gtk 2.24.23) dm: mdm
           Distro: Linux Mint 17.3 Rosa
```
Autokey was installed from package repository (ver 0.90.4-1). When i run `autohotkey-gtk -l` i get:
```
2016-05-20 16:58:20,771 INFO - root - Initialising application
2016-05-20 16:58:20,778 INFO - root - Initialise global hotkeys
2016-05-20 16:58:20,778 INFO - config-manager - Loading config from existing file: /home/kossak/.config/autokey/autokey.json
2016-05-20 16:58:20,805 DEBUG - config-manager - Loading folder at '/home/kossak/.config/autokey/data/Sample Scripts'
2016-05-20 16:58:20,825 DEBUG - config-manager - Loading folder at '/home/kossak/.config/autokey/data/My Phrases'
2016-05-20 16:58:20,828 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2016-05-20 16:58:20,828 DEBUG - inotify - Adding watch for /home/kossak/.config/autokey/data/Sample Scripts
2016-05-20 16:58:20,828 DEBUG - inotify - Adding watch for /home/kossak/.config/autokey/data/My Phrases
2016-05-20 16:58:20,828 DEBUG - inotify - Adding watch for /home/kossak/.config/autokey/data/My Phrases/Addresses
2016-05-20 16:58:20,828 INFO - config-manager - Successfully loaded configuration
2016-05-20 16:58:20,829 DEBUG - inotify - Adding watch for /home/kossak/.config/autokey/data
2016-05-20 16:58:20,829 DEBUG - inotify - Adding watch for /home/kossak/.config/autokey
2016-05-20 16:58:20,829 DEBUG - config-manager - Global settings: {'showTrayIcon': True, 'sortByUsageCount': True, 'scriptGlobals': {}, 'undoUsingBackspace': True, 'notificationIcon': u'autokey-status', 'enableQT4Workaround': False, 'promptToSave': False, 'menuTakesFocus': False, 'interfaceType': u'XRecord', 'windowDefaultSize': [600, 400], 'showToolbar': True, 'serviceRunning': True, 'columnWidths': [150, 50, 100], 'workAroundApps': u'.*VirtualBox.*|krdc.Krdc', 'hPanePosition': 150, 'isFirstRun': True}
2016-05-20 16:58:20,829 INFO - service - Starting service
2016-05-20 16:58:20,865 ERROR - root - Error starting interface: 'utf8' codec can't decode byte 0xc0 in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/autokey/gtkapp.py", line 131, in initialise
    self.service.start()
  File "/usr/lib/python2.7/dist-packages/autokey/service.py", line 78, in start
    self.mediator = IoMediator(self)
  File "/usr/lib/python2.7/dist-packages/autokey/iomediator.py", line 142, in __init__
    self.interface = XRecordInterface(self, service.app)
  File "/usr/lib/python2.7/dist-packages/autokey/interface.py", line 88, in __init__
    self.__initMappings()
  File "/usr/lib/python2.7/dist-packages/autokey/interface.py", line 140, in __initMappings
    self.localDisplay = display.Display()
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/connect.py", line 93, in get_auth
    return getattr(mod, modname).get_auth(sock, dname, host, dno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/unix_connect.py", line 116, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/lib/python2.7/dist-packages/Xlib/xauth.py", line 84, in __init__
    self.entries.append((family, addr.decode('UTF-8'),
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 0: invalid start byte
2016-05-20 16:58:23,489 INFO - root - Entering main()
```

**Comment by josephj11** [comment]
Don't have an answer for this one (or the resources to find one). 

I would suggest (as I did to palloy on our support list) contacting the dbus folks to see if they can shed any light on the issue.

dbus users/developers ( dbus@lists.freedesktop.org <http://lists.freedesktop.org/mailman/listinfo/dbus/>) 

Until we have an active development team, there's not much we can do for a very technical issue like this.

**Comment by palloy** [comment]
dbus couldn't help either - they said everything was apparently OK their 
end.

I'm using xbindkeys instead now.

**Comment by josephj11** [comment]
Sorry to hear that, but good to know. Maybe the other branch of AutoKey will work better. (See the edit to my last post). At least they have an active developer.

**Comment by tkossak** [comment]
I just installed [AutoKey-Py3](https://github.com/guoci/autokey-py3) and I can confirm that it doesn't have this problem.
