### ISSUE TITLE
Crash using Gdk

### ISSUE THREAD

**Issue by ayouknowwho** [autokey/autokey#411]
## Classification:

Crash

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): GTK

If the problem is known to be present in more than one version, please list all of those.

Installed via: AUR

Linux Distribution: Arch

## Summary

I have several scripts that run without issues in Autokey. I'm creating a new script to interact with some existing scripts, but importing Gdk to a script seems to make it crash after calling the script between 1 and 10 times.
## Steps to Reproduce (if applicable)

- run autokey-gtk --verbose from command line to view crash information
- run script (a simplified script for testing):

```
#!/usr/bin/python3
#Print RGB color values of screen pixel at location x, y
from gi.repository import Gdk

#defines grabbing pixel colour at location, tested working
def PixelAt(x, y):
  w = Gdk.get_default_root_window()
  pb = Gdk.pixbuf_get_from_window(w, x, y, 1, 1)
  return pb.get_pixels()

keyboard.send_keys(str(tuple(PixelAt(1,1))))
```

## Expected Results

- keyboard types the RGB values as many times as the shortcut is pressed

## Actual Results

- Instead, the script works between 1 and 10 times and then crashes providing the following message
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Fatal Python error: Aborted

Thread 0x00007fa854eb8700 (most recent call first):
  File "/usr/lib/python3.8/site-packages/pyinotify.py", line 1194 in check_events
  File "/usr/lib/python3.8/site-packages/autokey/monitor.py", line 125 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fa855eba700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302 in wait
  File "/usr/lib/python3.8/queue.py", line 170 in get
  File "/usr/lib/python3.8/site-packages/autokey/iomediator/_iomediator.py", line 103 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fa8566bb700 (most recent call first):
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/display.py", line 561 in send_and_recv
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1381 in reply
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1369 in __init__
  File "/usr/lib/python3.8/site-packages/Xlib/ext/record.py", line 220 in __init__
  File "/usr/lib/python3.8/site-packages/Xlib/ext/record.py", line 239 in enable_context
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1206 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fa856ebc700 (most recent call first):
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 906 in __flushEvents
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fa8576bd700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302 in wait
  File "/usr/lib/python3.8/queue.py", line 170 in get
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 235 in __eventLoop
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007fa85fd2f740 (most recent call first):
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1632 in main
  File "/usr/lib/python3.8/site-packages/autokey/gtkapp.py", line 273 in main
  File "/usr/lib/python3.8/site-packages/autokey/gtkui/__main__.py", line 9 in main
  File "/usr/bin/autokey-gtk", line 11 in <module>
Aborted (core dumped)
```
if the script is changed to 
```
#!/usr/bin/python3
# Print RGB color values of screen pixel at location x, y
from gi.repository import Gdk,GObject
import threading

GObject.threads_init()

#defines grabbing pixel colour at location, tested working
def PixelAt(x, y):
  w = Gdk.get_default_root_window()
  pb = Gdk.pixbuf_get_from_window(w, x, y, 1, 1)
  return pb.get_pixels()

keyboard.send_keys(str(tuple(PixelAt(1,1))))
```
the error message on the terminal is now
```
(autokey-gtk:5617): Gdk-CRITICAL **: 10:47:49.117: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
2020-04-29 10:47:49,943 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/usr/lib/python3.8/site-packages/Xlib/xobject/drawable.py", line 455, in get_property
    r = request.GetProperty(display = self.display,
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04800003), sequence_number = 1561, major_opcode = 20, minor_opcode = 0
2020-04-29 10:47:52,962 INFO - root - Displaying configuration window
2020-04-29 10:47:57,683 DEBUG - iomediator - Key.ALT pressed
2020-04-29 10:47:57,898 DEBUG - service - Raw key: '4', modifiers: [<Key.ALT: '<alt>'>], Key: 4
2020-04-29 10:47:57,898 DEBUG - service - Window visible title: '*Untitled 1 - Mousepad', Window class: 'mousepad.Mousepad'
2020-04-29 10:47:57,899 INFO - service - Matched Script "PixelDetect" with hotkey and prompt=False
2020-04-29 10:47:57,899 DEBUG - service - Script runner executing: Script('PixelDetect')
2020-04-29 10:47:57,899 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
2020-04-29 10:47:58,054 DEBUG - iomediator - Key.ALT released
2020-04-29 10:47:58,410 DEBUG - iomediator - Send via event interface
2020-04-29 10:47:58,412 DEBUG - interface - Sending string: '(143, 151, 158)'
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Fatal Python error: Aborted

Thread 0x00007f3f59ffb700 (most recent call first):
  File "/usr/lib/python3.8/site-packages/pyinotify.py", line 1194 in check_events
  File "/usr/lib/python3.8/site-packages/autokey/monitor.py", line 125 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f3f5affd700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302 in wait
  File "/usr/lib/python3.8/queue.py", line 170 in get
  File "/usr/lib/python3.8/site-packages/autokey/iomediator/_iomediator.py", line 103 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f3f5b7fe700 (most recent call first):
  File "/usr/2020-04-29 10:47:58,697 DEBUG - iomediator - Key.ALT pressed
lib/python3.8/site-packages/Xlib/protocol/display.py", line 561 in send_and_recv
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1381 in reply
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1369 in __init__
  File "/usr/lib/python3.8/site-packages/Xlib/ext/record.py", line 220 in __init__
  File "/usr/lib/python3.8/site-packages/Xlib/ext/record.py", line 239 in enable_context
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1206 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f3f5bfff700 (most recent call first):
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 906 in __flushEvents
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f3f68de4700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302 in wait
  File "/usr/lib/python3.8/queue.py", line 170 in get
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 235 in __eventLoop
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f3f6d3c5740 (most recent call first):
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1632 in main
  File "/usr/lib/python3.8/site-packages/autokey/gtkapp.py", line 273 in main
  File "/usr/lib/python3.8/site-packages/autokey/gtkui/__main__.py", line 9 in main
  File "/usr/bin/autokey-gtk", line 11 in <module>
Aborted (core dumped)
```
Sometimes the crash is silent and the message
```
Gdk-Message: 10:46:49.329: autokey-gtk: Fatal IO error 0 (Success) on X server :0.0.
```
appears instead.

**Comment by josephj11** [comment]
@ayouknowwho It would be good to retest this using AutoKey 0.96.0 and a newer version of Python - like 3.11 (we don't support 3.12 yet).

AFAIK, there's nothing in 0.96.0 that would address this, but maybe the newer version of Python or updates to GTK will help.

Also it would be interesting to see if this works in autokey-qt - to know if it has anything to do with our GTK front end code. I know that Arch makes installing the Qt version a bit of trouble if you want to use the GTK version the rest of the time.

You might want to try testing it using the [zero install method](https://github.com/autokey/autokey/wiki/Installing#zero-installation-method), but you'll still have to deal with the additional dependencies it requires if they're not already installed on your system. The section right after that one covers dependencies.

**Comment by ayouknowwho** [comment]
I am long past solving the problem I was working on, and am now using a different computer, different OS, etc. If you can't reproduce the bug with an up to date set up I wouldn't worry about it.
