### ISSUE TITLE
ImportError: cannot import name 'WatchManager' from 'pyinotify'

### ISSUE THREAD

**Issue by FabioNevesRezende** [autokey/autokey#415]
## Classification:

Crash

## Reproducibility:

Always

## Version

AutoKey version:  0.95.10-1

Used GUI (Gtk, Qt, or both):  autokey-qt

Installed via: (PPA, pip3, …). Arch linux user repository (aur, http://aur.archlinux.org/packages/autokey)

Linux Distribution: Artix Linux

## Summary

I can't start the program because it crashes with this error

## Steps to Reproduce (if applicable)

- just open terminal and run `autokey-qt`

## Expected Results

- Program to open

## Actual Results

- crash

Stack trace:

> $ autokey-qt 
> Traceback (most recent call last):
>   File "/usr/bin/autokey-qt", line 11, in <module>
>     load_entry_point('autokey==0.95.10', 'console_scripts', 'autokey-qt')()
>   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
>     return self.resolve()
>   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/lib/python3.8/site-packages/autokey/qtui/__main__.py", line 23, in <module>
>     from autokey.qtapp import Application
>   File "/usr/lib/python3.8/site-packages/autokey/qtapp.py", line 37, in <module>
>     from autokey import service, monitor
>   File "/usr/lib/python3.8/site-packages/autokey/monitor.py", line 24, in <module>
>     from pyinotify import WatchManager, Notifier, EventsCodes, ProcessEvent
> ImportError: cannot import name 'WatchManager' from 'pyinotify' (/usr/lib/python3.8/site-packages/pyinotify.py)
>

**Comment by josephj11** [comment]
Did you check if there's a "WatchManager" module/function installed on your system?
I don't know Arch, but I've seen previous reports where supporting modules either weren't installed or they were, but when Arch "compiled" them to .pyc format they were at a lower version number than needed. This was fixed by reinstalling them to get the newer version.

Just looked again: Python 3.8 is bleeding edge (as usual for Arch), so the pynotify.py version might also be too new for us. One of our developers will be able to give you a better answer.

**Comment by luziferius** [comment]
Ubuntu 20.04 also ships Python 3.8.2 and it works here.

Try opening a Python 3 prompt and execute
```python
from pyinotify import WatchManager, Notifier, EventsCodes, ProcessEvent
```
If that fails on a standalone Python prompt, it is an installation issue in one of AutoKey’s dependencies.
