### ISSUE TITLE
Dead keys trigger phrases

### ISSUE THREAD

**Issue by precondition** [autokey/autokey#437]
## Version

AutoKey version: 0.95.10

Used GUI: GTK

Installed via: .deb packages from the GitHub releases

Linux Distribution: (X)Ubuntu

## Summary

Dead keys trigger phrases. This happens regardless of the "Trigger on" options ­which, by the way, do not seem to work at all for me. Even if I define the phrase to trigger on Tab, it triggers on any non-basic or non-alphanumeric character/key, it's not really the subject of this issue but it's most likely correlated. It also happens with all the paste methods, though you can see some "left overs" or something of the dead key when using the clipboard.

Let's take my "rer" → "remember" phrase. With keyboard paste, if I want to type "reré" using dead keys, I get "rememberé". If, instead, I use any of the Clipboard ways to paste, I get "remember﹑e".

## Steps to Reproduce (if applicable)

- Use a xkb layout with dead keys (such as the Belgian one or the US Intl, with or without AltGr dead keys)
- Define a phrase 
- Type the abbreviation up until its last character
- Activate a dead key

## Expected Results

- \<abbreviation\>\<accented letter\>
    - e.g. "reré"

## Actual Results

- \<text expansion phrase\>\<accented letter\>
    - e.g. "remember﹑e" with Clipboard
    - e.g.  "rememberé" with Keyboard

```
2020-08-10 22:22:09,187 INFO - root - Initialising application
2020-08-10 22:22:09,192 INFO - root - Initialise global hotkeys
2020-08-10 22:22:09,192 INFO - config-manager - Loading config from existing file: /home/vern/.config/autokey/autokey.json
2020-08-10 22:22:09,192 INFO - config-manager - Disabling modifier key <capslock> based on the stored configuration file.
2020-08-10 22:22:09,193 DEBUG - config-manager - Loading folder at '/home/vern/.config/autokey/data/Sample Scripts'
2020-08-10 22:22:09,194 DEBUG - config-manager - Loading folder at '/home/vern/.config/autokey/data/Abbreviations'
2020-08-10 22:22:09,202 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2020-08-10 22:22:09,202 DEBUG - inotify - Adding watch for /home/vern/.config/autokey/data/Sample Scripts
2020-08-10 22:22:09,202 DEBUG - inotify - Adding watch for /home/vern/.config/autokey/data/Abbreviations
2020-08-10 22:22:09,202 DEBUG - inotify - Adding watch for /home/vern/.config/autokey/data/Abbreviations/Français
2020-08-10 22:22:09,202 DEBUG - inotify - Adding watch for /home/vern/.config/autokey/data/Abbreviations/English
2020-08-10 22:22:09,203 INFO - config-manager - Successfully loaded configuration
2020-08-10 22:22:09,203 DEBUG - inotify - Adding watch for /home/vern/.config/autokey/data
2020-08-10 22:22:09,203 DEBUG - inotify - Adding watch for /home/vern/.config/autokey
2020-08-10 22:22:09,203 DEBUG - config-manager - Global settings: {'isFirstRun': True, 'serviceRunning': True, 'menuTakesFocus': False, 'showTrayIcon': True, 'sortByUsageCount': True, 'promptToSave': False, 'enableQT4Workaround': False, 'interfaceType': 'XRecord', 'undoUsingBackspace': True, 'windowDefaultSize': [798, 874], 'hPanePosition': 253, 'columnWidths': [150, 50, 100], 'showToolbar': True, 'notificationIcon': 'autokey-status-dark', 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'triggerItemByInitial': False, 'disabledModifiers': [<Key.CAPSLOCK: '<capslock>'>], 'scriptGlobals': {}}
2020-08-10 22:22:09,203 INFO - service - Starting service
2020-08-10 22:22:09,228 DEBUG - interface - Enabling sending using Alt-Grid
2020-08-10 22:22:09,228 DEBUG - interface - Modifier masks: {<Key.SHIFT: '<shift>'>: 1, <Key.CONTROL: '<ctrl>'>: 4, <Key.ALT: '<alt>'>: 8, <Key.ALT_GR: '<alt_gr>'>: 128, <Key.SUPER: '<super>'>: 64, <Key.HYPER: '<hyper>'>: 64, <Key.META: '<meta>'>: 8, <Key.NUMLOCK: '<numlock>'>: 16}
2020-08-10 22:22:09,229 DEBUG - interface - Alt-Grid: XK_ISO_Level3_Shift, 65027
2020-08-10 22:22:09,229 DEBUG - interface - X Server Keymap, listing unmapped keys.
2020-08-10 22:22:09,229 DEBUG - iomediator - Set modifier Key.CAPSLOCK to False
2020-08-10 22:22:09,229 DEBUG - iomediator - Set modifier Key.NUMLOCK to True
2020-08-10 22:22:09,230 DEBUG - interface - __flushEvents: Entering event loop.
2020-08-10 22:22:09,230 INFO - iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2020-08-10 22:22:09,237 INFO - interface - XRecord interface thread starting
2020-08-10 22:22:09,238 INFO - service - Service now marked as running
2020-08-10 22:22:09,290 DEBUG - phrase-menu - Sorting phrase menu by usage count
2020-08-10 22:22:09,290 DEBUG - phrase-menu - Triggering menu item by position in list
2020-08-10 22:22:09,294 DEBUG - root - Created DBus service
2020-08-10 22:22:09,294 INFO - root - Entering main()
2020-08-10 22:22:13,333 DEBUG - service - Raw key: 'r', modifiers: [], Key: r
2020-08-10 22:22:13,333 DEBUG - service - Window visible title: 'Whisker Menu', Window class: 'wrapper-2.0.Wrapper-2.0'
2020-08-10 22:22:13,334 DEBUG - service - Input queue at end of handle_keypress: deque(['r'], maxlen=150)
2020-08-10 22:22:13,437 DEBUG - service - Raw key: 'e', modifiers: [], Key: e
2020-08-10 22:22:13,437 DEBUG - service - Window visible title: 'Whisker Menu', Window class: 'wrapper-2.0.Wrapper-2.0'
2020-08-10 22:22:13,438 DEBUG - service - Input queue at end of handle_keypress: deque(['r', 'e'], maxlen=150)
2020-08-10 22:22:13,519 DEBUG - service - Raw key: 'r', modifiers: [], Key: r
2020-08-10 22:22:13,519 DEBUG - service - Window visible title: 'Whisker Menu', Window class: 'wrapper-2.0.Wrapper-2.0'
2020-08-10 22:22:13,520 DEBUG - service - Input queue at end of handle_keypress: deque(['r', 'e', 'r'], maxlen=150)
2020-08-10 22:22:14,700 DEBUG - iomediator - Key.ALT_GR pressed
2020-08-10 22:22:14,708 DEBUG - service - Raw key: "'", modifiers: [], Key: ﹑
2020-08-10 22:22:14,709 DEBUG - service - Window visible title: 'Whisker Menu', Window class: 'wrapper-2.0.Wrapper-2.0'
2020-08-10 22:22:14,709 INFO - service - Matched Phrase "rer" having abbreviations "['rer']" against current input
2020-08-10 22:22:14,709 DEBUG - iomediator - Send via event interface
2020-08-10 22:22:14,709 DEBUG - service - Input queue at end of handle_keypress: deque([], maxlen=150)
2020-08-10 22:22:14,710 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
2020-08-10 22:22:14,710 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2020-08-10 22:22:14,711 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2020-08-10 22:22:14,712 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2020-08-10 22:22:14,713 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2020-08-10 22:22:14,714 DEBUG - interface - Sending string: 'remember﹑'
2020-08-10 22:22:14,722 DEBUG - iomediator - Key.ALT_GR released
2020-08-10 22:22:15,447 DEBUG - service - Raw key: 'e', modifiers: [], Key: e
2020-08-10 22:22:15,447 DEBUG - service - Window visible title: 'Whisker Menu', Window class: 'wrapper-2.0.Wrapper-2.0'
2020-08-10 22:22:15,448 DEBUG - service - Input queue at end of handle_keypress: deque(['e'], maxlen=150)
```

## Notes

I've tried re-installing multiple times and starting off a blank slate but it happens every time.
I've briefly tried to see if anybody submitted an issue concerning this python error:
```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
```
but I didn't find anything, maybe I didn't look hard enough? I'm not sure whether it's even linked to the issue at hand or not.

**Comment by precondition** [comment]
This issue still happens on version 0.96.0

**Comment by precondition** [comment]
I think I understand it better now. Now, it only happens sporadically; there is a timing problem. My keyboard firmware sends macros involving modifier+key at superhuman speeds and AutoKey seemingly struggles to keep up.

When I press my macro key for è that works by sending <kbd>AltGr</kbd>+<kbd>\`</kbd>, quickly followed by <kbd>E</kbd>, AutoKey either catches on to the fact that <kbd>`</kbd> is chorded with <kbd>AltGr</kbd> or misses that fact.

Correctly catching the keyboard shortcut:
```
2022-07-25 15:15:39,606 DEBUG - autokey.iomediator.iomediator - Key.ALT_GR pressed
2022-07-25 15:15:39,609 DEBUG - autokey.iomediator.iomediator - Key.ALT_GR released
2022-07-25 15:15:39,609 DEBUG - autokey.service - Raw key: '`', modifiers: [<Key.ALT_GR: '<alt_gr>'>], Key: ﹐
2022-07-25 15:15:39,611 DEBUG - autokey.service - Raw key: 'e', modifiers: [], Key: e
```
Failure to catch the keyboard shortcut:
```
2022-07-25 15:16:18,227 DEBUG - autokey.iomediator.iomediator - Key.ALT_GR pressed
è2022-07-25 15:16:18,229 DEBUG - autokey.iomediator.iomediator - Key.ALT_GR released
2022-07-25 15:16:18,229 DEBUG - autokey.service - Raw key: '`', modifiers: [], Key: `
2022-07-25 15:16:18,232 DEBUG - autokey.service - Raw key: 'e', modifiers: [], Key: e
```

I suspect this is also why my "match-case" phrases sometimes fail to capitalise when I use QMK's One-Shot shift key.

**Comment by josephj11** [comment]
We don't have a lot of experience with smart keyboards (or mice) and issues like this are challenging to recreate since we don't have your hardware.

In general, AutoKey doesn't play well with things like remapped keyboards and  this is a bit like that.

One thing I would look at is typing your hotkey while `xev` is running to see if your hardware is actually releasing the modifier key before sending the main key. If it is, then AutoKey isn't currently designed to detect that as a hotkey.

There was some work done on implementing "chorded" hotkeys and I think it was working in tests, but it was never added to our development branch. (I think we still have the code, but I would have to research it.)

The release unlocked key exception used to happen all the time and was purely an annoyance with no consequences. It was finally fixed in 0.96.0.

**Comment by precondition** [comment]
`xev` output of macro key
```
KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5516034, (98,93), root:(809,466),
    state 0x10, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5516036, (98,93), root:(809,466),
    state 0x90, keycode 49 (keysym 0xfe50, dead_grave), same_screen YES,
    XLookupString gives 1 bytes: (60) "`"
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: True

KeyRelease event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5516040, (98,93), root:(809,466),
    state 0x90, keycode 49 (keysym 0xfe50, dead_grave), same_screen YES,
    XLookupString gives 1 bytes: (60) "`"
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5516041, (98,93), root:(809,466),
    state 0x90, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5516042, (98,93), root:(809,466),
    state 0x10, keycode 26 (keysym 0x65, e), same_screen YES,
    XLookupString gives 1 bytes: (65) "e"
    XmbLookupString gives 1 bytes: (65) "e"
    XFilterEvent returns: True

KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5516042, (98,93), root:(809,466),
    state 0x10, keycode 0 (keysym 0xe8, egrave), same_screen YES,
    XKeysymToKeycode returns keycode: 16
    XLookupString gives 0 bytes: 
    XmbLookupString gives 2 bytes: (c3 a8) "è"
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5516047, (98,93), root:(809,466),
    state 0x10, keycode 26 (keysym 0x65, e), same_screen YES,
    XLookupString gives 1 bytes: (65) "e"
    XFilterEvent returns: False
```

`xev` output of the same sequence but done manually:
```
KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5631899, (118,137), root:(204,443),
    state 0x10, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5632107, (118,137), root:(204,443),
    state 0x90, keycode 49 (keysym 0xfe50, dead_grave), same_screen YES,
    XLookupString gives 1 bytes: (60) "`"
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: True

KeyRelease event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5632230, (118,137), root:(204,443),
    state 0x90, keycode 49 (keysym 0xfe50, dead_grave), same_screen YES,
    XLookupString gives 1 bytes: (60) "`"
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5632337, (118,137), root:(204,443),
    state 0x90, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5633984, (118,137), root:(204,443),
    state 0x10, keycode 26 (keysym 0x65, e), same_screen YES,
    XLookupString gives 1 bytes: (65) "e"
    XmbLookupString gives 1 bytes: (65) "e"
    XFilterEvent returns: True

KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5633984, (118,137), root:(204,443),
    state 0x10, keycode 0 (keysym 0xe8, egrave), same_screen YES,
    XKeysymToKeycode returns keycode: 16
    XLookupString gives 0 bytes: 
    XmbLookupString gives 2 bytes: (c3 a8) "è"
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x5000001,
    root 0x55b, subw 0x0, time 5633991, (118,137), root:(204,443),
    state 0x10, keycode 26 (keysym 0x65, e), same_screen YES,
    XLookupString gives 1 bytes: (65) "e"
    XFilterEvent returns: False
```

The sequence of key events is just what you'd expect.

I understand that debugging timing-related issues is rather hard, especially so if it requires special hardware. I have already set up an AutoKey dev env — to remove the enter key from the list of phrase trigger keys — so I can try to look into it if I feel a strong need to procrastinate on my other tasks.

**Comment by josephj11** [comment]
That output will help the developers.

I have no idea what's going on here, but it "feels" like a shortcoming/limitation/bug in the libraries we use for our keyboard interface.

_If_ that's the case, it suggests a few things.

- It's probably an  upstream problem in code we have no experience with
- If some common facility is failing, then the problem should also manifest in other software projects which use that facility
- Other people using your device or another similar one should be experiencing similar issues

So, until our developers get a chance to look at this (which might be a while because we have < 1 at the moment), you could look in support forums for your device. You could also look for issues with the libraries we use. (I will stare at the code later and see if I can adequately identify which those are. I'm not one of the developers.)

One thing I'm a bit unclear on is the scope of the issue. Does this occur for everything you do using this device or is it limited to some subset? Does it have anything to do with this "dead key" thing that I don't understand at all?

**Comment by Elliria** [comment]
Do you have "Trigger when typed as part of a word" enabled in the abbreviation settings?

**Comment by precondition** [comment]
> Does this occur for everything you do using this device or is it limited to some subset?

Not quite sure I understand your question. Other programs do not have any problems with my macro keys if that's what you're asking.

> Does it have anything to do with this "dead key" thing that I don't understand at all?

A dead key is a key you press to modify the symbol of the next key press you execute. You can have an « diaeresis dead key » (¨) which upon initial key press doesn't show/output anything, then followed by any letter like A and that next letter will see the accent of the dead key applied to it, e.g. ä. If the combination of the accent and the key is « illegal » then you'll just get the accent alone followed by the unmodified letter, e.g. ¨ followed by q = ¨q because ümlaut Q does not exist.

Consequently, as you can see, the dead key is a special symbol so AHK thinks it can try to expand what's been typed up to that point. Not realising that this symbol hasn't actually even materialised yet, in a sense, and will be used to produce a letter instead, albeit an accented one but a letter nonetheless.

That's a standard feature of (nearly?) all national keyboard layouts with support for languages including accented letters.

> Do you have "Trigger when typed as part of a word" enabled in the abbreviation settings?

No, I do not.

**Comment by josephj11** [comment]
@precondition I don't think AutoKey understands things like dead keys. In any case, it's quite likely that whatever is going wrong is occurring in the interface modules that we import from Python, but IDK that for sure.

We are currently testing a new interface library that is (mostly) compatible with Wayland. Maybe that will work differently (hopefully, better) for you, but it's not really ready for end user testing yet. If you want to live dangerously and  try it, come over to [Gitter](https://gitter.im/autokey/autokey) and we can help you setup for testing it.

**Comment by Elliria** [comment]
Interesting. [This Wikipedia article](https://en.wikipedia.org/wiki/Dead_key) points out that the difference between a dead key and a standard modifier (like **Ctrl** or **Alt**) is that unlike the standard modifiers, the dead key isn't held down while the next key is pressed. The **﹑** key that you're pressing that triggers your phrases isn't a standard key, but AutoKey seems to be treating it as a non-word character.

Have you tried changing the "**Trigger on:** setting from **All non-word** to **Space and Enter** or **Tab**?

If neither of those will work and you'd rather use a custom trigger, you might find [this discussion](https://github.com/autokey/autokey/issues/843) interesting. Hopefully you'll be able to fine-tune it so that only the abbreviations and triggers you specify will be used.

**Comment by josephj11** [comment]
In the past, someone added a feature to support chorded hotkeys and AutoKey sort of supports this with the is_recursive parameter, but the code was never merged into development and may be lost. Not sure it would help here anyway.

**Comment by josephj11** [comment]
@Elliria I think  you're on to something with the non-word character thing. AutoKey generally seems to get scan codes from the keyboard and responds to them ignoring any superimposed magic like secondary layouts or remapped keys and it sounds like dead keys is a similar issue.

IDK how things work at that low level.

**Comment by Elliria** [comment]
Luckily, nothing is ever lost with git, so it's there somewhere. It would have to be looked at by someone who could understand it, though. Your mention of key-mapping might also be useful for solving this if the triggers don't do it.

**Comment by precondition** [comment]
> Interesting. [This Wikipedia article](https://en.wikipedia.org/wiki/Dead_key) points out that the difference between a dead key and a standard modifier (like **Ctrl** or **Alt**) is that unlike the standard modifiers, the dead key isn't held down while the next key is pressed. The **﹑** key that you're pressing that triggers your phrases isn't a standard key, but AutoKey seems to be treating it as a non-word character.
> 
> Have you tried changing the "**Trigger on:** setting from **All non-word** to **Space and Enter** or **Tab**?
> 
> If neither of those will work and you'd rather use a custom trigger, you might find [this discussion](https://github.com/autokey/autokey/issues/843) interesting. Hopefully you'll be able to fine-tune it so that only the abbreviations and triggers you specify will be used.

The problem with a custom trigger is that AutoKey cannot distinguish between, say, a simple/raw grave <code>`</code> and a dead grave. I could omit the grave from the trigger list, which would indeed prevent expansions when followed by a grave-accented letter like è but I still want my abbreviations to expand if I follow them by a raw grave.

**Comment by josephj11** [comment]
@Elliria If you're talking about the lost enhancement, the problem is figuring out whose personal repo it was/is in.

**Comment by Elliria** [comment]
> The problem with a custom trigger is that AutoKey cannot distinguish between, say, a simple/raw grave `` ` `` and a dead grave. I could omit the grave from the trigger list, which would indeed prevent expansions when followed by a grave-accented letter like è but I still want my abbreviations to expand if I follow them by a raw grave.

I must admit to not knowing the difference, either. How are each of them created?

**Comment by Elliria** [comment]
> @Elliria If you're talking about the lost enhancement, the problem is figuring out whose personal repo it was/is in.

Ah, okay. If it was part of a pull request that didn't go through and was closed, it should still exist in the code. I did [this search of the code](https://github.com/search?q=repo%3Aautokey%2Fautokey+chorded&type=issues) and turned up issue #208. Is that the one?

**Comment by josephj11** [comment]
That one has a reference to it in one of my comments, but nothing about who did it or where. 

I did a quick scan of xpusostomos's repo and didn't find it there. One down...
