### ISSUE TITLE
Xlib.error.BadWindow

### ISSUE THREAD

**Issue by feluxe** [autokey/autokey#438]
## Classification:

Crash/Error

## Reproducibility:

Always

## Version

AutoKey version: `0.95.10`

Used GUI (Gtk, Qt, or both): `autokey-gtk`

Installed via: `pipx`

Linux Distribution: `arch`

## Summary

If I start `autokey-gtk` from the command line I get a bunch of errors similar to this one:

```
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1922, major_opcode = 33, minor_opcode = 0
```

## Steps to Reproduce (if applicable)

* I open a terminal
* I run `autokey-gtk` and get the error.

## Expected Results

It should run without errors. ;)

## Actual Results

I start it and get the errors.

<details><summary><b>Error Log from `autokey-gtk`</b></summary>
<p>

```
(autokey-gtk:142509): Gdk-CRITICAL **: 12:11:29.411: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1858, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1859, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1860, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1861, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1862, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1863, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1864, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1865, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1866, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1867, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1868, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1869, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1870, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1871, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1872, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1873, major_opcode = 33, minor_opcode = 0
```

</p>
</details>

<details><summary><b>Error Log from `autokey-gtk --verbose`</b></summary>
<p>

```
.......

(autokey-gtk:146360): Gdk-CRITICAL **: 12:17:39.121: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
2020-08-11 12:17:39,935 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/home/felix/.local/pipx/venvs/autokey/lib/python3.8/site-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/home/felix/.local/pipx/venvs/autokey/lib/python3.8/site-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/home/felix/.local/pipx/venvs/autokey/lib/python3.8/site-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/home/felix/.local/pipx/venvs/autokey/lib/python3.8/site-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/home/felix/.local/pipx/venvs/autokey/lib/python3.8/site-packages/Xlib/xobject/drawable.py", line 455, in get_property
    r = request.GetProperty(display = self.display,
  File "/home/felix/.local/pipx/venvs/autokey/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/home/felix/.local/pipx/venvs/autokey/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1893, major_opcode = 20, minor_opcode = 0

........

X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1908, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1909, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1910, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1911, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1912, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1913, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1914, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1915, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1916, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1917, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1918, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1919, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1920, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1921, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1922, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04e00002), sequence_number = 1923, major_opcode = 33, minor_opcode = 0

........
```

## Notes

It worked for some years. The errors started to appear after I upgraded `autokey` and the OS.

**Comment by josephj11** [comment]
It might be awhile before a developer answers (summer...), so I'll grasp at a straw or two.

Arch (which I know very little about) is very picky about program (dependencies) versions. Sometimes it names them by including the version in the name which can lead to problems when things don't get upgraded simultaneously.

I don't know much about pip either. I do recall someone having problems installing AutoKey because the source code didn't get updated in pyPI.

If you're an Arch user, you're probably far more technically competent than I am, but you might want to take a look at our [installation instructions](https://github.com/autokey/autokey/wiki/Installing#pip-installation) to see if they offer any insights.

We have seen that particular error message a bunch of times before. I found three open issues that reference it, but I'm not sure any of them will be helpful.

**Comment by feluxe** [comment]
I've been fiddling with this for a while, but nothing really helped.

> Arch (which I know very little about) is very picky about program (dependencies) versions. Sometimes it names them by including the version in the name which can lead to problems when things don't get upgraded simultaneously.

I think I have xlib available. I'm not sure how to debug this.

> I don't know much about pip either. I do recall someone having problems installing AutoKey because the source code didn't get updated in pyPI.

I install it via pipx directly from the github repo, so I get the latest version.

>  but you might want to take a look at our installation instructions to see if they offer any insights.

I've been there several times. I think all dependencies should be there, because autokey worked before.

> We have seen that particular error message a bunch of times before. I found three open issues that reference it, but I'm not sure any of them will be helpful.

I've been there, but couldn't find a path into the right direction.


**Update**

I noticed the acutal crash creates this output later on:

```
(autokey-gtk:234160): Gdk-WARNING **: 14:45:02.858: GdkWindow 0x1c00006 unexpectedly destroyed

(autokey-gtk:234160): Gdk-ERROR **: 14:45:02.868: The program 'autokey-gtk' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadPicture (invalid Picture parameter)'.
  (Details: serial 330 error_code 143 request_code 139 (RENDER) minor_code 7)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
zsh: trace trap (core dumped)  autokey-gtk

```

**Comment by sebastiansam55** [comment]
Does this error impede use of the AutoKey program in any way? I get a few of these every once in a while but I only notice because I'm looking at the log for other reasons, I don't know that I've ever had any issues that I've tracked down to caused by this error.

**Comment by HumptyDumptyNumpty** [comment]
I have a similar issue - I am trying to debug another issue and in the journalctl output saw dozens of identical errors from autokey.
My autokey (I suspect) was installed on Ubuntu 20.04 using sudo apt install.
The report shows:-
`autokey.desktop[3014]: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04a00>
autokey.desktop[3014]: X protocol error:`
and then these two lines repeat many times.
Any help with working out what I have done wrong would be appreciated.
(I have left the default scripts and phrases, but have added a couple of additional phrases that are activated on - hopefully - unusual keystrokes).

**Comment by josephj11** [comment]
@HumptyDumptyNumpty If you installed using apt, there's not much you could have done wrong. We have had these problems (not even sure it's just one problem) for quite a while. The only thing that seems to stand out was upgrading X11 from something.19 to something.20. It looks like something upstream changed, but no one has figured it out AFAIK.

**Comment by HumptyDumptyNumpty** [comment]
@josephj11 Many thanks for letting me know.
If I get a few minutes, I will see if there is any other information that may be of help.
Kind Regards,

**Comment by Elliria** [comment]
I can verify this under **Kubuntu 24.04 LTS** with **AutoKey 95.10** installed from the Ubuntu repositories. I'm attaching a log from a quick run of AutoKey in verbose mode where I just ran it and exited. It doesn't seem to have any effect on the use of the program.

[log.txt](https://github.com/user-attachments/files/25638400/log.txt)

**Comment by josephj11** [comment]
I vaguely remember something like this that appeared to be caused by assigning hotkeys to an action that were already in use by the desktop or some other programs higher in the keyboard food chain than AutoKey.

**Comment by Anonymouse83** [comment]
A couple of months ago (at the most) this was working for me, but now I have the same issue - plus any hotkeys I have tried, no longer work, although I haven't changed the hotkeys in a year or more!
I am running Ubuntu 22.04, with Autokey v. 0.95.10.
Bizarrely, I normally run `autokey-gtk`, but by mistake, I typed `autokey` (version 0.95.10 as well) and it all seemed to work (i.e. hotkeys worked) - but the same error messages!

**Comment by josephj11** [comment]
@Anonymouse83 The only thing I can think of is that you may have updated your environment via normal upgrades and it may have grabbed some new keys. 

I use KDE and a trip into its settings reveals a multitude of assigned hotkeys, most of which do things that eitiher don't make sense to me or that I would never want a hotkey for.

So far (a very long time), errors like these have been pretty opaque as to their origin/cause.

Normally, "autokey" ends up under /etc/alternatives and points to the first? AutoKey front end you installed. That's probably why it works.

Although it is unlikely to fix this particular problem, we highly recommend that you upgrade to our current release. See boiler plate below.

----

I notice that you are not running 0.96.0, our current release. This release contains a lot of bug fixes and a few new features. We highly encourage users to upgrade as soon as possible. You can find it [here](https://github.com/autokey/autokey/releases/) and instructions are [here](https://github.com/autokey/autokey/wiki/Installing).

The installation is pretty easy to do and we also provide .deb packages for users of Debian and Debian-derived distributions (Ubuntu, Mint, ...).

**Comment by Anonymouse83** [comment]
@josephj11 many thanks for your help.
I did have a look at the keys I have been using and whether they conflict with Ubuntu allocated keys, and I couldn't find any - and I also recalled that on the CLI, `autokey` worked.
I have now removed `autokey-common` and `autokey-gtk`, downloaded the new debs and installed them using dpkg.
I haven't checked running from the CLI to see if the errors are replicated, but the hotkeys work again, so thank you very much!
Kind Regards,

**Comment by Elliria** [comment]
Yep. I came across one or more like that when I did a search for just **window** or **bad window**, but not when I put the entire error message in. What's interesting is that it's just there in the log and doesn't seem to cause any trouble, at least for some of us.
