### ISSUE TITLE
Expansions sometimes pastes clipboard content instead of intended text

### ISSUE THREAD

**Issue by dchen327** [autokey/autokey#456]
## Classification:

Bug
## Reproducibility:

Sometimes, Rarely

## Version

AutoKey version: 
0.95.10

Used GUI (Gtk, Qt, or both): 
Gtk
If the problem is known to be present in more than one version, please list all of those.

Linux Distribution:
Pop! OS 20.04 (Based on Ubuntu)

## Summary

Occasionally when I type triggers that I want to expand to certain text, whatever I have copied in my clipboard is pasted. Sometimes nothing is inserted and the trigger disappears, but I can backspace to restore the trigger text. Usually if I copy some other text, it's fixed.

## Steps to Reproduce (if applicable)

Type a trigger.

## Expected Results

The trigger should expand to the text I've set.

## Actual Results

My clipboard is pasted (or nothing is pasted at all).

**Comment by josephj11** [comment]
We need more information.
I assume this is about phrases and not scripts.
What exactly do you do with "copy other text" that fixes it?
What "Paste using" option are you using?
Does this occur with multiple phrases?
Is there any pattern as to when it occurs?
It would be helpful to have a [trace](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide) of the failure.
We need as much information as possible because we have to be able to recreate issues in order to debug and fix them.

**Comment by dchen327** [comment]
To fix it, I usually just need to ctrl+c to copy anything. The my phrase expansions work again. I'm pasting with clipboard `ctrl + v`, and changing to pasting with clipboard `ctrl + shift + v` doesn't have any impact. I'll try using `shift + insert` because I actually haven't test that. I don't think there's any pattern as far as I can tell. I'll try a trace sometime. Thanks!

**Comment by josephj11** [comment]
`Ctrl+Shift+V` exists mainly because you need it in terminals which use `Ctrl+V` for something else.

When this occurs, does it keep happening several times in a row or just sporadically?

The challenge with bugs like this is that you have to stop AutoKey and relaunch it with tracing turned on and there's no guarantee that the bug will manifest at that point. If you just run normally with tracing on, the output gets large quickly and gets truncated at your terminal scroll-back limit. That's usually not an issue because the part we need to see is almost always at the end of the trace, but I'm not sure if that will create other problems.

It would have been really bizarre if you had been using Paste using keyboard!

**Comment by dchen327** [comment]
I'm going to try running with tracing turned on, but now I remember why I couldn't input with keyboard. Since my phrases are emojis, if I insert with keyboard only a space shows up. I'll update back if I see anything with tracing on!

**Comment by dchen327** [comment]
```
2020-10-20 09:50:21,306 DEBUG - interface - Sending string via clipboard: 😆 
2020-10-20 09:50:21,306 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
```

Here's the trace I get when it fails to insert the correct phrase.

**Comment by jspaetzel** [comment]
I've noticed this on my machine as well but haven't dug into it yet. When I've noticed it in the past I get in a state where it's stuck and replaces any phrase I attempt with whatever is currently in my ~keyboard~ clipboard.

I'm also on 0.95.10 but on Ubuntu 12.04.

**Comment by dchen327** [comment]
@jspaetzel when you say whatever is currently in keyboard you mean the clipboard content right? It seems we're facing the exact same bug.

**Comment by josephj11** [comment]
@dchen327 I've been trying to get that error message muted for years. It happens all the time and doesn't affect anything.
The code locks and unlocks some resource and sometimes it tries to unlock it when it's not locked. Nobody has tried (or at least succeeded) to track it down and fix it.

The trace shows that it sent your emoji, so how you got anything else is quite puzzling.

Yes, our keyboard library/module can't deal with multibyte characters or almost anything that you couldn't type manually on a physical keyboard, but using the clipboard usually works fine.

If this is a serious problem for you, you might try using autokey-qt instead. If you don't have any other Qt applications installed, installing this will bring in a bunch of dependencies.

We are in the process of reorganizing our developers and it may be some time before we have another release.

**Comment by dchen327** [comment]
What's the difference in autokey-gt? But yeah it's quite odd that it shows my emoji was sent, but it very clearly pastes something else. The most annoying part is when it pastes an empty thing, so i need to hit delete a couple times to delete the phrase trigger.

**Comment by jspaetzel** [comment]
@dchen327 that's correct, the clipboard content.

**Comment by josephj11** [comment]
@dchen327 The two front ends use completely separate code bases and GUI libraries, so sometimes they behave differently although we try to make them function identically.

**Comment by Salvatos** [comment]
This happens to me frequently, so I can share a few observations.

1. It happens independently of the pasting mode (keyboard or Ctrl+V) and content (regular words or special characters).
2. It (almost?) never happens in some apps, but happens frequently in others, and almost always in some interfaces.
3. In some cases, backspacing and typing the abbreviation again will paste the correct result. In others, there is seemingly nothing I can do to make it work.

Specifically:
- In LibreOffice, it happens with some frequency, but backspacing and redoing the abb. fixes it. I’ve noticed that it seems to happen more when I’m coming from another window/app, and if I’m not mistaken, after it happens once it’s fixed at least until I alt-tab back and forth again. It also seems to happen mostly or only with apostrophes, so I suspect a conflict between Autokey and LibreOffice’s own replacement of single quotes into actual apostrophes.
- In text editors like xed and Geany, I don’t think I’ve ever encountered the issue, nor in Thunderbird or Discord.
- It’s generally not a problem in input fields on Firefox, however it is prevalent in some translation platforms I use daily that rely on JS monstrosities instead of actual input fields.
- Notably, in XTM, the input fields are div elements and while Autokey sometimes works there, mostly it will paste my clipboard content over and over. Oddly, a replacement I use for curly apostrophes ("`'`" to "`’`") usually works fine, but `ndash-` to `–` breaks almost every time. Testing again now, it looks like it needs a special character (such as `–` or `œ`) to start happening, and then it breaks some other replacements too, but I can’t quite isolate which (most of them contain a curly apostrophe, line break or other special character and use clipboard replacement, but I also have `‽` that continues to work from the clipboard so...).
- Another example is memoQWeb, which I believe does something similar though I can’t check the exact HTML at the moment, and where I can strictly never use my curly apostrophe replacement because while it does paste the content, it also leaves the trigger character and deletes the character _before_ it (e.g. when I type "`d'`", it should change to "`d’`", but instead it changes to "`'’`"). I believe this has more to do with the JS on the page than with Autokey, though, since it’s even worse than XTM’s.

Here is a stack trace from XTM since I can reliably reproduce it there.

**Input:**
`aujourd'hui ajd l`

**Expected output:**
`aujourd’hui aujourd’hui l`

**Actual output (`**` being my clipboard content at the time):**
`aujourd’hui **l`

Note that the single apostrophe replacement works in the first word, but the expansion of `ajd` into `aujourd’hui` inserts the clipboard content, and the space trigger character is lost.

```
2021-05-06 12:27:23,909 DEBUG - service - Raw key: 'a', modifiers: [], Key: a
2021-05-06 12:27:23,909 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:23,910 DEBUG - service - Input queue at end of handle_keypress: deque(['a'], maxlen=150)
2021-05-06 12:27:24,110 DEBUG - service - Raw key: 'u', modifiers: [], Key: u
2021-05-06 12:27:24,110 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:24,110 DEBUG - service - Input queue at end of handle_keypress: deque(['a', 'u'], maxlen=150)
2021-05-06 12:27:24,342 DEBUG - service - Raw key: 'j', modifiers: [], Key: j
2021-05-06 12:27:24,342 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:24,342 DEBUG - service - Input queue at end of handle_keypress: deque(['a', 'u', 'j'], maxlen=150)
2021-05-06 12:27:24,589 DEBUG - service - Raw key: 'o', modifiers: [], Key: o
2021-05-06 12:27:24,589 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:24,590 DEBUG - service - Input queue at end of handle_keypress: deque(['a', 'u', 'j', 'o'], maxlen=150)
2021-05-06 12:27:24,650 DEBUG - service - Raw key: 'u', modifiers: [], Key: u
2021-05-06 12:27:24,650 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:24,650 DEBUG - service - Input queue at end of handle_keypress: deque(['a', 'u', 'j', 'o', 'u'], maxlen=150)
2021-05-06 12:27:24,989 DEBUG - service - Raw key: 'r', modifiers: [], Key: r
2021-05-06 12:27:24,990 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:24,990 DEBUG - service - Input queue at end of handle_keypress: deque(['a', 'u', 'j', 'o', 'u', 'r'], maxlen=150)
2021-05-06 12:27:25,237 DEBUG - service - Raw key: 'd', modifiers: [], Key: d
2021-05-06 12:27:25,237 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:25,238 DEBUG - service - Input queue at end of handle_keypress: deque(['a', 'u', 'j', 'o', 'u', 'r', 'd'], maxlen=150)
2021-05-06 12:27:26,245 DEBUG - iomediator - Key.SHIFT pressed
2021-05-06 12:27:26,389 DEBUG - service - Raw key: ',', modifiers: [<Key.SHIFT: '<shift>'>], Key: '
2021-05-06 12:27:26,389 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:26,390 INFO - service - Matched Phrase "curly apos" having abbreviations "["'"]" against current input
2021-05-06 12:27:26,390 DEBUG - iomediator - Send via clipboard
2021-05-06 12:27:26,390 DEBUG - service - Input queue at end of handle_keypress: deque([], maxlen=150)
2021-05-06 12:27:26,391 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
2021-05-06 12:27:26,390 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2021-05-06 12:27:26,390 DEBUG - interface - Sending string via clipboard: ’
2021-05-06 12:27:26,392 DEBUG - interface - Sending via clipboard enqueued.
2021-05-06 12:27:26,398 DEBUG - iomediator - Send via event interface
2021-05-06 12:27:26,398 DEBUG - interface - Send modified key: modifiers: ['<ctrl>'] key: v
2021-05-06 12:27:26,602 DEBUG - iomediator - Key.SHIFT released
2021-05-06 12:27:27,461 DEBUG - service - Raw key: 'h', modifiers: [], Key: h
2021-05-06 12:27:27,462 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:27,462 DEBUG - service - Input queue at end of handle_keypress: deque(['h'], maxlen=150)
2021-05-06 12:27:27,669 DEBUG - service - Raw key: 'u', modifiers: [], Key: u
2021-05-06 12:27:27,669 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:27,670 DEBUG - service - Input queue at end of handle_keypress: deque(['h', 'u'], maxlen=150)
2021-05-06 12:27:27,869 DEBUG - service - Raw key: 'i', modifiers: [], Key: i
2021-05-06 12:27:27,869 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:27,870 DEBUG - service - Input queue at end of handle_keypress: deque(['h', 'u', 'i'], maxlen=150)
2021-05-06 12:27:28,621 DEBUG - service - Raw key: ' ', modifiers: [], Key:  
2021-05-06 12:27:28,621 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:28,622 DEBUG - service - Input queue at end of handle_keypress: deque(['h', 'u', 'i', ' '], maxlen=150)
2021-05-06 12:27:29,565 DEBUG - service - Raw key: 'a', modifiers: [], Key: a
2021-05-06 12:27:29,565 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:29,565 DEBUG - service - Input queue at end of handle_keypress: deque(['h', 'u', 'i', ' ', 'a'], maxlen=150)
2021-05-06 12:27:29,725 DEBUG - service - Raw key: 'j', modifiers: [], Key: j
2021-05-06 12:27:29,725 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:29,725 DEBUG - service - Input queue at end of handle_keypress: deque(['h', 'u', 'i', ' ', 'a', 'j'], maxlen=150)
2021-05-06 12:27:29,837 DEBUG - service - Raw key: 'd', modifiers: [], Key: d
2021-05-06 12:27:29,837 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:29,838 DEBUG - service - Input queue at end of handle_keypress: deque(['h', 'u', 'i', ' ', 'a', 'j', 'd'], maxlen=150)
2021-05-06 12:27:30,373 DEBUG - service - Raw key: ' ', modifiers: [], Key:  
2021-05-06 12:27:30,373 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:30,373 INFO - service - Matched Phrase "aujourd’hui" having abbreviations "['ajd']" against current input
2021-05-06 12:27:30,374 DEBUG - iomediator - Send via clipboard
2021-05-06 12:27:30,374 DEBUG - service - Input queue at end of handle_keypress: deque([], maxlen=150)
2021-05-06 12:27:30,374 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
2021-05-06 12:27:30,374 DEBUG - interface - Sending string via clipboard: aujourd’hui 
2021-05-06 12:27:30,374 DEBUG - interface - Sending via clipboard enqueued.
2021-05-06 12:27:30,375 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2021-05-06 12:27:30,376 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2021-05-06 12:27:30,376 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2021-05-06 12:27:30,376 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2021-05-06 12:27:30,378 DEBUG - iomediator - Send via event interface
2021-05-06 12:27:30,379 DEBUG - interface - Send modified key: modifiers: ['<ctrl>'] key: v
2021-05-06 12:27:35,333 DEBUG - service - Raw key: 'l', modifiers: [], Key: l
2021-05-06 12:27:35,333 DEBUG - service - Window visible title: 'XTM Workbench - Mozilla Firefox', Window class: 'Navigator.Firefox'
2021-05-06 12:27:35,334 DEBUG - service - Input queue at end of handle_keypress: deque(['l'], maxlen=150)
```
This is on Mint Cinnamon 20.1, using autokey-gtk 0.95.10 (can also reproduce with autokey-qt).

**Comment by josephj11** [comment]
@salvatos Thanks for all the hard work and detailed information.
Some general observations:
I'm not sure what you named your phrase, but you really shouldn't include any special characters in the name because AutoKey uses it as a file name for the phrase and, even though it's legal in Linux, it's not a good idea to have file names with metacharacters like single quotes in them.

If it happens in some apps, but not in others, it's often a timing problem.
AutoKey types at machine speed and some apps can't keep up. Pasting (as you have done) usually avoids such issues.
LibreOffice and Firefox (especially in the address bar) often have these issues.

The trace looks like AutoKey worked correctly. The locking error is effectively a non-event and has finally been fixed (after a decade!) in 0.96 which we're just starting to beta test.

The first thing to try is to convert it from a phrase to a script. In script form, you can add delays before and after or even between characters and see if slowing things down solves the problem.

For this first reply, I'm not going to add all the scripting details in case you are already familiar with them, but I can get as specific as necessary later.

If you want to get really slow to see if that's the issue, you can use my [type_slow()](https://github.com/autokey/autokey-python2/wiki/Contributed-Scripts#function-to-type-text-slowly) function.
You can also explicitly clear the clipboard at the start of your script if you want to.

**Comment by BlueDrink9** [comment]
Are there any other open issues about the clipboard? I know from my work with autohotkey on Windows, that clipboard timing can be very tricky. Setting the clipboard is usually asynchronous, so you have to wait until the contents have changed. That is tricky to do though without explicitly checking the clipboard contents. So it could be to do with that?

**Comment by josephj11** [comment]
LOL. Surely you jest. I just searched open issues for clipboard and it found 37. For many of those, the clipboard is probably secondary or not really a factor, but you get the idea.

Just to restate the hopefully obvious: in both Qt and GTK, calls that affect the clipboard return success immediately while the actual processes are in fact asynchronous. This messes everybody up until they realize that delays have to be inserted in scripts after doing anything with the clipboard - and, for some reason, sometimes before accessing the clipboard.

You don't have to look at the clipboard. Usually, a delay of between 0.1 and 0.5 seconds makes things work as expected.

It might be worth considering wrapping our clipboard API calls in something that adds a 0.1 second delay before returning to the user upon success. That wouldn't slow things down noticeably and it would probably eliminate most of the race conditions.

**Comment by BlueDrink9** [comment]
I'd rather wrap the clipboard api in something that checks the clipboard and ensures it is set properly tbh, because a large clip or a clipboard that previously had an image would need a longer delay. Would depend on how much delay such a check adds though.

**Comment by josephj11** [comment]
If you can figure out how to do that, it would be great. Maybe it could give up after some maximum time so it wouldn't add a huge delay. Then, it would fall back on the script writer to defend their code as appropriate. Maybe it could return success, failure, and timeout codes so the script would know what happened.

**Comment by josephj11** [comment]
To all other contributors to this issue: Have you found any workarounds? Is this just a race condition/timing issue or something more?

**Comment by Elliria** [comment]
I saw this issue the other day in a cloned copy of AutoKey 0.96.0 running under Kubuntu 22.04 LTS inside of a virtual machine. I was doing a lot of regex trigger tests and suddenly my clipboard contents were the only thing that was pasted. The only thing that worked to stop it was closing AutoKey and typing `pkill autokey` into a terminal window and then running AutoKey again. I didn't get a trace and it hasn't happened again.
