### ISSUE TITLE
script works in Linuxmint 19.3 (Python 3.6.5) but not in LM20 (Python 3.8.5)

### ISSUE THREAD

**Issue by ven-u** [autokey/autokey#460]
## Classification:

(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement)

## Reproducibility:

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)

## Version

AutoKey version: 

Used GUI (Gtk, Qt, or both): 

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).

Linux Distribution:

## Summary

Summary of the problem.

## Steps to Reproduce (if applicable)

- I do this
- I do that

## Expected Results

- This should happen.

## Actual Results

- Instead, this happens. :(

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

**Comment by ven-u** [comment]
Autokey-gtk, 0.95.10; 
Reproducibility: always
Autokey was installed via Linuxmint repository (apt install autokey-gtk)

I need a script that will paste unicode (utf-8) characters into a document. The Kate text editor, for instance, doesn't allow the key sequence "<ctrl-shit-u >[u-code point] " to input a character. But you can PASTE a unicode/utf8 character onto the Kate editing pane.

In LM19.3, this script, which I copied from StackOverflow, works flawlessly:

```
import sys
reload(sys)
sys.setdefaultencoding('utf8')
from subprocess import Popen, PIPE

def paste_character(symbol):
    c = Popen(['xclip', '-selection', 'clipboard'], stdin=PIPE)
    c.communicate(symbol.encode('utf-8')) 
    keyboard.send_keys('<ctrl>+v')

paste_character('ā')
```
This is the error:
Script name:'MyCopy'
Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/autokey/service.py", line 485, in execute exec(script.code,scope)
 File "<string", line2, in <module>
NameError: name 'reload' is not defined.

Workaround: I have gone back to the following script, which doesn't work with Kate and some other text editor:

```
# a-macron u-101
import sys
keyboard.send_keys("<ctrl>+<shift>+u101 ")
sys.exit()
```

============== autokey-gtk --verbose (note -- this is  the tail end of the enormous screen output. I entered the trigger abbreviation, then shut down Autokey)
2020-11-10 22:39:44,291 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'q'
2020-11-10 22:39:44,291 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'q'
2020-11-10 22:39:44,292 DEBUG - interface - Grabbing hotkey: ['<ctrl>'] '<f7>'
2020-11-10 22:39:56,230 DEBUG - service - Raw key: '.', modifiers: [], Key: .
2020-11-10 22:39:56,230 DEBUG - service - Window visible title: '*Unsaved Document 1', Window class: 'xed.Xed'
2020-11-10 22:39:56,230 DEBUG - service - Input queue at end of handle_keypress: deque(['.'], maxlen=150)
2020-11-10 22:39:56,448 DEBUG - service - Raw key: '.', modifiers: [], Key: .
2020-11-10 22:39:56,448 DEBUG - service - Window visible title: '*Unsaved Document 1', Window class: 'xed.Xed'
2020-11-10 22:39:56,448 DEBUG - service - Input queue at end of handle_keypress: deque(['.', '.'], maxlen=150)
2020-11-10 22:39:56,594 DEBUG - service - Raw key: 'a', modifiers: [], Key: a
2020-11-10 22:39:56,595 DEBUG - service - Window visible title: '*Unsaved Document 1', Window class: 'xed.Xed'
2020-11-10 22:39:56,595 INFO - service - Matched Script "MyCopy" having abbreviations "['..a']" against current input
2020-11-10 22:39:56,597 DEBUG - service - Script runner executing: Script('MyCopy')
2020-11-10 22:39:56,597 DEBUG - service - Input queue at end of handle_keypress: deque([], maxlen=150)
2020-11-10 22:39:56,598 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
2020-11-10 22:39:56,598 ERROR - service - Script error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 485, in execute
    exec(script.code, scope)
  File "<string>", line 2, in <module>
NameError: name 'reload' is not defined
2020-11-10 22:39:56,598 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2020-11-10 22:39:56,601 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2020-11-10 22:39:56,601 DEBUG - interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2020-11-10 22:40:12,707 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 's'
2020-11-10 22:40:12,707 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 'p'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 'v'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 'z'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 'h'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 'm'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'x'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'b'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'm'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'a'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'q'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 's'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 'p'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 'v'
2020-11-10 22:40:12,708 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 'z'
2020-11-10 22:40:12,709 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 'h'
2020-11-10 22:40:12,709 DEBUG - interface - Grabbing hotkey: ['<ctrl>', '<super>'] 'm'
2020-11-10 22:40:12,709 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'x'
2020-11-10 22:40:12,709 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'b'
2020-11-10 22:40:12,709 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'm'
2020-11-10 22:40:12,709 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'a'
2020-11-10 22:40:12,709 DEBUG - interface - Grabbing hotkey: ['<alt>', '<ctrl>', '<super>'] 'q'
2020-11-10 22:40:13,325 INFO - root - Shutting down
2020-11-10 22:40:13,326 INFO - service - Service shutting down
2020-11-10 22:40:13,326 DEBUG - iomediator - IoMediator shutting down
2020-11-10 22:40:13,326 DEBUG - interface - XInterfaceBase: Try to exit event thread.
2020-11-10 22:40:13,326 DEBUG - interface - XInterfaceBase: Event thread exit marker enqueued.
2020-11-10 22:40:13,326 DEBUG - interface - XInterfaceBase: self.shutdown set to True. This should stop the listener thread.
2020-11-10 22:40:13,462 DEBUG - interface - __flushEvents: Left event loop.
2020-11-10 22:40:13,468 DEBUG - iomediator - Waiting for IoMediator thread to end
2020-11-10 22:40:13,469 DEBUG - iomediator - IoMediator shutdown completed
2020-11-10 22:40:13,469 INFO - config-manager - Persisting configuration
2020-11-10 22:40:13,469 INFO - config-manager - Backing up existing config file
2020-11-10 22:40:13,469 DEBUG - inotify - Reporting IN_MODIFY event at /home/sadhu/.config/autokey/autokey.json~
2020-11-10 22:40:13,470 DEBUG - inotify - Reporting IN_MODIFY event at /home/sadhu/.config/autokey/autokey.json
2020-11-10 22:40:13,470 INFO - config-manager - Finished persisting configuration - no errors
2020-11-10 22:40:13,470 DEBUG - service - Service shutdown completed.
2020-11-10 22:40:14,471 INFO - inotify - Shutting down file monitor
2020-11-10 22:40:14,485 DEBUG - root - All shutdown tasks complete... quitting

**Comment by sebastiansam55** [comment]
You don't really need to `sys.exit()`. The file will just complete its execution.

I'm also not sure that reloading the sys module is necessary, as you import it the line before. My brief understanding of the reload function is that it basically resets it like you have just imported it, which you did in the line before. Not familiar with that function of python however.

From reading some of the other issues filed the `send_keys` function does not really work with special characters.

You should switch to using the phrases function if all you are doing is pasting special characters, I use it for pasting greek characters for statistics work and it works fine, just make sure you switch the "Paste Using" drop down to Clipboard, I have it set to "Clipboard (Ctrl+V)" and haven't had any issues with it.

**Comment by josephj11** [comment]
As Sam says, multibyte characters have to be emitted by pasting from the clipboard in phrases and scripts because the "typing" library doesn't support them (a bug we currently don't know how to fix.)

We appreciate and support usage questions, but they should be made on our [support list](https://groups.google.com/forum/#!forum/autokey-users) or, for more advanced questions, on our [Gitter page](https://gitter.im/autokey/autokey).

**Comment by josephj11** [comment]
For anyone finding this later, we have a new [Wiki article](https://github.com/autokey/autokey/wiki/Adding-Unicode-Characters-or-Emojis-to-Your-Scripts-or-Phrases) which covers this extensively.
