### ISSUE TITLE
 Fatal error starting Autokey. can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by sl5net** [autokey/autokey#464]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 

Qt

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).

Linux Distribution:

## Summary

Summary of the problem.

## Steps to Reproduce (if applicable)

1. I was working on Lintalist4Linux
1. testing Lintalist4Linux in VirtualBox very often
1. running Lintalist4Linux in Host
1. running Lintalist4Linux in Guest at the same time
1. disabled Lintalist4Linux in Guest
1. suddenly this errors happens
1. uninstalled autokey
1. installed autokey

## Expected Results

- no error

## Actual Results

1. started Autokey
-  Fatal error starting Autokey. can only concatenate str (not "NoneType") to str

 `autokey-qt --verbose`

```
ner of name 'org.autokey.Service': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 218, in _verify_not_running
    dbus_service = bus.get_object("org.autokey.Service", "/AppService")
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.autokey.Service was not provided by any .service files
```

I'll keep trying. maybe set up my operating system from scratch if necessary.

**Comment by sl5net** [comment]
the ini file was corrupted by a third party script
