### ISSUE TITLE
Main window fails to open with X protocol error.

### ISSUE THREAD

**Issue by Janfel** [autokey/autokey#475]
## Classification:

UI/Usability

## Version

AutoKey version: 0.95.10

Used GUI: Both

Installed via: AUR

Linux Distribution: Manjaro Linux

## Summary

AutoKey suddenly stopped opening the main window automatically on startup. The main window can still be opened using the tray icon.

## Expected Results

The AutoKey main window opens on startup.

## Actual Results

The main window does not open, it can however be opened using the tray icon.

This error message appears without `--verbose`:

```
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 470, sequence_number = 26, major_opcode = 33, minor_opcode = 0
```

This is the output of `autokey-gtk --verbose`:

<details><pre>
2020-11-19 12:28:57,975 INFO - root - Initialising application
2020-11-19 12:28:57,981 INFO - root - Initialise global hotkeys
2020-11-19 12:28:57,981 INFO - config-manager - Loading config from existing file: /home/janfel/.config/autokey/autokey.json
2020-11-19 12:28:57,982 DEBUG - config-manager - Loading folder at '/home/janfel/.config/autokey/data/My Phrases'
2020-11-19 12:28:57,983 DEBUG - config-manager - Loading folder at '/home/janfel/.config/autokey/data/Sample Scripts'
2020-11-19 12:28:57,983 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2020-11-19 12:28:57,983 DEBUG - inotify - Adding watch for /home/janfel/.config/autokey/data/My Phrases
2020-11-19 12:28:57,984 DEBUG - inotify - Adding watch for /home/janfel/.config/autokey/data/My Phrases/Addresses
2020-11-19 12:28:57,984 DEBUG - inotify - Adding watch for /home/janfel/.config/autokey/data/Sample Scripts
2020-11-19 12:28:57,984 INFO - config-manager - Successfully loaded configuration
2020-11-19 12:28:57,984 DEBUG - inotify - Adding watch for /home/janfel/.config/autokey/data
2020-11-19 12:28:57,984 DEBUG - inotify - Adding watch for /home/janfel/.config/autokey
2020-11-19 12:28:57,984 DEBUG - config-manager - Global settings: {'isFirstRun': False, 'serviceRunning': True, 'menuTakesFocus': False, 'showTrayIcon': True, 'sortByUsageCount': True, 'promptToSave': False, 'enableQT4Workaround': False, 'interfaceType': 'XRecord', 'undoUsingBackspace': True, 'windowDefaultSize': [1920, 1139], 'hPanePosition': 260, 'columnWidths': [237, 49, 100], 'showToolbar': True, 'notificationIcon': 'autokey-status', 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'triggerItemByInitial': False, 'disabledModifiers': [], 'scriptGlobals': {}}
2020-11-19 12:28:57,984 INFO - service - Starting service
2020-11-19 12:28:58,002 DEBUG - interface - Modifier masks: {<Key.SHIFT: '<shift>'>: 1, <Key.CAPSLOCK: '<capslock>'>: 1, <Key.CONTROL: '<ctrl>'>: 4, <Key.ALT: '<alt>'>: 8, <Key.ALT_GR: '<alt_gr>'>: 128, <Key.SUPER: '<super>'>: 64, <Key.META: '<meta>'>: 8}
2020-11-19 12:28:58,023 DEBUG - interface - X Server Keymap, listing unmapped keys.
2020-11-19 12:28:58,023 DEBUG - iomediator - Set modifier Key.CAPSLOCK to False
2020-11-19 12:28:58,023 DEBUG - iomediator - Set modifier Key.NUMLOCK to False
2020-11-19 12:28:58,025 DEBUG - interface - Grabbing hotkey: ['<super>'] 'k'
2020-11-19 12:28:58,025 DEBUG - interface - __flushEvents: Entering event loop.
2020-11-19 12:28:58,025 DEBUG - interface - Grabbing hotkey: ['<shift>', '<super>'] 'k'
2020-11-19 12:28:58,025 INFO - iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2020-11-19 12:28:58,025 DEBUG - interface - Grabbing hotkey: ['<ctrl>'] '<f7>'
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 470, sequence_number = 26, major_opcode = 33, minor_opcode = 0
2020-11-19 12:28:58,031 INFO - interface - XRecord interface thread starting
2020-11-19 12:28:58,031 INFO - service - Service now marked as running
2020-11-19 12:28:58,036 DEBUG - phrase-menu - Sorting phrase menu by usage count
2020-11-19 12:28:58,036 DEBUG - phrase-menu - Triggering menu item by position in list
2020-11-19 12:28:58,038 DEBUG - root - Created DBus service
2020-11-19 12:28:58,038 INFO - root - Entering main()
2020-11-19 12:29:02,933 INFO - root - Shutting down
2020-11-19 12:29:02,934 INFO - service - Service shutting down
2020-11-19 12:29:02,934 DEBUG - iomediator - IoMediator shutting down
2020-11-19 12:29:02,934 DEBUG - interface - XInterfaceBase: Try to exit event thread.
2020-11-19 12:29:02,934 DEBUG - interface - XInterfaceBase: Event thread exit marker enqueued.
2020-11-19 12:29:02,935 DEBUG - interface - XInterfaceBase: self.shutdown set to True. This should stop the listener thread.
2020-11-19 12:29:03,836 DEBUG - interface - __flushEvents: Left event loop.
2020-11-19 12:29:03,837 DEBUG - iomediator - Waiting for IoMediator thread to end
2020-11-19 12:29:03,838 DEBUG - iomediator - IoMediator shutdown completed
2020-11-19 12:29:03,838 INFO - config-manager - Persisting configuration
2020-11-19 12:29:03,838 INFO - config-manager - Backing up existing config file
2020-11-19 12:29:03,839 DEBUG - inotify - Reporting IN_MODIFY event at /home/janfel/.config/autokey/autokey.json~
2020-11-19 12:29:03,840 DEBUG - inotify - Reporting IN_MODIFY event at /home/janfel/.config/autokey/autokey.json~
2020-11-19 12:29:03,841 DEBUG - inotify - Reporting IN_MODIFY event at /home/janfel/.config/autokey/autokey.json
2020-11-19 12:29:03,842 INFO - config-manager - Finished persisting configuration - no errors
2020-11-19 12:29:03,842 DEBUG - service - Service shutdown completed.
2020-11-19 12:29:04,843 INFO - inotify - Shutting down file monitor
2020-11-19 12:29:04,855 DEBUG - root - All shutdown tasks complete... quitting
</pre></details>

## Notes

This issue started appearing suddenly after I tried starting a different version of AutoKey using the [zero-installation method](https://github.com/autokey/autokey#zero-installation-method). Now every version I start has this problem. I did not run two versions of AutoKey at the same time.

**Comment by sebastiansam55** [comment]
This is running on startup? As in system startup or launching autokey startup?

Can you find the command used to launch AutoKey on startup? `python3 -m` is weird and I personally haven't been able to get it to launch a git version of AutoKey on startup.

For the log did you quit the program via user input or is that output with out any interaction with the program?

#67 seems similar (tho old)

**Comment by josephj11** [comment]
Aside from any x protocol errors - which need to be addressed - AutoKey, by default, will open without displaying the main window. If you launch it using `autokey-qt -c`, it should display the main window as desired.

Once Autokey is running, launching it a second time also causes the main window to be displayed.

This may be somehow related to upgrading from X11 0.19 to X11 0.20. We haven't identified what the issue is.

**Comment by Janfel** [comment]
> This is running on startup? As in system startup or launching autokey startup?

Sorry, I meant program startup, not system startup.

> Can you find the command used to launch AutoKey on startup?

From the console I just used `autokey-gtk`/`autokey-qt` without extra arguments. The .desktop files installed with the program use `autokey-gtk -c` and `autokey-qt` without `-c`.

> For the log did you quit the program via user input or is that output with out any interaction with the program?

I quit the program via user input using the system tray.

>  AutoKey, by default, will open without displaying the main window.

That feels a bit counter-intuitive and might be the cause of some confusion on my part. I thought this was related to the error message and did not investigate further.

> If you launch it using `autokey-qt -c`, it should display the main window as desired.

It does, thank you. Currently, `autokey-qt.desktop` does not use the `-c` flag though, that should probably be changed.

https://github.com/autokey/autokey/blob/fc7c6b90f3f28a57ad256829ef2b69e3be5148d2/config/autokey-qt.desktop#L6

**Comment by josephj11** [comment]
I'm not sure whether the -c should be added or not. It probably should be. In any case, both front-ends should work the same way.

**Comment by TheJoeSchr** [comment]
hi, I too get this error when starting `autokey-gtk` from cli, reported over and over again:
```
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 501, sequence_number = 22, major_opcode = 33, minor_opcode = 
```

when I try starting `autokey-qt` I even get, maybe thats related?
```python
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 33, in <module>
    sys.exit(load_entry_point('autokey==0.95.10', 'console_scripts', 'autokey-qt')())
  File "/usr/bin/autokey-qt", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/autokey/qtui/__main__.py", line 23, in <module>
    from autokey.qtapp import Application
  File "/usr/lib/python3.8/site-packages/autokey/qtapp.py", line 41, in <module>
    from autokey.qtui.configwindow import ConfigWindow
  File "/usr/lib/python3.8/site-packages/autokey/qtui/configwindow.py", line 40, in <module>
    class ConfigWindow(*autokey.qtui.common.inherits_from_ui_file_with_name("mainwindow")):
  File "/usr/lib/python3.8/site-packages/autokey/qtui/common.py", line 146, in load_ui_from_file
    base_type = uic.loadUiType(ui_file, from_imports=True)
  File "/usr/lib/python3.8/site-packages/PyQt5/uic/__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 292, in <module>
  File "/usr/lib/python3.8/site-packages/autokey/qtui/centralwidget.py", line 37, in <module>
    class CentralWidget(*ui_common.inherits_from_ui_file_with_name("centralwidget")):
  File "/usr/lib/python3.8/site-packages/autokey/qtui/common.py", line 146, in load_ui_from_file
    base_type = uic.loadUiType(ui_file, from_imports=True)
  File "/usr/lib/python3.8/site-packages/PyQt5/uic/__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 67, in <module>
  File "/usr/lib/python3.8/site-packages/autokey/qtui/scriptpage.py", line 20, in <module>
    from PyQt5 import Qsci
ImportError: cannot import name 'Qsci' from 'PyQt5' (/usr/lib/python3.8/site-packages/PyQt5/__init__.py)

```

but running `pip install pyqt5` I get: 
```sh
 pip install pyqt5
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyqt5 in /usr/lib/python3.8/site-packages (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/lib/python3.8/site-packages (from pyqt5) (12.8.1)
```

even tried removing and installing it again. I'm on arch/manjaro, please advise?

**Comment by sebastiansam55** [comment]
Try popping open python3 in a terminal a see if:
`from PyQt5 import Qsci` 
runs without errors. I might also trying searching for and install pyqt5 via whatever package manager arch/manjaro uses.

Interesting, this stackoverflow issue seems to indicate that the error stems from autokey trying to grab a hotkey that has already been grabbed. If anyone has a way to consistently trigger a BadAccess or BadWindow error that is replicate-able please share it.
https://stackoverflow.com/questions/36764217/ubuntu-hotkeys-with-x11-xlib-x-error-badaccess

**Comment by TheJoeSchr** [comment]
Thanks @sebastiansam55 at first it didn't work, although PyQt5 seems to be installed. But it brought me onto the right track! :tada: 

This were my results:
```sh
Already inside TMUX
joe@lxrush ~
$ python
Python 3.8.6 (default, Sep 30 2020, 04:00:38)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import Qsci
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Qsci' from 'PyQt5' (/usr/lib/python3.8/site-packages/PyQt5/__init__.py)
>>> from PyQt5 import sip
>>> exit()
joe@lxrush ~
$ pamac install python-pyqt5
Preparing...
Nothing to do.
Transaction successfully finished.
joe@lxrush ~
$
```

So I asked myself: "What is `Qsci` and how can I install it?"

Answer is as simple as `pamac install python-qscintilla-qt5` and now everything works! :smile: 

Thanks a lot!

**Comment by BlueDrink9** [comment]
This doesn't actually seem to be a bug, or at least nothing we can fix, so I'm closing it.

Two issues in the thread. The second is a missing dependency package, which has been address in documentation and which we can't automatically fix. The autokey AUR package has the correct dependencies anyway, so this shouldn't re-occur.

The thread was opened because the main window wasn't starting. This may be unintuitive, but for users that want autokey running on start-up, opening the config window when it starts up every reboot is awful UX imo.
There may be scope for changing the behavior to open the window by default for the `.desktop` files, but not when adding autostart entries, but this should be discussed in a separate, more focussed issue.
The protocol errors are red herrings because, as Sam pointed out, they happen when autokey tries to regrab already-grabbed keys (which X does not support).
We may want to catch these purely to re-label them, and it would be great to list exactly which keygrabs trigger it, but again a different and more focussed issue should be the place for discussion.
