### ISSUE TITLE
#354 fix causes IndexError: string index out of range

### ISSUE THREAD

**Issue by fx-kirin** [autokey/autokey#483]
## Classification:

Bug

## Reproducibility:

Just run this command through autokey.

``` python
system.exec_command("fcitx-remote -s **fcitx-keyboard-us")
```

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): 

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …). PPA

Linux Distribution: Linux Mint 20

## Summary

#354 adds some commands related to this problem. It causes the result.

## Expected Results

Nothing happens.

## Actual Results

``` python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
2020-11-29 23:28:13,811 ERROR - service - Script error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 485, in execute
    exec(script.code, scope)
  File "<string>", line 2, in <module>
  File "/usr/lib/python3/dist-packages/autokey/scripting.py", line 497, in exec_command
    if output[-1] == "\n":
IndexError: string index out of range
```

**Comment by xrat** [comment]
A workaround for this is `system.exec_command("fcitx-remote -s **fcitx-keyboard-us ; echo")` (using OPs example).

**Comment by josephj11** [comment]
#354 breaks when issuing any command that produces no output. There's a one line patch that will fix it. See #462.
