### ISSUE TITLE
Version installed from source zip via pip3 doesn't run

### ISSUE THREAD

**Issue by katoquro** [autokey/autokey#491]
## Classification:

Crash

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): Gtk

If the problem is known to be present in more than one version, please list all of those.

Installed via:  pip3 (pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6))

Linux Distribution: Ubuntu 18.04.5 LTS

## Summary

I've used version from distro but it is a bit outdated.
I've removed it ad tried to setup zip version via pip3 https://github.com/autokey/autokey/wiki/Installing#installing-autokey

## Steps to Reproduce (if applicable)

1. install via pip3 - everything is OK
1. run autokey-gtk - get error

## Expected Results

autokey runs ui

## Actual Results
```
$ autokey-gtk --verbose                                                                                                                        
Traceback (most recent call last):
  File "/home/katoquro/.local/bin/autokey-gtk", line 11, in <module>
    load_entry_point('autokey==0.95.10', 'console_scripts', 'autokey-gtk')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/katoquro/.local/lib/python3.6/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/katoquro/.local/lib/python3.6/site-packages/autokey/gtkapp.py", line 44, in <module>
    from autokey import service, monitor
  File "/home/katoquro/.local/lib/python3.6/site-packages/autokey/service.py", line 25, in <module>
    from autokey.iomediator.key import Key, KEY_FIND_RE
  File "/home/katoquro/.local/lib/python3.6/site-packages/autokey/iomediator/__init__.py", line 20, in <module>
    from ._windowgrabber import WindowGrabber
  File "/home/katoquro/.local/lib/python3.6/site-packages/autokey/iomediator/_windowgrabber.py", line 21, in <module>
    from ._iomediator import IoMediator
  File "/home/katoquro/.local/lib/python3.6/site-packages/autokey/iomediator/_iomediator.py", line 5, in <module>
    from ..configmanager import ConfigManager
  File "/home/katoquro/.local/lib/python3.6/site-packages/autokey/configmanager.py", line 990, in <module>
    class GlobalHotkey(model.AbstractHotkey):
AttributeError: module 'autokey.model' has no attribute 'AbstractHotkey'
```

## Notes
pip3 install log

```
pip3 install --user https://github.com/autokey/autokey/archive/v0.95.10.zip                                                                  
Collecting https://github.com/autokey/autokey/archive/v0.95.10.zip
  Using cached https://github.com/autokey/autokey/archive/v0.95.10.zip
Collecting pyinotify (from autokey==0.95.10)
Collecting python-xlib (from autokey==0.95.10)
  Using cached https://files.pythonhosted.org/packages/aa/b1/3d678b2426a3485ceb3ab1ec1e079da79ecb1b5e8845470ef089999cf688/python_xlib-0.29-py2.py3-none-any.whl
Collecting six>=1.10.0 (from python-xlib->autokey==0.95.10)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Installing collected packages: pyinotify, six, python-xlib, autokey
  Running setup.py install for autokey ... done
Successfully installed autokey-0.95.10 pyinotify-0.9.6 python-xlib-0.29 six-1.15.0
```

**Comment by katoquro** [comment]
Hm it looks like everything is OK and module contains class but it doesn't work(((

```
cat /home/katoquro/.local/lib/python3.6/site-packages/autokey/model.py | grep AbstractHotkey                                         
class AbstractHotkey(AbstractWindowFilter):
class Folder(AbstractAbbreviation, AbstractHotkey, AbstractWindowFilter):
        AbstractHotkey.__init__(self)
            "hotkey": AbstractHotkey.get_serializable(self),
        AbstractHotkey.load_from_serialized(self, data["hotkey"])
class Phrase(AbstractAbbreviation, AbstractHotkey, AbstractWindowFilter):
        AbstractHotkey.__init__(self)
            "hotkey": AbstractHotkey.get_serializable(self),
        AbstractHotkey.load_from_serialized(self, data["hotkey"])
class Script(AbstractAbbreviation, AbstractHotkey, AbstractWindowFilter):
        AbstractHotkey.__init__(self)
            "hotkey": AbstractHotkey.get_serializable(self),
        AbstractHotkey.load_from_serialized(self, data["hotkey"])
```

**Comment by katoquro** [comment]
Looks like it was an incompatibility with python libs installed with deb version so I've removed some suspicious in my opinion and everything starts work. 
`sudo apt-get remove libpython3-dev libdbus-1-dev && sudo apt autoremove`

**Comment by josephj11** [comment]
Glad it works for you now.

For future reference:
Yep, almost eight years is definitely "a bit out dated." :)

We finally have a Debian package maintainer again, so from 20.04 on, you should get a much more current release  from your package manager.

We provide debs [here](github.com/autokey/autokey/releases/) that are mostly distro/release independent, so if you need to reinstall on 18.04, you can use them and, hopefully, get the proper dependencies sorted for you.
