### ISSUE TITLE
locale setting causes AutoKey exception during startup

### ISSUE THREAD

**Issue by ghost** [autokey/autokey#511]
## Classification:
Crash/Hang/Data Loss

## Reproducibility:

Always

## Version

AutoKey version: 0.95.02

Used GUI (Gtk, Qt, or both): both

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …). AUR

Linux Distribution: Manjaro

## Summary

Summary of the problem.
When I start autokey it crashes
## Steps to Reproduce (if applicable)

- I do this "start autokey"

## Expected Results

- This should happen.
autokey to start
## Actual Results
Autokey crashes

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```

(autokey-gtk:33792): Gtk-WARNING **: 12:40:34.076: Locale not supported by C library.
        Using the fallback 'C' locale.

(autokey-gtk:33792): Gtk-WARNING **: 12:40:34.117: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(autokey-gtk:33792): Gtk-WARNING **: 12:40:34.117: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(autokey-gtk:33792): Gtk-WARNING **: 12:40:34.117: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Gtk-Message: 12:40:34.206: Failed to load module "appmenu-gtk-module"
Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 33, in <module>
    sys.exit(load_entry_point('autokey==0.95.10', 'console_scripts', 'autokey-gtk')())
  File "/usr/bin/autokey-gtk", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3.9/site-packages/autokey/gtkapp.py", line 47, in <module>
    from autokey.gtkui.configwindow import ConfigWindow
  File "/usr/lib/python3.9/site-packages/autokey/gtkui/configwindow.py", line 31, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

```

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

**Comment by josephj11** [comment]
You list the version as 0.95.2, but the traceback shows
`sys.exit(load_entry_point('autokey==0.95.10', 'console_scripts', 'autokey-gtk')())`
which is the current version.

You list the front end as Both, but the traceback shows the GTK front end and the error is GTK related. There doesn't seem to be a similar call in the Qt front end.

That's a pretty strange error. AFAIK, the LC_ALL locale is the least common denominator of all locales and should work on any normal Linux system.

What is the output of your `locale` command? Mine is

```
bigbird@sananda:~/installs/autokey/autokey/lib/autokey$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

If you also have the Qt front end installed, what does it do when you start it?

If it's not already installed, you can install it if you want to. Both front ends can be installed as long as you only run one at a time. If you don't already have other Qt applications installed, this will require/add a bunch of Qt libraries to your system.

Review [this](https://github.com/autokey/autokey/wiki/Installing#arch-linux) and see if it suggests anything you may have misssed.

**Comment by ghost** [comment]
```[xcomy@xcomy-hp250g5notebookpc ~]$ locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=mk_MK.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=mk_MK.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=mk_MK.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

I at one time had the qt versiono which did the same thing. The wiki only says to install missing dependecies if the programs outputs that they are missing

**Comment by ghost** [comment]
I changed my local settings to default now it works. But I am not pleased with the local settings. But I guess I am going to have to comprise. Thanks for the help

**Comment by josephj11** [comment]
Can you detail what changed between when it failed and now that it works? We will need that to be able to recreate the issue. Maybe you could change things back one at a time until it breaks.

For starters, the differences that I see between your locale and mine are the values of `LC_COLLATE`, `LC_TIME`, `LC_MONETARY`, and `LC_MEASUREMENT`. I can't think of any reason why those would make a difference, but I have never strayed from the defaults, so I'm unfamiliar with such issues.

**Comment by ghost** [comment]
I changed those locale settings to macedonian values, like to show denar instead of dollar. To make it work I just changed them back to US values

**Comment by josephj11** [comment]
I changed the issue title to reflect the actual problem.
