### ISSUE TITLE
Attempting to delete a script folder whose directory does not exist does nothing.

### ISSUE THREAD

**Issue by Quintovir** [autokey/autokey#534]
## Classification:

UI/Usability

## Reproducibility:

Always

## Version

AutoKey version: 
0.95.10

Used GUI (Gtk, Qt, or both): Gtk

If the problem is known to be present in more than one version, please list all of those.

Installed via: pamac

Linux Distribution: Manjaro Linux

## Summary

When I try to delete script folders that point to non-existent folders in a hard drive nothing happens.

## Steps to Reproduce (if applicable)

Right click on a script folder whose directory does not exist.
Click "yes" to confirm.
Nothing happens.
Click "no".
Nothing happens.
Click the X on the top right corner.
The confirmation window closes.

## Expected Results

Confirming deletion by clicking on "yes" should delete the empty script folder.
Clicking "yes" in the confirmation window should not disable the "no" button to close the confirmation window.

## Actual Results

Confirming deletion by clicking on "yes" visibly shows your click but otherwise does nothing else.
Clicking on "no" after having pressed on "yes" does not close the confirmation window.

Debugging output, obtained by launching autokey via `autokey-gtk --verbose`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autokey/gtkui/configwindow.py", line 1176, in on_delete_item
    self.__removeItem(theModel, item)
  File "/usr/lib/python3.9/site-packages/autokey/gtkui/configwindow.py", line 1200, in __removeItem
    model.remove_item(item)
  File "/usr/lib/python3.9/site-packages/autokey/gtkui/configwindow.py", line 1633, in remove_item
    item.remove_data()
  File "/usr/lib/python3.9/site-packages/autokey/model.py", line 540, in remove_data
    os.rmdir(self.path)
FileNotFoundError: [Errno 2] No such file or directory: '/PATH/TO/NON-EXISTENT/FOLDER'
```

## Notes
I checked if autokey-qt had the same problem.

**Comment by josephj11** [comment]
I'm not an AutoKey developer, but I would guess that the file management is done in autokey-common - independent of which front end is running. I'm pretty sure model.py is in autokey-common. If that's the case, then these two issues are really one issue. See my comments in #533.
