### ISSUE TITLE
new user, expansion not occuring. Downloaded through apt, system: PopOS, i3wm.

### ISSUE THREAD

**Issue by thor314** [autokey/autokey#551]
## Classification:
-> Bug

## Reproducibility:
sudo apt install autokey-qt
write a snippet, add a hotkey and a shortcut to expand
save
try the snippet, fail on both hotkey (alt-shift-p) and shortcut (qqp)

tried also: removing autokey-qt, installing ak-gtk, same issue

->Always

## Version

AutoKey version: 
gtk 0.95.10-1
-> Qt
installed via apt

Linux Distribution:
PopOS, running i3wm on X

**Comment by sebastiansam55** [comment]
Can you post a log? Launch via a terminal (after quitting AutoKey completely) with `autokey-qt -lc`

`-l` for verbose logging and `-c` to show the main AutoKey window.

**Comment by thor314** [comment]
```
autokey-gtk -lc
2021-05-26 15:51:27,276 INFO - root - Initialising application
2021-05-26 15:51:27,282 INFO - root - Initialise global hotkeys
2021-05-26 15:51:27,282 INFO - config-manager - Loading config from existing file: /home/thor/.config/autokey/autokey.json
2021-05-26 15:51:27,283 DEBUG - config-manager - Loading folder at '/home/thor/.config/autokey/data/Sample Scripts'
2021-05-26 15:51:27,285 DEBUG - config-manager - Loading folder at '/home/thor/.config/autokey/data/My Phrases'
2021-05-26 15:51:27,286 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2021-05-26 15:51:27,286 DEBUG - inotify - Adding watch for /home/thor/.config/autokey/data/Sample Scripts
2021-05-26 15:51:27,287 DEBUG - inotify - Adding watch for /home/thor/.config/autokey/data/My Phrases
2021-05-26 15:51:27,287 DEBUG - inotify - Adding watch for /home/thor/.config/autokey/data/My Phrases/Addresses
2021-05-26 15:51:27,287 INFO - config-manager - Successfully loaded configuration
2021-05-26 15:51:27,287 DEBUG - inotify - Adding watch for /home/thor/.config/autokey/data
2021-05-26 15:51:27,287 DEBUG - inotify - Adding watch for /home/thor/.config/autokey
2021-05-26 15:51:27,287 DEBUG - config-manager - Global settings: {'isFirstRun': True, 'serviceRunning': True, 'menuTakesFocus': False, 'showTrayIcon': True, 'sortByUsageCount': True, 'promptToSave': False, 'enableQT4Workaround': False, 'interfaceType': 'XRecord', 'undoUsingBackspace': True, 'windowDefaultSize': [600, 400], 'hPanePosition': 150, 'columnWidths': [150, 50, 100], 'showToolbar': True, 'notificationIcon': 'autokey-status', 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'triggerItemByInitial': False, 'disabledModifiers': [], 'scriptGlobals': {}}
2021-05-26 15:51:27,287 INFO - service - Starting service
2021-05-26 15:51:27,301 DEBUG - interface - Modifier masks: {<Key.SHIFT: '<shift>'>: 1, <Key.CAPSLOCK: '<capslock>'>: 2, <Key.CONTROL: '<ctrl>'>: 4, <Key.ALT: '<alt>'>: 8, <Key.ALT_GR: '<alt_gr>'>: 128, <Key.SUPER: '<super>'>: 64, <Key.HYPER: '<hyper>'>: 64, <Key.META: '<meta>'>: 8, <Key.NUMLOCK: '<numlock>'>: 16}
2021-05-26 15:51:27,321 DEBUG - interface - Alt-Grid: XK_Alt_R, 65514
2021-05-26 15:51:27,321 DEBUG - interface - X Server Keymap, listing unmapped keys.
2021-05-26 15:51:27,322 DEBUG - iomediator - Set modifier Key.CAPSLOCK to False
2021-05-26 15:51:27,322 DEBUG - iomediator - Set modifier Key.NUMLOCK to False
2021-05-26 15:51:27,322 DEBUG - interface - Grabbing hotkey: ['<super>'] 'k'
2021-05-26 15:51:27,322 DEBUG - interface - Grabbing hotkey: ['<shift>', '<super>'] 'k'
2021-05-26 15:51:27,323 DEBUG - interface - Grabbing hotkey: ['<ctrl>'] '<f7>'
2021-05-26 15:51:27,323 DEBUG - interface - __flushEvents: Entering event loop.
2021-05-26 15:51:27,323 INFO - iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1960, sequence_number = 20, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1960, sequence_number = 21, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1960, sequence_number = 22, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1960, sequence_number = 23, major_opcode = 33, minor_opcode = 0
2021-05-26 15:51:27,328 INFO - interface - XRecord interface thread starting
2021-05-26 15:51:27,328 INFO - service - Service now marked as running
2021-05-26 15:51:27,346 DEBUG - phrase-menu - Sorting phrase menu by usage count
2021-05-26 15:51:27,346 DEBUG - phrase-menu - Triggering menu item by position in list
2021-05-26 15:51:27,348 DEBUG - root - Created DBus service
2021-05-26 15:51:27,348 INFO - root - Displaying configuration window
2021-05-26 15:51:27,463 INFO - root - Entering main()

(autokey-gtk:12732): IBUS-WARNING **: 15:51:27.463: Unable to connect to ibus: Could not connect: Connection refused

(autokey-gtk:12732): Gdk-CRITICAL **: 15:51:27.574: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
2021-05-26 15:51:28,330 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/usr/lib/python3/dist-packages/Xlib/xobject/drawable.py", line 455, in get_property
    r = request.GetProperty(display = self.display,
  File "/usr/lib/python3/dist-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3/dist-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x0460010e), sequence_number = 341, major_opcode = 20, minor_opcode = 0
```

**Comment by josephj11** [comment]
The Bad Window error has cropped up in a number of issues over an extended time frame. The only clue I have seen was that it started when someone updated from X11 *19* to *20*. (Don't remember the exact version string.) See also: #475  #368

**Comment by Elliria** [comment]
It looks like you're having an IBus error rather than an AutoKey issue. Did you try restarting IBus? Also, is this still an issue, @thor314?
