### ISSUE TITLE
Deleting all content, then adding a new script crashes or creates exception

### ISSUE THREAD

**Issue by BlueDrink9** [autokey/autokey#583]
## Classification:

crash

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI QT (also applies to GTK, but doesn't cause crash)

Linux Distribution: arch

## Steps to Reproduce (if applicable)

- have scripts and folders in ui (in this case, a lot of them)
- Select all (ctrl-a) and delete (del)
- click "new" button, create new script
- crashes (or in GTK case, just doesn't create a new script but does log an exception)

```
2021-07-19 22:45:01,799 INFO - autokey.qtapp - Initialise global hotkeys
2021-07-19 22:45:01,800 INFO - autokey.configmanager.configmanager - Loading config from existing file: /home/user/.config/autokey/autokey.json
2021-07-19 22:45:01,801 INFO - autokey.configmanager.version_upgrading - Checking if upgrade is needed from version 0.96.0b1
2021-07-19 22:45:02,074 INFO - autokey.configmanager.version_upgrading - Checking if upgrade is needed from version 0.96.0b1
2021-07-19 22:45:02,075 INFO - autokey.configmanager.version_upgrading - Resetting interface type, new type: XRecord
2021-07-19 22:45:02,075 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2021-07-19 22:45:02,081 INFO - autokey.configmanager.configmanager - Persisting configuration
2021-07-19 22:45:02,082 INFO - autokey.configmanager.configmanager - Backing up existing config file
2021-07-19 22:45:02,082 INFO - autokey.configmanager.configmanager - Finished persisting configuration - no errors
2021-07-19 22:45:02,083 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2021-07-19 22:45:02,083 INFO - autokey.configmanager.configmanager - Successfully loaded configuration
2021-07-19 22:45:02,084 INFO - autokey.service - Starting service
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 379, sequence_number = 22, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 379, sequence_number = 23, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 379, sequence_number = 24, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 379, sequence_number = 25, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 379, sequence_number = 26, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 379, sequence_number = 27, major_opcode = 33, minor_opcode = 0
2021-07-19 22:45:02,185 INFO - autokey.iomediator.iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2021-07-19 22:45:02,196 INFO - autokey.interface - XRecord interface thread starting
2021-07-19 22:45:02,196 INFO - autokey.service - Service now marked as running
2021-07-19 22:45:02,205 INFO - autokey.qtui.notifier - Creating static context menu actions.
2021-07-19 22:45:02,207 INFO - autokey.qtui.notifier - Rebuilding model item actions, adding all items marked for access through the tray icon.
2021-07-19 22:45:02,232 INFO - autokey.qtui.notifier - System tray icon notifiercreated.
2021-07-19 22:45:10,251 INFO - autokey.qtapp - Displaying configuration window
qt.svg: link #Nursery is undefined!
qt.svg: link #Nursery is undefined!
qt.svg: link #Nursery is undefined!
qt.svg: link #Nursery is undefined!
qt.svg: link #Nursery is undefined!
qt.svg: link #Nursery is undefined!
qt.svg: link #Nursery is undefined!
2021-07-19 22:45:17,400 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2021-07-19 22:45:17,401 INFO - autokey.qtui.notifier - Rebuilding model item actions, adding all items marked for access through the tray icon.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/autokey/qtui/centralwidget.py", line 285, in on_new_script
    parent_item = tree_widget.selectedItems()[0]  # type: ak_tree.ItemWidgetType
IndexError: list index out of range
Fatal Python error: Aborted

Thread 0x00007f1db560b640 (most recent call first):
  File "/home/user/.local/lib/python3.9/site-packages/pyinotify.py", line 1194 in check_events
  File "/home/user/.local/lib/python3.9/site-packages/autokey/monitor.py", line 125 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap

Thread 0x00007f1db5ffb640 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/queue.py", line 171 in get
  File "/home/user/.local/lib/python3.9/site-packages/autokey/iomediator/iomediator.py", line 120 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap

Thread 0x00007f1db67fc640 (most recent call first):
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/display.py", line 561 in send_and_recv
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/rq.py", line 1381 in reply
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/rq.py", line 1369 in __init__
  File "/usr/lib/python3.9/site-packages/Xlib/ext/record.py", line 220 in __init__
  File "/usr/lib/python3.9/site-packages/Xlib/ext/record.py", line 239 in enable_context
  File "/home/user/.local/lib/python3.9/site-packages/autokey/interface.py", line 1273 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap

Thread 0x00007f1db6ffd640 (most recent call first):
  File "/home/user/.local/lib/python3.9/site-packages/autokey/interface.py", line 970 in __flushEvents
  File "/usr/lib/python3.9/threading.py", line 892 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap

Thread 0x00007f1db77fe640 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/queue.py", line 171 in get
  File "/home/user/.local/lib/python3.9/site-packages/autokey/interface.py", line 239 in __eventLoop
  File "/usr/lib/python3.9/threading.py", line 892 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap

Current thread 0x00007f1dcb283740 (most recent call first):
  File "/home/user/.local/lib/python3.9/site-packages/autokey/qtapp.py", line154 in __init__
  File "/home/user/.local/bin/autokey-qt", line 8 in <module>
```

**Comment by BlueDrink9** [comment]
Creating a new folder works fine, but doesn't fix the issue.

**Comment by BlueDrink9** [comment]
GTK has a similar issue, although pressing delete with all phrases selected doesn't delete them. GTK doesn't crash, however. It just logs and error and doesn't create the phrase.
```
Traceback (most recent call last):
  File "/home/user/src/autokey/lib/autokey/interface.py", line 167, in __eventLoop
    method(*args)
  File "/home/user/src/autokey/lib/autokey/interface.py", line 374, in __grabHotkeysForWindow
    elif self.__needsMutterWorkaround(item):
  File "/home/user/src/autokey/lib/autokey/interface.py", line 265, in __needsMutterWorkaround
    if Key.SUPER not in item.modifiers:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/user/src/autokey/lib/autokey/gtkui/configwindow.py", line 1097, in on_new_phrase
    parentIter = self.__getRealParent(theModel[selectedPaths[0]].iter)
IndexError: list index out of range
```

**Comment by BlueDrink9** [comment]
Occurs with new subfolder and script as well

**Comment by BlueDrink9** [comment]
Oh, actually this occurs on master as well. That means no-one has complained about it out of all of our users.
Having a look around, it seems very ui-focussed, which I know nothing about.
Given those two things, I am going to stop working on it.
