### ISSUE TITLE
Changing an autokey file while autokey gui is open on another x desktop causes crash

### ISSUE THREAD

**Issue by BlueDrink9** [autokey/autokey#601]
## Classification:

Crash

## Reproducibility:

Always

## Version

AutoKey version: develop 9dec16f7b86ad012bd95dca517e71eab20daa561

Used GUI GTK (QT verified not to be affected)

Installed via: git

Linux Distribution: Arch (bspwm)

## Summary

Summary of the problem.

## Steps to Reproduce (if applicable)

1. Open autokey-gtk gui
2. Switch to another workspace/virtual desktop
3. Edit an autokey .json file in an external editor, while gui isn't visible but is open on the other window

## Expected Results

Autokey gui reloads data in the background

## Actual Results

Autokey crashes

```
2021-08-29 12:40:54,152 WARNING - autokey.configmanager.configmanager - No action taken for create/update event at /home/user/.config/autokey/data/abc/4913
2021-08-29 12:40:54,153 DEBUG - autokey.monitor - Reporting IN_DELETE event at /home/user/.config/autokey/data/abc/4913
2021-08-29 12:40:54,654 WARNING - autokey.configmanager.configmanager - No action taken for delete event at /home/user/.config/autokey/data/abc/4913
2021-08-29 12:40:54,655 DEBUG - autokey.monitor - Reporting IN_MOVED_FROM event at /home/user/.config/autokey/data/abc/folder.json
2021-08-29 12:40:54,724 DEBUG - autokey.iomediator.iomediator - Key.SUPER pressed
2021-08-29 12:40:55,156 WARNING - autokey.configmanager.configmanager - No action taken for delete event at /home/user/.config/autokey/data/abc/folder.json
2021-08-29 12:40:55,156 DEBUG - autokey.monitor - Reporting IN_CREATE event at /home/user/.config/autokey/data/abc/folder.json
2021-08-29 12:40:55,264 DEBUG - autokey.iomediator.iomediator - Key.SUPER released
2021-08-29 12:40:55,658 ERROR - autokey.model.folder - Error while loading json data for abcd
Traceback (most recent call last):
  File "/home/user/src/autokey/lib/autokey/model/folder.py", line 124, in load_from_serialized
    self.inject_json_data(data)
  File "/home/user/src/autokey/lib/autokey/model/folder.py", line 137, in inject_json_data
    AbstractHotkey.load_from_serialized(self, data["hotkey"])
  File "/home/user/src/autokey/lib/autokey/model/abstract_hotkey.py", line 38, in load_from_serialized
    self.set_hotkey(data["modifiers"], data["hotKey"])
  File "/home/user/src/autokey/lib/autokey/model/abstract_hotkey.py", line 45, in set_hotkey
    modifiers.sort()
AttributeError: 'NoneType' object has no attribute 'sort'
2021-08-29 12:40:55,659 ERROR - autokey.model.folder - JSON data not loaded (or loaded incomplete)
2021-08-29 12:40:55,660 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2021-08-29 12:40:55,661 INFO - autokey.gtkui.configwindow - Modifications detected to open files. Reloading...
/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py:1425: Warning: instance of invalid non-instantiatable type '<invalid>'
  super(TreeSelection, self).select_path(path)
/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py:1425: Warning: g_signal_emit_valist: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  super(TreeSelection, self).select_path(path)
2021-08-29 12:40:55,669 DEBUG - autokey.gtkui.dialogs - Loaded item folder 'My Phrases', key: <f7>, modifiers: ['<ctrl>']
2021-08-29 12:40:55,670 DEBUG - autokey.monitor - Reporting IN_MODIFY event at /home/user/.config/autokey/data/abc/folder.json
2021-08-29 12:40:56,171 ERROR - autokey.model.folder - Error while loading json data for abcd
Traceback (most recent call last):
  File "/home/user/src/autokey/lib/autokey/model/folder.py", line 124, in load_from_serialized
    self.inject_json_data(data)
  File "/home/user/src/autokey/lib/autokey/model/folder.py", line 137, in inject_json_data
    AbstractHotkey.load_from_serialized(self, data["hotkey"])
  File "/home/user/src/autokey/lib/autokey/model/abstract_hotkey.py", line 38, in load_from_serialized
    self.set_hotkey(data["modifiers"], data["hotKey"])
  File "/home/user/src/autokey/lib/autokey/model/abstract_hotkey.py", line 45, in set_hotkey
    modifiers.sort()
AttributeError: 'NoneType' object has no attribute 'sort'
2021-08-29 12:40:56,172 ERROR - autokey.model.folder - JSON data not loaded (or loaded incomplete)
2021-08-29 12:40:56,173 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2021-08-29 12:40:56,174 INFO - autokey.gtkui.configwindow - Modifications detected to open files. Reloading...
Fatal Python error: Segmentation fault

Current thread 0x00007f9d8cff9640 (most recent call first):
  File "/home/user/src/autokey/lib/autokey/gtkui/configwindow.py", line 1432 in on_tree_selection_changed
  File "/home/user/src/autokey/lib/autokey/gtkui/configwindow.py", line 965 in rebuild_tree
  File "/home/user/src/autokey/lib/autokey/gtkui/configwindow.py", line 907 in config_modified
  File "/home/user/src/autokey/lib/autokey/UI_common_functions.py", line 167 in path_created_or_modified
  File "/home/user/src/autokey/lib/autokey/gtkapp.py", line 144 in path_created_or_modified
  File "/home/user/src/autokey/lib/autokey/monitor.py", line 59 in process_IN_MODIFY
  File "/home/user/.local/lib/python3.9/site-packages/pyinotify.py", line 630 in __call__
  File "/home/user/.local/lib/python3.9/site-packages/pyinotify.py", line 910 in __call__
  File "/home/user/.local/lib/python3.9/site-packages/pyinotify.py", line 1273 in process_events
  File "/home/user/src/autokey/lib/autokey/monitor.py", line 124 in run
  File "/usr/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f9d8e7fc640 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/queue.py", line 171 in get
  File "/home/user/src/autokey/lib/autokey/iomediator/iomediator.py", line 120 in run
  File "/usr/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f9d8effd640 (most recent call first):
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/display.py", line 561 in send_and_recv
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/rq.py", line 1381 in reply
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/rq.py", line 1369 in __init__
  File "/usr/lib/python3.9/site-packages/Xlib/ext/record.py", line 220 in __init__
  File "/usr/lib/python3.9/site-packages/Xlib/ext/record.py", line 239 in enable_context
  File "/home/user/src/autokey/lib/autokey/interface.py", line 1273 in run
  File "/usr/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f9d8f7fe640 (most recent call first):
  File "/home/user/src/autokey/lib/autokey/interface.py", line 970 in __flushEvents
  File "/usr/lib/python3.9/threading.py", line 910 in run
  File "/usr/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f9d8ffff640 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/queue.py", line 171 in get
  File "/home/user/src/autokey/lib/autokey/interface.py", line 239 in __eventLoop
  File "/usr/lib/python3.9/threading.py", line 910 in run
  File "/usr/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f9d98455740 (most recent call first):
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 1680 in main
  File "/home/user/src/autokey/lib/autokey/gtkapp.py", line 230 in main
  File "/home/user/src/autokey/lib/autokey/gtkui/__main__.py", line 9 in main
  File "/home/user/.local/bin/autokey-gtk", line 33 in <module>
zsh: segmentation fault (core dumped)  autokey-gtk -c --verbose
```

**Comment by BlueDrink9** [comment]
@sebastiansam55 might be easier for you to look into this than me, since you wrote the update code

**Comment by BlueDrink9** [comment]
Also an important note about the log: These errors `AttributeError: 'NoneType' object has no attribute 'sort'
2021-08-29 12:40:56,172 ERROR - autokey.model.folder - JSON data not loaded (or loaded incomplete)` appear when reloading on the same window too, without crash. So they are not the errors relating directly to this crash

**Comment by BlueDrink9** [comment]
Beta is also affected, so we want this fixed soon. Seems to only happen if the thing you are changing is visible in the gui though.

**Comment by BlueDrink9** [comment]
@sebastiansam55 if you have time, I would appreciate you taking a look at this
