### ISSUE TITLE
fails to find .desktop file to create autostart .desktop (autokey should search `$XDG_DATA_DIRS`)

### ISSUE THREAD

**Issue by podiki** [autokey/autokey#609]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): GTK (but shouldn't depend on GUI)

If the problem is known to be present in more than one version, please list all of those.

Installed via: self-packaged (built from source)

Linux Distribution: GNU Guix

## Summary

When autokey(-gtk) looks to create the autostart .desktop file, it looks to find the application desktop file, but only in some set locations (`/usr/share/applications` besides `$XDG_DATA_HOME`). Rather it should look in `$XDG_DATA_DIRS` for application desktop files to be more general. For example, this fails in distros like GNU Guix which do not use `/usr/share/applications`, but do properly set `$XDG_DATA_DIRS` as search paths for things like .desktop files.

## Steps to Reproduce (if applicable)

- Try to enable autostart in the settings dialog

## Expected Results

- The .desktop file should be found and an autostart entry created

## Actual Results

- Instead, this happens. :(
- output:

```
2021-09-07 12:18:17,567 INFO - config-manager - Save autostart settings: AutostartSettings(desktop_file_name='autokey-gtk.desktop', switch_show_configure=False)
2021-09-07 12:18:17,568 ERROR - config-manager - Failed to find a usable .desktop file! Unable to find: autokey-gtk.desktop
Traceback (most recent call last):
  File "/gnu/store/khp...-python-autokey-0.95.10/lib/python3.8/site-packages/autokey/configmanager.py", line 209, in _create_autostart_entry
    source_desktop_file = get_source_desktop_file(autostart_data.desktop_file_name)
  File "/gnu/store/khp...-python-autokey-0.95.10/lib/python3.8/site-packages/autokey/configmanager.py", line 251, in get_source_desktop_file
    raise FileNotFoundError("Desktop file for autokey could not be found. Searched paths: {}".format(possible_paths))
FileNotFoundError: Desktop file for autokey could not be found. Searched paths: (PosixPath('/home/podiki/.local/share/applications'), PosixPath('/usr/share/applications'), PosixPath('/gnu/store/khp...-python-autokey-0.95.10/lib/python3.8/config'))
```

But, `autokey-gtk.desktop` is found in `$XDG_DATA_DIRS` (in this case in a profile directory, this is a Guix thing, but autokey should use XDG specs). This can be verified through using launchers like rofi, or with xdg tools.

## Notes

I have not tried to patch this, but the relevant code is at https://github.com/autokey/autokey/blob/4b87b32452cd41d2b98341db220e99cf4f9e34d6/lib/autokey/configmanager.py#L234 Here, autokey should search `$XDG_DATA_DIRS` for the autokey .desktop file.

**Comment by BlueDrink9** [comment]
You're right, it should respect that. Maintainer time is quite stretched, so if you are willing to submit a PR against the `develop` branch, it would be greatly appreciated

**Comment by podiki** [comment]
No worries! Should be a quick fix, I'll try to take a look myself soon.

**Comment by BlueDrink9** [comment]
@podiki did you have a chance to look at this?

**Comment by podiki** [comment]
Sorry, did not yet! But actually I was just looking, and I think it'll just be a few lines: `os.getnev('XDG_DATA_DIRS')` and `os.path.pathsep` (or use the default dirs if not set), and look for the desktop file in those paths with '/applications'. I can try it out and submit something in the next few days.

**Comment by podiki** [comment]
Hi @BlueDrink9. Here is a short code snippet that should do the trick. I wasn't sure of the exact style and what we want to do, but I think adding a variable `common.XDG_DATA_DIRS` (like what is there for `XDG_DATA_HOME`), where if it is `None` to set to what the XDG default is `usr/local/share/:/usr/share/`. So this at least will produce a list of directories to search:

```
import os
from pathlib import Path

path = os.getenv('XDG_DATA_DIRS')

paths = [os.path.join(p, "applications")
         for p in path.split(os.path.pathsep)]
```

**Comment by josephj11** [comment]
This looks like an easy fix. I'm going to add  labels for that, but I will remove them if anyone objects.

**Comment by josephj11** [comment]
@podiki Are you still using GNU Guix? I'd be interested in hearing about how that works for you. I just looked it up and it's quite different from what I'm used to. If you want to reply, it would probably be better to do so on [Gitter](https://gitter.im/autokey/autokey) so as not to clog up this issue.
