### ISSUE TITLE
Fatal error starting Autokey. 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by jcassee** [autokey/autokey#61]
Classification: Bug

Reproducibility: Always

## Summary

Since this morning, starting autokey-py shows an error dialog and exits:

```
Fatal error starting AutoKey.
'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte
```

## Steps to Reproduce

1. Start autokey-py3.

## Expected Results

Autokey should start. :-)

## Actual Results

Apart from the error dialog, this is the output with `--verbose`:

```
$ autokey-gtk --verbose
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
2017-01-12 00:40:30,776 ERROR - root - Fatal error starting AutoKey: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/gtkapp.py", line 77, in __init__
    if self.__verifyNotRunning():
  File "/usr/lib/python3/dist-packages/autokey/gtkapp.py", line 95, in __verifyNotRunning
    with open(LOCK_FILE, 'r') as f: pid = f.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte
```

## Version

AutoKey-Py3 version 0.93.9-1 from the Ubuntu PPA. The master branch ( commit c0f5af1217589d970ef028c243f8bdd5fc9c111d) has the same problem.

Installed via: 0.93.9-1 from PPA, master branch using `python3 setup.py install`.

Distro: Ubuntu 16.04.

**Comment by troxor** [comment]
Strange, I can't reproduce this on my VM using the PPA package. Can you paste the output of 
`P=$HOME/.config/autokey/autokey.pid ; cat $P ; echo ; file $P; file -i $P; od -x $P; locale` please?

Here is what I see (obviously the PID will differ...) : 

```
23003
/home/trox/.config/autokey/autokey.pid: ASCII text, with no line terminators
/home/trox/.config/autokey/autokey.pid: text/plain; charset=us-ascii
0000000 3332 3030 0033
0000005
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
If everything else looks fine, can you try completely removing anything related to autokey from your system, and reinstalling fresh?

**Comment by jcassee** [comment]
The output is:

```
AH��
/home/joost/.config/autokey/autokey.pid: Non-ISO extended-ASCII text, with no line terminators
/home/joost/.config/autokey/autokey.pid: text/plain; charset=unknown-8bit
0000000 4841 9e9b
0000004
LANG=nl_NL.UTF-8
LANGUAGE=nl:en_GB:en
LC_CTYPE="nl_NL.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_COLLATE="nl_NL.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="nl_NL.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=
```

Those first characters look suspicious. I removed `~/.config/autokey/autokey.pid` and everything works again. I guess the pidfile got corrupted.

Thanks for your help!
