### ISSUE TITLE
Unable to register Hotkey on Fedora

### ISSUE THREAD

**Issue by tnguyen14** [autokey/autokey#630]
## Classification:
Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): both

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …). `dnf install autokey-gtk`

Linux Distribution: Fedora 35

## Summary

Summary of the problem.

## Steps to Reproduce (if applicable)

I created a phrase, and then under "Hot key", I clicked on "Set". In the "Set HotKey" popup window, I clicked "Press to Set" and it says "Press a key...". I pressed the key that I want to set on the keyboard. In fact, I tried most of the keys on the keyboard.

## Expected Results

A key is registered

## Actual Results

No key is being registered

## Logs

```
2021-11-13 18:00:49,677 INFO - root - Displaying configuration window
2021-11-13 18:01:01,454 ERROR - interface - Error in X event loop thread
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/autokey/interface.py", line 242, in __eventLoop
    method(*args)
  File "/usr/lib/python3.10/site-packages/autokey/interface.py", line 674, in __grab_keyboard
    focus.grab_keyboard(True, X.GrabModeAsync, X.GrabModeAsync, X.CurrentTime)
AttributeError: 'int' object has no attribute 'grab_keyboard'

```

**Comment by tnguyen14** [comment]
Based on this comment https://github.com/autokey/autokey/issues/293#issuecomment-581217014, I tried to switch to XOrg instead using this guide https://docs.fedoraproject.org/en-US/quick-docs/configuring-xorg-as-default-gnome-session/.

It seems to be working in X11.
