### ISSUE TITLE
AutoKey crashes when script errors and notification icon off

### ISSUE THREAD

**Issue by gingershaped** [autokey/autokey#634]
## Classification:
(Pick one: Bug, Crash/Hang/Data loss, Enhancement, Feature (new), Performance, UI/Usability)
Crash

## Reproducibility:
(Pick one: Always, Sometimes, Rarely, Unable, I didn't try)
Always

## AutoKey version:
(Paste in your AutoKey version and, if the problem is known to be present in more than one version, please list them all.)
0.95.10

## Used GUI:
(Pick one: Gtk, Qt, Both):
Gtk

## Installed via:
(Pick one: PPA, pip3, Git, package manager, etc.)
appt

## Linux distribution:
(Provide information about your Linux distribution and its release or version number.)
Raspberry Pi OS (formally Raspbian) Bullseye (upgraded from Buster in-place)

## Summary:
When running an AutoKey script, if the script encounters an error (and the system tray icon is deactivated) AutoKey will crash.

## Steps to reproduce:
- Write an AutoKey script that causes a Python exception
- Deactivate the system tray icon in Preferences
- Run the script

## Expected result:
The error notification should pop up

## Actual result:
The error notification pops up and AutoKey immediately crashes

## Screenshot (if applicable):
(Include one or more screenshots of the issue by dragging the image file(s) here to help with debugging.)

## Verbose output (if applicable):
(Include the output from launching AutoKey via the `autokey-gtk --verbose` or `autokey-qt --verbose` command to help with debugging. Please upload the output somewhere accessible or paste it into a code block here, enclosing it in triple backticks.)
```
2021-11-24 15:21:45,469 DEBUG - service - Script runner executing: Script('crasher')
2021-11-24 15:21:45,470 ERROR - service - Script error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 485, in execute
    exec(script.code, scope)
  File "<string>", line 1, in <module>
NameError: name 'wefuivrgynwjkvljehwuiovmwjnevbwejkv' is not defined
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
python3: ../../src/xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Fatal Python error: Aborted

Current thread 0xAborted

```

## Notes:
This only seems to happen after AutoKey is restarted with the system tray icon off.

**Comment by BlueDrink9** [comment]
Unable to reproduce on beta 9 or .95.10. This might be related to multi-threading, which will make it hard to reproduce. Does this happen to you every time?

**Comment by gingershaped** [comment]
@BlueDrink9  Yes, it does.

**Comment by BlueDrink9** [comment]
Curious. Perhaps it doesn't affect me on Plasma. I would like others to chime in. Are you running Rasbian? What is your desktop environment?

**Comment by Elliria** [comment]
I can't reproduce it here, either, with the beta in a virtual machine with these specifications:
* Autokey version: autokey-gtk 0.96.0-beta.9
* Installed via: pip3
* Linux distribution: Kubuntu 20.04 LTS running inside of VirtualBox
* KDE Plasma Version 5.18.5
* KDE Frameworks Version: 5.68.0
* Qt Version: 5.12.8
* Kernel Version: 5.11.0-40-generic
* OS Type: 64-bit
* Memory: 3.2 GiB of RAM
* Processor: 1 x Intel Core i5-8600K CPU @ 3.60 GHz

I get a name error, but have full use of AutoKey. Interestingly, although the notification icon is disabled during this test, as soon as the error is encountered, the notification icon appears so that you can right-click it and view the script error. Once you've done that, it goes away again. That's a thoughtful feature.

**Comment by BlueDrink9** [comment]
I wonder if it is an old library bug somewhere? I see you aren't running rasbian anymore, sorry for misreading that. Knowing the DE would help, and getting a VM with the same OS would be useful to reproduce it (but I dont' have time to set that up myself)

**Comment by josephj11** [comment]
This looks like it might be an OS/distro-specific problem (upstream of AutoKey). If it's still a problem, someone will have to recreate it on an R Pi or in a suitable VM.

@GingerIndustries Is this still a problem for you... ?

**Comment by gingershaped** [comment]
It's been over a year since I initially encountered this bug, and since then I have both ceased using AutoKey and the environment on my Pi has changed significantly. I'd love to help with this issue, but unfortunately I no longer remember the steps I followed to install AutoKey, and I will therefore probably not be able to reproduce it. Nonetheless, I will try installing AutoKey again and seeing if the error occurs at some point soon.
