### ISSUE TITLE
AttributeError when trying to set hotkey

### ISSUE THREAD

**Issue by sdanil-ops** [autokey/autokey#646]
## Classification:
Bug

## Reproducibility:
Allways

## AutoKey version:
0.95.10-4

## Used GUI:
gtk

## Installed via:
yay

## Linux distribution:
5.15.7-1-MANJARO #1 SMP PREEMPT Wed Dec 8 10:09:19 UTC 2021 x86_64 GNU/Linux

## Summary:

Hi! Getting AttributeError when trying to set hotkey

## Steps to reproduce:
-Set HotKey

## Expected result:
Hotkey sets 

## Actual result:
Nothing but AttributeError

## Verbose output (if applicable):
```
2022-01-02 14:35:02,912 ERROR - interface - Error in X event loop thread
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autokey/interface.py", line 242, in __eventLoop
    method(*args)
  File "/usr/lib/python3.9/site-packages/autokey/interface.py", line 674, in __grab_keyboard
    focus.grab_keyboard(True, X.GrabModeAsync, X.GrabModeAsync, X.CurrentTime)
AttributeError: 'int' object has no attribute 'grab_keyboard'
```

**Comment by Elliria** [comment]
Interesting. A couple of questions:
- Does it happen with one specific hotkey or any hotkey you try to set?
- Does it happen on all of your scripts or just one?

**Comment by josephj11** [comment]
A few more questions:
- Did this work for you before or is this a new install?
- If it worked before, what has changed/been updated since then.

Note: I didn't immediately find the focus module in our source code. Is it possible that its calling sequence has changed in a new version of an external package? Manjaro (Arch) gets bleeding edge updates.

- While we are investigating this..., is it possible to use the Qt version instead?

   On Arch, the two versions of AutoKey (GTK and Qt) are packaged separately, so this may require some extra effort to test. If you have any scripts and phrases already defined, be sure to make a backup of $HOME/.config/autokey (including hidden files) before doing any package management.

**Comment by mikemp7** [comment]
I had this happening to me with `/usr/lib/python3/dist-packages/autokey/gtkui/dialogs.py`

This is what I did to fix it 
Replace `text = model.get_value(i.next().iter, 0)` with `text = model.get_value(next(i).iter, 0)` 

`i.next()` is Python 2 syntax.

**Comment by Elliria** [comment]
Excellent find! It's added to the list of things to do once we can edit the code again.

**Comment by josephj11** [comment]
@Elliria Is that a personal list or is in here somewhere like in a discussion thread?

**Comment by Elliria** [comment]
It's a list in my personal wiki that has fifty-some-odd things in it so far that are either partially done or need to be done.

**Comment by josephj11** [comment]
Might be nice to put some of that where others can find it if you're not around.

**Comment by Elliria** [comment]
I did, once upon a time. A long while back, I created a GitHub repository for tracking tasks and populated it with an issue for each of my tasks.

That was problematic because when I linked to [AutoKey issues](https://github.com/autokey/autokey/issues) or [AutoKey discussions](https://github.com/autokey/autokey/discussions) in my tasks (which was necessary for completing them), GitHub recognized that I had done that and automatically included a back-link to my issues in the comments of their related AutoKey issues or AutoKey discussions.

This caused confusion in the AutoKey repository, so I was asked to find a different way to track my tasks. As a result, I moved them into my personal wiki, which is where they've lived ever since.

I haven't invented any tasks that don't already exist somewhere as AutoKey issues, as AutoKey discussions, as suggestions posted by users in comments under either of those, or as sample code posted by users in comments under either of those. This is just my personal collection derived from all of those sources.

**Comment by Elliria** [comment]
Related issues:
* [issue #1048](https://github.com/autokey/autokey/issues/1048)
* [issue #1059](https://github.com/autokey/autokey/issues/1059)
* [issue #974](https://github.com/autokey/autokey/issues/974)
* [issue #1013](https://github.com/autokey/autokey/issues/1013)

**Comment by Elliria** [comment]
Closing this issue manually since the issue has been resolved in pull request #1076.
