### ISSUE TITLE
autokey-run error on Arch Linux

### ISSUE THREAD

**Issue by MrOats** [autokey/autokey#65]
Classification: Bug

Reproducibility: Always

## Summary

autokey-run fails to run a script with error down below.

## Steps to Reproduce

`autokey-run -s myscript.py`

## Expected Results

Run the script

## Actual Results

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.autokey.Service': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/autokey-run", line 39, in <module>
    dbusService = bus.get_object("org.autokey.Service", "/AppService")
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.autokey.Service was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/autokey-run", line 50, in <module>
    print >>sys.stderr, str(e)
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
```

If helpful, submit screenshots of the issue to help debug. `autokey-gtk --verbose` output is also useful.

## Version

AutoKey-Py3 version: 0.93.9-2

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip, …): AUR via Pacman

Distro: Arch Linux, up-to-date

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, provide it here.

**Comment by troxor** [comment]
Autokey needs to be present on the dbus first. Running 'autokey-gtk', then `autokey-run -s issue8` (where issue8.py exists in my autokey scripts directory works fine. The error message has been fixed and clarified.
