### ISSUE TITLE
window.get_active_title() throws error

### ISSUE THREAD

**Issue by kreezxil** [autokey/autokey#697]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Which Linux distribution did you use?

Operating System: Manjaro Linux
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.94.0
Qt Version: 5.15.4
Kernel Version: 5.15.41-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor
Memory: 23.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2

### Which AutoKey GUI did you use?

Qt

### Which AutoKey version did you use?

0.96.0-beta.5

### How did you install AutoKey?

pip

### Can you briefly describe the issue?

Calling this statement causes AutoKey to crash and require a full restart, it happens randomly.

```
targetScan = window.get_active_title()
```
- Autokey: 0.96.0-beta.5
- Python: 3.10.4

It used to work reliably I think on an older version of Python. If I figure it out, I'll update this.

This is nearly identical to [https://stackoverflow.com/questions/72324058/autokey-sporadic-error-on-system-exec-command][1], but with Python3.10. I was getting it rather frequently but discovered I had a Windows Python module installed, removed that, and now I'm down to 1 out 3 times it will fail me. I wonder if there is a way to scan the Python modules to find out which ones belong to a type of operating system; for example, windows only.

Also my output in case someone wants to help us out

```
2022-05-26 10:40:59,608 ERROR - autokey.service - Script error
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/autokey/service.py", line 530, in _execute
    exec(compiled_code, scope)
  File "/home/kreezxil/.config/autokey/data/_work/curseforge/projects/mymods.py", line 22, in <module>
    targetScan = window.get_active_title()
  File "/usr/lib/python3.10/site-packages/autokey/scripting/window.py", line 230, in get_active_title
    return self.mediator.interface.get_window_title()
  File "/usr/lib/python3.10/site-packages/autokey/interface.py", line 1225, in get_window_title
    return self.get_window_info(window, traverse).wm_title
  File "/usr/lib/python3.10/site-packages/autokey/interface.py", line 1141, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3.10/site-packages/autokey/interface.py", line 1147, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3.10/site-packages/autokey/interface.py", line 1197, in _try_get_window_title
    atom = self._try_read_property(window, self.__NameAtom)
  File "/usr/lib/python3.10/site-packages/autokey/interface.py", line 1212, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/home/kreezxil/.local/lib/python3.10/site-packages/Xlib/xobject/drawable.py", line 435, in get_property
    r = request.GetProperty(display = self.display,
  File "/home/kreezxil/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1481, in __init__
    self.reply()
  File "/home/kreezxil/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1493, in reply
    self._display.send_and_recv(request = self._serial)
  File "/home/kreezxil/.local/lib/python3.10/site-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/home/kreezxil/.local/lib/python3.10/site-packages/Xlib/protocol/display.py", line 643, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/home/kreezxil/.local/lib/python3.10/site-packages/Xlib/protocol/display.py", line 726, in parse_request_response
    raise RuntimeError("Expected reply for request %s, but got %s.  Can't happen!"
RuntimeError: Expected reply for request 617, but got 616.  Can't happen!

```

  [1]: https://stackoverflow.com/questions/72324058/autokey-sporadic-error-on-system-exec-command

### What are the steps to reproduce the issue?

use
```
var_name = window.get_active_title()
```

### What should have happened?

not crash

### What actually happened?

crash

### Do you have screenshots?

no

### Can you provide the output of the AutoKey command?

```bash
took a while to get it, suddenly everything started working for about 40 minutes and then without warning wham. kind of big so i zipped it and put it on my cloud drive. https://drive.google.com/file/d/1tMoLva-cYuBsTUAoP-wjc1hPJzTV3VHt/view?usp=drivesdk
```

**Comment by josephj11** [comment]
I know Arch/Manjaro makes it difficult to install the other front end, but can you use autokey-gtk as a workaround until this gets fixed?

The error message suggests that there may be a race condition or some similar timing concern that is getting events misaligned. That might explain why it's intermittent. It might depend on other system load factors.

**Comment by ineuw** [comment]
```
# [ win + ins ] insert current date, time, and filename 2022-05-12 04:27 - AutoKey

import datetime

paste_ = "<ctrl>+v"
activetitle_ = window.get_active_title()
ts_ = time.time()
timestamp_ = datetime.datetime.fromtimestamp(ts_).strftime('%Y-%m-%d %H:%M')
combined_ = '# ' + timestamp_ + " - " + activetitle_
clipboard.fill_clipboard(combined_)

time.sleep(0.1)
keyboard.send_keys(paste_)
```

I may have posted this somewhere here earlier, but I use this without a problem for years with autokey-gtk

**Comment by kreezxil** [comment]
I'll try but I feel i might be sending in more bug reports.

**Comment by ineuw** [comment]
Feeling is an invalid parameter. :-) Just test it.
```
# 2022-05-27 16:12 - window.get_active_title() throws error · Issue #697 · autokey/autokey — Mozilla Firefox
```
This is the output when activated in this text box, while writing this post.

**Comment by Elliria** [comment]
I tried the code at the top of this issue with AutoKey Qt version 0.95.10 from the Ubuntu repositories in this environment:
* Operating System: Kubuntu 22.04
* KDE Plasma Version: 5.24.4
* KDE Frameworks Version: 5.92.0
* Qt Version: 5.15.3
* Kernel Version: 5.15.0-33-generic (64-bit)
* Graphics Platform: X11

I ran it many times without being able to duplicate the issue, but I see that your test was done with the beta. It's possible something has changed between those the version I'm using and the beta. Also, there are some differences in our environments, any of which might play a part.

**Comment by kreezxil** [comment]
I meant that I would be sending in bug reports such as I did the last time that I used AUTOKEY-GTK on KDE. Such as this bug which still isn't fixed.

When triggering a drop down, while you can use the arrows to select an item. Pressing the return/enter key does not autopress the OK button for you, you have to click "ok" with the mouse.

![image](https://user-images.githubusercontent.com/3880072/170867304-757a1918-b499-4e16-97b6-c5cbd193a4a2.png)

https://github.com/autokey/autokey/issues/374 which is partially fixed now because the arrow keys now work.

**Comment by kreezxil** [comment]
I've got a temporary work around:
```python
def get_active_title():
    return system.exec_command('xdotool getactivewindow getwindowname', getOutput=True)
```

Note this predicate upon having the xdotool, which I want to say that most Linux systems with a windowing system should have.
