### ISSUE TITLE
Traceback Crash

### ISSUE THREAD

**Issue by GabenCrying** [autokey/autokey#701]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Crash/Hang/Data loss

### Which Linux distribution did you use?

Linux arch 5.18.3-arch1-1

### Which AutoKey GUI did you use?

Both

### Which AutoKey version did you use?

https://aur.archlinux.org/packages/autokey-gtk
and
https://aur.archlinux.org/packages/autokey-qt

### How did you install AutoKey?

AUR

### Can you briefly describe the issue?

Running either GTK or QT crashes w/ traceback

### What are the steps to reproduce the issue?

1. Run autokey-gtk/qt

### What should have happened?

It runs?

### What actually happened?

It crashes w/ traceback

### Can you provide the output of the AutoKey command?

```bash
[shane@arch yay]$ autokey-qt
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 5, in <module>
    from autokey.qtui.__main__ import Application
  File "/usr/lib/python3.10/site-packages/autokey/qtui/__main__.py", line 23, in <module>
    from autokey.qtapp import Application
  File "/usr/lib/python3.10/site-packages/autokey/qtapp.py", line 35, in <module>
    from autokey import service, monitor
  File "/usr/lib/python3.10/site-packages/autokey/service.py", line 33, in <module>
    from autokey.iomediator.iomediator import IoMediator
  File "/usr/lib/python3.10/site-packages/autokey/iomediator/iomediator.py", line 19, in <module>
    from autokey.configmanager.configmanager import ConfigManager
  File "/usr/lib/python3.10/site-packages/autokey/configmanager/configmanager.py", line 41, in <module>
    import autokey.configmanager.version_upgrading as version_upgrade
  File "/usr/lib/python3.10/site-packages/autokey/configmanager/version_upgrading.py", line 41, in <module>
    from packaging.version import parse as vparse
ModuleNotFoundError: No module named 'packaging'



Same error on both GTK and QT
```

### Anything else?

installing pip3, upgrading, and running
 pip3 install packaging
 fixed it

**Comment by Elliria** [comment]
I'm glad you got it working. If you're still monitoring this issue report, @GabenCrying,  you might want to contact the AutoKey maintainer in your distribution and give him or her a link to this page so the informatioon in your traceback can be used to make those packages work.

**Comment by josephj11** [comment]
Yes. There was a bunch of refactoring of code for 0.96.0 and I recall seeing something about putting some code in some sort of a container. This definitely _looks_ like a packaging problem. If it is, it will affect all our Arch and Manjaro users, so it needs to be looked at.
I am reopening this with an upstream tag - which is the closest one for this issue.
