### ISSUE TITLE
Running "pip install ." does not install all requirements in fresh ubuntu 22.04.2 environment (xorg session)

### ISSUE THREAD

**Issue by sebastiansam55** [autokey/autokey#816]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [X] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [X] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [X] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Ubuntu 22.04.2

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.96.0

### How did you install AutoKey?

pip

### Can you briefly describe the issue?

Seems like the switch to AyatanaAppIndicator3 did not make it to the config files

### Can the issue be reproduced?

Always

### Can you provide the output of the AutoKey command?

```bash
sam@autokeytest ~/autokey (master)> autokey-gtk
Traceback (most recent call last):
  File "/home/sam/.local/lib/python3.10/site-packages/autokey/gtkui/notifier.py", line 29, in <module>
    gi.require_version('AyatanaAppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sam/.local/bin/autokey-gtk", line 5, in <module>
    from autokey.gtkui.__main__ import main
  File "/home/sam/.local/lib/python3.10/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/sam/.local/lib/python3.10/site-packages/autokey/gtkapp.py", line 40, in <module>
    from autokey.gtkui.notifier import get_notifier
  File "/home/sam/.local/lib/python3.10/site-packages/autokey/gtkui/notifier.py", line 31, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```
```


### Anything else?

_No response_

**Comment by Elliria** [comment]
Would adding **gir1.2-ayatanaappindicator3-0.1** to the [apt-requirements.txt](https://github.com/autokey/autokey/blob/develop/apt-requirements.txt) file solve it?

**Comment by josephj11** [comment]
Is this exclusive to autokey-gtk or are similar changes needed to autokey-qt?

**Comment by ineuw** [comment]
I have a very similar issue with Kubuntu where both versions fail. Should I open a new ticket against advice? I have the error messages but it was after installation

**Comment by josephj11** [comment]
@ineuw  Post the error message here and we'll see if it fits here or needs a separate issue.

**Comment by ineuw** [comment]
I simply switched to the .deb files. But my error was not the GTK/Ayatana error.
 
Currently `gir1.2-ayatanaappindicator3-0.1 is already the newest version (0.5.90-7ubuntu2)` is my version in LMC 21.1. I am sure its the same version in Ku22.04

**Comment by Elliria** [comment]
The subject line for this issue mentions using `pip install .` as the command. If that's the case, it may be to blame. Have you tried the `pip3 install autokey` command from the [Installing](https://github.com/autokey/autokey/wiki/Installing) wiki page? And if so, does it give the same error?
