### ISSUE TITLE
Handle invalid regex for Trigger on (user input)

### ISSUE THREAD

**Issue by josephj11** [autokey/autokey#846]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Crash/Hang/Data loss

### Choose one or more terms that describe this issue:

- [X] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [X] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [X] user interface

### Which Linux distribution did you use?

N/A

### Which AutoKey GUI did you use?

None

### Which AutoKey version did you use?

Any

### How did you install AutoKey?

N/A

### Can you briefly describe the issue?

The Trigger on field in the GUI accepts arbitrary user input and compiles it as a regex, but does not appear to handle an exception for an invalid regex.

It should do something reasonable like display an error message pop-up and refuse to save the regex.

See:

https://github.com/autokey/autokey/blob/master/lib/autokey/model/abstract_abbreviation.py#L68

Also make sure that a n invalid regex manually added to a sidecar file will not crash AutoKey.

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

Type an invalid regex into the Trigger on field in the GUI or edit one into a sidecar file for an action.

The first one should cause a problem immediately. The second one will probably show up when the manually modified action is used. This case needs to be investigated.

### What should have happened?

An invalid regex exception should be handled and the regex shoud be refused (not saved) with an appropriate error pop-up, etc. if it was entered in the GUI.  

If the invalid regex was manually edited into a sidecar file, something similar should be done to insure that AutoKey detects the problem when it encounters it and does not crash.

### What actually happened?

Didn't try it.

### Anything else?

This needs to be implemented _before_ we advertize the existence of this arbitrary input field.

**Comment by Elliria** [comment]
> Type an invalid regex into the Trigger on field in the GUI or edit one into a sidecar file for an action.

Can you give examples of both of these for testing purposes?

Also, would the behavior I mentioned [here](https://github.com/autokey/autokey/issues/843#issuecomment-1520834884) fit in as part of this issue?

**Comment by josephj11** [comment]
A regex of '(12'  or '[12' ought to break things. You type it into the Trigger on field or edit it into a test action sidecar file and then restart Autokey and see what happens. It ought to run into it when parsing the sidecar file before you do anything.

The test you already ran makes it look like something else is going on. There's no way your regex - which appears valid to me, acted like "True" and let everything pass - should have done that.

I'm fair and BREs and EREs, but I'm not particularly familiar with the dialect that Python uses.

**Comment by Elliria** [comment]
Typing invalid regex into it doesn't cause AutoKey to display a notification. That actually makes sense, though, if the purpose of that box is for you to put one or more characters into it that you wish to use to cause the phrase or script to be triggered when its abbreviation has been used. So, for example, with **(12** as the trigger, your phrase or script will fire if the abbreviation is used and you type either an opening parenthesis or a one or a two. In all of my tests, AutoKey didn't attempt to look at what I typed into that box as a whole that it should consider as an entity of some sort, like a valid regex expression. It seemed to only care about the contents of the box as individual characters.

**Comment by josephj11** [comment]
I think I figured out what it's doing. It is a full regex, but the GUI wraps whatever you enter in `[^...]` so it becomes a character class of _not_ whatever you entered.

That defangs most simple regexes, but can be defeated by entering something like `something]fancy stuff[something` so the fancy stuff isn't in the character class. If anyone does that, then they know enough to fix it themselves.

If you manually enter something illegal into wordChars in the sidecar file, the whole action disappears from the folder menu in the left panel, so it looks like any serious errors  in the JSON file make the action be ignored by AutoKey. There probably should be an error message in the log when this happens. Found this, but apparently AutoKey keeps going anyway.

```
Error while loading json data for
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/model/phrase.py", line 105, in load_from_serialized
    data = json.load(json_file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 18 column 24 (char 407)
JSON data not loaded (or loaded incomplete)
```

**Comment by Elliria** [comment]
> I think I figured out what it's doing. It is a full regex, but the GUI wraps whatever you enter in `[^...]` so it becomes a character class of _not_ whatever you entered.

I don't think so, because in my case, AutoKey matches with wild abandon and includes more than what I put in as the trigger.
 
> If you manually enter something illegal into wordChars in the sidecar file, the whole action disappears from the folder menu in the left panel, so it looks like any serious errors in the JSON file make the action be ignored by AutoKey.

Yep. It's picky and cares very much if the JSON is written properly or not.

> There probably should be an error message in the log when this happens. Found this, but apparently AutoKey keeps going anyway.

*SNIP*

Interesting. A grep of the 0.96.0 source code for **Error while loading json data for** turns these up:
```bash
$ grep -ir "Error while loading json data" *
lib/autokey/model/folder.py:            logger.exception("Error while loading json data for " + self.title)
lib/autokey/model/phrase.py:            logger.exception("Error while loading json data for " + self.description)
lib/autokey/model/script.py:            logger.exception("Error while loading json data for " + self.description)
```
From that, it looks like phrases only throw predefined exceptions if their descriptions (the names of the phrases) are bad. I suppose we'd need to add a **wordChars** exception to catch bad regex, but a test would need to be written and I'm not sure how difficult that would be.

**Comment by josephj11** [comment]
It's probably easy. If the regex compiler throws an exception, the code could handle that and do something. If it came from the GUI, then a pop-up would be appropriate. 

You might have to add a "trial run" of the compiler in the GUI code because I believe it doesn't get called right away. It may wait until you try to Save your changes - when it may no longer have the desired context for a good error message, etc.

**Comment by Elliria** [comment]
My mistake. Those three locations are on the **master** branch.

In the **develop** branch:
* The [folder.py](https://github.com/autokey/autokey/blob/develop/lib/autokey/model/folder.py) file contains the **Error while loading json data for** message in the logger.
* There's no **Error while loading json data for** message in the logger in the [phrase.py](https://github.com/autokey/autokey/blob/develop/lib/autokey/model/phrase.py) file, although it does mention the logger. That file also makes no mention of errors, whatsoever.
* There's no **Error while loading json data for** message in the logger in the [script.py](https://github.com/autokey/autokey/blob/develop/lib/autokey/model/script.py) file, either. That file makes no mention of the logger, but uses the **ScriptErrorRecord** class, which may or may not handle exceptions.

All of that still needs to be investigated further to see why the changes were made and what it does and/or doesn't do.

With the logger messages, I think the goal is to write to the log rather than pop up a message to the user.

**Comment by josephj11** [comment]
Good research.

What I am trying to address is if the user types something "illegal" into the Trigger on field, they should get feedback then (not just in the log that they may not view/notice for quite some time). That would have to be a pop-up or some other GUI action that is immediately visible.

I'm not sure how things work, but if really bad input gets entered, the changes (possibly more than one modifed parameter) may not  get saved when AutoKey gets upset. If they are somehow saved, then that action may disappear from the folder panel next time AutoKey starts because AutoKey appears to ignore any actions that don't parse correctly (after complaining in the log where no one looks if they're not tracing something). I had to use a find command just to figure out where the log was because I almost never use it directly.

**Comment by Elliria** [comment]
I'm not sure that will be possible. As it stands, I'm convinced that AutoKey just accepts any one of the characters in the trigger box when you do a custom trigger and isn't reading it as though you intended it to be regex. The only technically-invalid characters would be duplicates, because they're not needed. Once a character is entered into the box, it's considered a trigger. Repeating it does nothing.

If the goal is to pop up some sort of message if a person enters valid regex that AutoKey won't interpret as such, I suppose the trigger could be parsed and compared against a list of possible regex combinations, but I'm not sure how big such a list would have to be or if one could even find one that would include every possible regex one could put into there. If it is possible, then AutoKey could pop up some sort of, "It looks like you're trying to use a regular expression..." statement somewhere in that part of the interface.

Also, although it's a big stretch, it's conceivable that a person completely unfamiliar with regex could coincidentally put valid regex into the trigger box in an effort to specify certain characters as triggers. In such a case, the person would want each of those characters to be considered a trigger for that phrase or script, so they should be allowed to use them.

It's also possible that a person familiar with regex could do such a thing, especially if they're only slightly familiar with regex. Those folks, too, might wish for each of those characters to be used as a trigger for that phrase or script and should be allowed to do so.

A notification or caution or warning would be appropriate and may convince the user to change or remove that trigger, but AutoKey should still allow the trigger to be used if that's what the user wants.

I don't think those phrases or scripts will disappear. At least, none of mine have with all the strange triggers I've been throwing into them. Disappearing phrases or scripts would be worthy of a bug report. I'm pretty sure you (or someone) filed a bug report on that, right? I'm assuming the goal should be for AutoKey to either log or warn the user, but shouldn't be getting rid of anything arbitrarily. If there's something you've created that it won't accept, it should definitely kick up a big fuss immediately so that you realize there's a problem and so that you don't lose any data.

**Comment by josephj11** [comment]
I manually messed up the value of wordChars in a JSON file and it made the action disappear from the left navigation panel the next time AutoKey was started. I haven't done that from tihe GUI yet, but since no validation checks are done on user input, it should be possible.

I'm going back to my earlier opinion that we should note that input to this field is possible and might be helpful in some edge cases, but that the user is on their own if they go down this particular rabbit hole.

Given how strange the behavior is, it might be best left as an undocumented feature - maybe with a few comments in the source code itself so if someone searches that deeply they can find it - presuming that if they're at that level, they can solve their own problems if they create them.

**Comment by Elliria** [comment]
I think it would be good to mention it since it's a feature that can be used. We should probably explain that one or more characters can be typed in and that any one of them will be accepted as the trigger character, but that there are some instances where certain character-combinations may cause AutoKey to accept or reject unexpected characters.

As part of that, we could put links to this issue and issue #843 so that users can find out more and/or contribute to either of the discussions in them.

**Comment by josephj11** [comment]
I'm fine with that as long as it comes with a caveat emptor. This is an advanced feature that should only be used if you know what you're doing. If you come up with good uses for it, please post them to our community.

**Comment by Elliria** [comment]
Okay. Thanks for the suggestion. I'm working on making sure that message is conveyed. The [Beginners Guide](https://github.com/autokey/autokey/wiki/Beginners-Guide) wiki page that I want to add it to needs to be reworked for this stuff to go into it smoothly, so I've currently got it partially rewritten on my desktop and have to put some more time into it before it's production-ready.
