### ISSUE TITLE
Can not connect to display

### ISSUE THREAD

**Issue by steelbrain** [autokey/autokey#9]
Here's the log. Note: I am not logged in as root.

```
2015-08-08 02:17:18,058 INFO - root - Initialising application
2015-08-08 02:17:18,065 INFO - root - Initialise global hotkeys
2015-08-08 02:17:18,065 INFO - config-manager - Loading config from existing file: /home/steel/.config/autokey/autokey.json
2015-08-08 02:17:18,066 DEBUG - config-manager - Loading folder at '/home/steel/.config/autokey/data/Sample Scripts'
2015-08-08 02:17:18,067 DEBUG - config-manager - Loading folder at '/home/steel/.config/autokey/data/My Phrases'
2015-08-08 02:17:18,068 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2015-08-08 02:17:18,068 DEBUG - inotify - Adding watch for /home/steel/.config/autokey/data/Sample Scripts
2015-08-08 02:17:18,069 DEBUG - inotify - Adding watch for /home/steel/.config/autokey/data/My Phrases
2015-08-08 02:17:18,069 DEBUG - inotify - Adding watch for /home/steel/.config/autokey/data/My Phrases/Addresses
2015-08-08 02:17:18,069 INFO - config-manager - Successfully loaded configuration
2015-08-08 02:17:18,069 DEBUG - inotify - Adding watch for /home/steel/.config/autokey/data
2015-08-08 02:17:18,069 DEBUG - inotify - Adding watch for /home/steel/.config/autokey
2015-08-08 02:17:18,069 DEBUG - config-manager - Global settings: {'sortByUsageCount': True, 'interfaceType': 'XRecord', 'showTrayIcon': True, 'showToolbar': True, 'notificationIcon': 'autokey-status', 'windowDefaultSize': [600, 400], 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'scriptGlobals': {}, 'serviceRunning': True, 'menuTakesFocus': False, 'columnWidths': [150, 50, 100], 'isFirstRun': True, 'promptToSave': False, 'undoUsingBackspace': True, 'enableQT4Workaround': False, 'hPanePosition': 150}
2015-08-08 02:17:18,070 INFO - service - Starting service
2015-08-08 02:17:18,080 ERROR - root - Error starting interface: Can't connect to display ":1": b'No protocol specified\n'
Traceback (most recent call last):
  File "/home/steel/.local/lib/python3.4/site-packages/autokey/gtkapp.py", line 129, in initialise
    self.service.start()
  File "/home/steel/.local/lib/python3.4/site-packages/autokey/service.py", line 80, in start
    self.mediator = IoMediator(self)
  File "/home/steel/.local/lib/python3.4/site-packages/autokey/iomediator00.py", line 45, in __init__
    self.interface = XRecordInterface(self, service.app)
  File "/home/steel/.local/lib/python3.4/site-packages/autokey/interface.py", line 88, in __init__
    self.__initMappings()
  File "/home/steel/.local/lib/python3.4/site-packages/autokey/interface.py", line 140, in __initMappings
    self.localDisplay = display.Display()
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":1": b'No protocol specified\n'
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by troxor** [comment]
what is the output of `pgrep -a X`?
