### ISSUE TITLE
Doesn't start on Fedora

### ISSUE THREAD

**Issue by mariusa** [autokey/autokey#91]
## Classification:

Bug

## Reproducibility:

```
pip3 install python-config
yum install dbus-devel dbus-glib-devel
pip3 install git+https://github.com/autokey-py3/autokey
```
then as user

```
$ autokey-gtk 
Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 11, in <module>
    load_entry_point('autokey==0.93.10', 'console_scripts', 'autokey-gtk')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3.6/site-packages/autokey/gtkapp.py", line 31, in <module>
    from autokey.gtkui.notifier import get_notifier
  File "/usr/lib/python3.6/site-packages/autokey/gtkui/notifier.py", line 22, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

$ rpm -q python3
python3-3.6.1-8.fc26.x86_64
```
Thanks

**Comment by xircon** [comment]
You need libappindicator-gtk3 - from my arch install:

pacman -Qi autokey-py3
Name            : autokey-py3
Version         : 0.93.10-3
Description     : Python 3 port of AutoKey, a desktop automation utility
for Linux and X11 with new
                  features.
Architecture    : any
URL             : https://github.com/guoci/autokey-py3
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : python  wmctrl  hicolor-icon-theme  python-dbus
python-pyinotify  zenity  xautomation
                  imagemagick  xorg-xwd  python-xlib  python-six
python-gobject  gtksourceview3  libnotify
                  libappindicator-gtk3  gtk-update-icon-cache
Optional Deps   : python-atspi
                  python-qscintilla: for QT GUI (deprecated) [installed]
                  kdebindings-python: for QT GUI (deprecated)
Required By     : None
Optional For    : None
Conflicts With  : autokey  autokey-gtk  autokey-data
Replaces        : None
Installed Size  : 1627.00 KiB
Packager        : Unknown Packager
Build Date      : Fri 10 Mar 2017 22:39:06 GMT
Install Date    : Fri 10 Mar 2017 22:39:08 GMT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

**Comment by troxor** [comment]
What he said :)
