### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ding3my** [autokey/autokey#93]
## Classification:

Crash/Hang/Data Loss
## Reproducibility:

Always
## Steps to Reproduce

`pip3 install  git+https://github.com/autokey-py3/autokey`
## Version

Distro:
4.5.5-300.fc24.x86_64

## Notes
```
Collecting git+https://github.com/autokey-py3/autokey
  Cloning https://github.com/autokey-py3/autokey to /tmp/pip-mge276v7-build
Collecting dbus-python (from autokey==0.93.10)
  Using cached dbus-python-1.2.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyinotify in /usr/lib/python3.5/site-packages (from autokey==0.93.10)
Collecting python3-xlib (from autokey==0.93.10)
  Using cached python3-xlib-0.15.tar.gz
Installing collected packages: dbus-python, python3-xlib, autokey
  Running setup.py install for dbus-python ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nw8imhb6/dbus-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rdrrz1lw-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    creating /tmp/pip-build-nw8imhb6/dbus-python/build
    creating /tmp/pip-build-nw8imhb6/dbus-python/build/temp.linux-x86_64-3.5
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether UID '1000' is supported by ustar format... yes
    checking whether GID '1000' is supported by ustar format... yes
    checking how to create a ustar tar archive... gnutar
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking for native Windows host... no
    checking how to print strings... printf
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /usr/bin/dd
    checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
    checking for mt... no
    checking if : is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... no
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for inline... inline
    checking whether /usr/bin/python3 version is >= 2.6... yes
    checking for /usr/bin/python3 version... 3.5
    checking for /usr/bin/python3 platform... linux
    checking for /usr/bin/python3 script directory... ${prefix}/lib/python3.5/site-packages
    checking for /usr/bin/python3 extension module directory... ${exec_prefix}/lib64/python3.5/site-packages
    checking for python3.5-config... no
    checking for python-config... /usr/bin/python-config
    checking for Python headers using /usr/bin/python-config --includes... -I/usr/include/python2.7 -I/usr/include/python2.7
    checking whether those headers are sufficient... yes
    checking for Python library linker flags using /usr/bin/python-config... -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
    checking for git... /usr/bin/git
    checking whether you want to build HTML docs... if possible
    checking whether you want to build API docs... if possible
    checking python3 module: docutils... no
    checking for dbus-run-session... /usr/bin/dbus-run-session
    checking whether  understands --generator... no
    checking whether  understands --date... no
    checking whether  understands --time... no
    checking whether  understands --exit-status=2... no
    checking whether  understands --no-raw... no
    checking whether  understands --no-file-insertion... no
    checking whether  understands --cloak-email-addresses... no
    checking whether  understands --input-encoding=UTF-8... no
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for DBUS... no
    configure: error: Package requirements (dbus-1 >= 1.6) were not met:
    
    No package 'dbus-1' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nw8imhb6/dbus-python/setup.py", line 106, in <module>
        'build_ext': BuildExt,
      File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/lib64/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-nw8imhb6/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib64/python3.5/subprocess.py", line 584, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-nw8imhb6/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-build-nw8imhb6/dbus-python/build/temp.linux-x86_64-3.5/prefix']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nw8imhb6/dbus-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rdrrz1lw-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-nw8imhb6/dbus-python
You are using pip version 8.0.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
rpm -qa | grep -i dbus-1
```
python3-dbus-1.2.4-1.fc24.x86_64
dbus-1.11.2-1.fc24.x86_64
```

**Comment by troxor** [comment]
You need to install the dbus headers package (which are usually named -dev or -devel), as the dbus-python module compiles against it.

**Comment by ding3my** [comment]
@troxor Thx for your help. After `sudo dnf install dbus-python-devel` and `sudo dnf install dbus-glib-devel`, I tried `pip3 install --user git+https://github.com/autokey-py3/autokey` again:
```
Collecting git+https://github.com/autokey-py3/autokey
  Cloning https://github.com/autokey-py3/autokey to /tmp/pip-uix1kxom-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-uix1kxom-build/setup.py", line 22, in <module>
        import autokey.common as R
      File "/tmp/pip-uix1kxom-build/lib/autokey/common.py", line 19, in <module>
        import os, dbus.service
      File "/usr/lib64/python3.5/site-packages/dbus/__init__.py", line 77, in <module>
        import dbus.types as types
      File "/usr/lib64/python3.5/site-packages/dbus/types.py", line 6, in <module>
        from _dbus_bindings import (
    ImportError: /usr/lib64/python3.5/site-packages/_dbus_bindings.so: undefined symbol: _Py_ZeroStruct
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-uix1kxom-build
You are using pip version 8.0.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by deepkolos** [comment]
it works~
