### ISSUE TITLE
autokey does not start anymore, needs update?

### ISSUE THREAD

**Issue by rayvermey** [autokey/autokey#939]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Crash/Hang/Data loss

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [X] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

arch linux latest test version

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

latest from git

### How did you install AutoKey?

yay autokey then choose autokey git

### Can you briefly describe the issue?

when i start autokey this happens since a few days so i guess there was an update that screwed autokey over:

 File "/usr/lib/python3.11/site-packages/gi/importer.py", line 139, in create_module
    introspection_module = get_introspection_module(namespace)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/module.py", line 267, in get_introspection_module
    module = IntrospectionModule(namespace, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/module.py", line 114, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'GObject', version '2.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 33, in <module>
    sys.exit(load_entry_point('autokey==0.96.0', 'console_scripts', 'autokey-gtk')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/autokey-gtk", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3.11/site-packages/autokey/gtkapp.py", line 34, in <module>
    from gi.repository import Gtk, Gdk, GObject, GLib
  File "/usr/lib/python3.11/site-packages/gi/importer.py", line 141, in create_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'GObject', version '2.0' not found

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. from cli type autokey-gtk

### What should have happened?

autokey should run normally

### What actually happened?

the error above showed up

### Can you provide the output of the AutoKey command?

```bash
File "/usr/lib/python3.11/site-packages/gi/importer.py", line 139, in create_module
    introspection_module = get_introspection_module(namespace)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/module.py", line 267, in get_introspection_module
    module = IntrospectionModule(namespace, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/module.py", line 114, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'GObject', version '2.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 33, in <module>
    sys.exit(load_entry_point('autokey==0.96.0', 'console_scripts', 'autokey-gtk')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/autokey-gtk", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3.11/site-packages/autokey/gtkapp.py", line 34, in <module>
    from gi.repository import Gtk, Gdk, GObject, GLib
  File "/usr/lib/python3.11/site-packages/gi/importer.py", line 141, in create_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'GObject', version '2.0' not found
```

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @rayvermey ! (not sure if I've seen you before or not)

This appears to be a dependency issue.

We do have some Arch and Manjaro users, so you should post about this on [Gitter](https://gitter.im/autokey/autokey) where one or more of them may see it.
You can link to this issue if you don't want to repost everything.

If there's somewhere appropriate in the Arch community, you may want to post there as well.

**Comment by rayvermey** [comment]
Hi

thanks for reaching out!
I reinstalled glib2 and now autokey is working again!

Cheers

Ray

Op za 30 mrt 2024 om 15:33 schreef Joe ***@***.***>:

**Comment by josephj11** [comment]
Great. Then you can close this issue.

**Comment by rayvermey** [comment]
Done!

**Comment by rayvermey** [comment]
Done!
