### ISSUE TITLE
Fedora 41 compatibility — imghdr removed with python 3.13.

### ISSUE THREAD

**Issue by markallasread** [autokey/autokey#961]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

None

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [X] autokey-gtk
- [X] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [X] enhancement
- [X] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [X] technical debt
- [ ] user interface

### Other terms that describe this issue if not provided above:

fedora python fc41 imghdr

### Which Linux distribution did you use?

Moving to fedora 41 introduced a fresh error for me: ModuleNotFoundError: No module named 'imghdr'

Python 3.13 no longer includes imghdr which at least in my context, prevented autokey-gtk / autokey-qt from starting. I suspect any autokey install on a distribution that's moving towards python 3.13 will want to implement this (with some research, there may be better ways. I'm a novice). 

For my own setup this worked:

I've swapped out the imghdr-reliant code for imagesize — specifically within: 
/usr/lib/python3.13/site-packages/autokey/scripting/highlevel.py:

Lines 66=>78:

I switched out:

```
def get_png_dim(filepath: str) -> int:
    """
    Usage: C{get_png_dim(filepath:str) -> (int)}

    Finds the dimension of a PNG.
    @param filepath: file path of the PNG.
    @returns: (width, height).
    @raise Exception: Raised if the file is not a png
    """
    if not imghdr.what(filepath) == 'png':
        raise Exception("not PNG")
    head = open(filepath, 'rb').read(24)
    return struct.unpack('!II', head[16:24])
```

to:
```
def get_png_dim(filepath: str) -> tuple[int, int]:
    """
    Usage: get_png_dim(filepath:str) -> (width: int, height: int)
    Finds the dimension of a PNG.
    @param filepath: file path of the PNG.
    @returns: tuple of (width, height).
    @raise Exception: Raised if the file is not a png
    """
    # Check if file exists
    if not os.path.isfile(filepath):
        raise Exception("File does not exist")
        
    # Check if file is PNG using python-magic
    file_type = magic.from_file(filepath, mime=True)
    if file_type != 'image/png':
        raise Exception("not PNG")
    
    # Get dimensions using imagesize
    try:
        width, height = imagesize.get(filepath)
        return width, height
    except:
        raise Exception("Could not determine PNG dimensions")
```
 At the top, replaced 'import imghdr' with 'import imagesize'
 & then 'pip install imagesize'.
 
 Afterwards, autokey should startup like normal.
 
 Including the original error just in case it helps folks find this:
 Traceback (most recent call last):
 ```
  File "/usr/bin/autokey-gtk", line 33, in <module>
    sys.exit(load_entry_point('autokey==0.96.0', 'console_scripts', 'autokey-gtk')())
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/autokey-gtk", line 25, in importlib_load_entry_point
    return next(matches).load()
           ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/importlib/metadata/__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.13/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3.13/site-packages/autokey/gtkapp.py", line 39, in <module>
    from autokey import service, monitor
  File "/usr/lib/python3.13/site-packages/autokey/service.py", line 36, in <module>
    import autokey.scripting
  File "/usr/lib/python3.13/site-packages/autokey/scripting/__init__.py", line 24, in <module>
    from . import highlevel
  File "/usr/lib/python3.13/site-packages/autokey/scripting/highlevel.py", line 9, in <module>
    import imghdr
ModuleNotFoundError: No module named 'imghdr'
```
 

### Which AutoKey GUI did you use?

Both

### Can you briefly describe the issue?

Autokey on fedora 41 won't start due to missing imghdr python module.

### Can the issue be reproduced?

Always

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #961</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @markallasread</code> (replace <code>20</code> with the amount, and <code>@markallasread</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @markallasread!

Thanks for finding _and_ fixing this! You can submit a PR for this (against the develop branch) if you want to.
I'm not an AutoKey developer, but unless there are some surprises here, it's pretty likely to be approved.

FYI: the develop branch is a bit messed up ATM because the developer set it up to test Wayland without also keeping X11 functionality enabled, so it may be a bit tricky to test your PR.

Also, our GitHub actions don't include tests with Python 3.12 or 3.13 yet.

We'd be happy to see other such contributions if you are so inclined. Feel free to join us over on [Gitter](https://gitter.im/autokey/autokey) if there's anything you'd like to discuss.

**Comment by Elliria** [comment]
My [Test AutoKey](https://gist.github.com/Elliria/d06633320cf23f2a093519b75f7295b7#test-autokey) Gist contains the steps for [testing AutoKey by cloning a branch and checking out a pull request](https://gist.github.com/Elliria/d06633320cf23f2a093519b75f7295b7#test-autokey-by-cloning-a-branch-and-checking-out-a-pull-request) and also the steps for [testing AutoKey by cloning a branch and checking out a tag (release)](https://gist.github.com/Elliria/d06633320cf23f2a093519b75f7295b7#test-autokey-by-cloning-a-branch-and-checking-out-a-tag-a-release). Either one would work to do tests prior to the current state of the code.

Also, I'll fix those tests, @josephj11, but the highest version of Python that GitHub currently supports is **3.12.7**, so that's what the AutoKey project will be supporting.

**Comment by markallasread** [comment]
Much appreciated re: feedback. I was wary of submitting a PR, as I didn't want to impact anyone else's installs — just leaving this here in case folks run into it. 

Fedora is clearly as faster moving target than most distros so it's probably a non-issue for most.

**Comment by josephj11** [comment]
@Elliria Great. 3.13 just came out, so it makes sense that it's not supported yet. Apparently, it's an annual thing with 3.14 scheduled for 10/25.

@markallasread There's really no development ATM. Sam may do some more on Wayland at some point and Elleria does occasional small maintenance fixes, but there are not likely to be conflicting changes to run into. In any case, PRs don't do anything until they are merged and that doesn't happen until they've been reviewed by at least one of us, so that's not a problem either.

**Comment by Elliria** [comment]
I haven't kept up with the news or status of Python, @josephj11. The way I do the AutoKey's Python versions is:
* Get the **lowest** supported version from [python.org's Status of Python versions page](https://devguide.python.org/versions/).
* Get the **highest** supported version from the most-recent **Ubuntu** release listed on [GitHub's runner-images page](https://github.com/actions/runner-images#available-images).

**Comment by Elliria** [comment]
While we're on the topic of the **lowest** and **highest** versions, if you got the notification for the failed #967 pull request, @josephj11, or if you've seen my comment on issue #964, then you already know that we've hit a bit of a wall on being able to support **Python 3.12**, so we're supporting **Python 3.11** for now and there's a **help wanted** label on the issue to try to get it sorted out.

**Comment by BlueDrink9** [comment]
Would be good to know how autokey was installed, which was left out of the issue form. If it was Pip, I think autokey shouldn't even try to support the latest python version immediately. Many projects break on new python versions, the usual suggestion is install an old version of python and use that,possibly in a virtual environment. Arch and Fedora run into this all the time, autokey can't afford to support the latest version like that.

At the most, I think Elliria is right about only supporting the latest version available via the ubuntu image

**Comment by kestral86** [comment]
Edit: Forgot to swap out 'import imghdr' with 'import imagesize'.  Works on both Xorg and Wayland.  Thanks so much!

**Comment by josephj11** [comment]
If this is all sorted as it appears to be, we need a PR to actually make the change.

Even though this addresses a problem with Python 3.13, I assume it will not break anything in 3.9 - 3.11. Just need to be sure in case it needs to be held and merged later.

**Comment by mistune** [comment]
To avoid modifying the installed autokey code, I just installed the missing dependency to get it to work on my Fedora 41 setup.

Install `python3-pip` in your system if you still do not have it installed (make sure you are not in a venv or a conda environment, in conda, just run `conda deactivate`)

`sudo dnf install python3-pip`

And install the missing dependency https://pypi.org/project/standard-imghdr/

`pip install standard-imghdr`

As mentioned in another issue, environments are the way to go to make autokey work across different configuration/s. I cannot do this in the coming weeks but hopefully someone already knowledgeable in packaging autokey using isolated environments can help.

**Comment by ericzolf** [comment]
I followed the path of the initial reporter and it worked. I reported the bug to Fedora at https://bugzilla.redhat.com/show_bug.cgi?id=2329600 (attaching the patch of @markallasread 
[autokey_highlevel.diff.txt](https://github.com/user-attachments/files/17964822/autokey_highlevel.diff.txt).

The thing is for me that imagesize is packaged in Fedora (as `python3-imagesize`) whereas `standard-imghdr` isn't, and mixing RPM and pip packages is calling for issues (but your mileage might vary). On the downside both libraries are dead but at least imagesize seems more broadly packaged (at least Fedora and Debian).

**Comment by ericzolf** [comment]
BTW https://peps.python.org/pep-0594/ which removes imghdr lists 3 alternatives: [filetype](https://pypi.org/project/filetype/), [puremagic](https://pypi.org/project/puremagic/), [python-magic](https://pypi.org/project/python-magic/) (without time yet to check those).

**Comment by Elliria** [comment]
I'd be happy to do @markallasread's fix above on the **develop** branch with a slight modification since the file on that branch uses colon-notation instead of @-notation for the parameters.

Now the question will be as to which is the better way to add the software as a dependency. It's [in the Ubuntu repositories](https://launchpad.net/ubuntu/+source/python-imagesize) and [on PyPi](https://pypi.org/project/imagesize/), so it could be installed with **apt** or **pip3**. I'm not sure which of the two is preferable when there's a choice:
* Add `imagesize` to the `pip-requirements.txt` file.
* Add `python3-imagesize` to the `apt-requirements.txt` file.

**Comment by josephj11** [comment]
@Elliria Great. IDK for sure. When available, I prefer apt so things show up in muon, etc. It just has tpbe done so it also works for non-Debian distros too that don't have apt.) IDK if we need to support things like pacman or dnf... I don't believe we've done that before.
Maybe using apt woud also satisfy a dependency for it in another unrelated package. IDK if pip woud do that.

**Comment by Elliria** [comment]
Yeah, no idea. I took a look at the [apt-requirements.txt](https://github.com/autokey/autokey/blob/master/apt-requirements.txt) file and the [pip-requirements.txt](https://github.com/autokey/autokey/blob/master/pip-requirements.txt) file and they both contain packages that could be gotten from apt, but the `pip-requirements.txt` file has at least one that's not available in apt.

**Comment by BlueDrink9** [comment]
Neither of the above, I'm pretty sure they are only used for CI (could be misremembering though, you could add to both to be safe). Iirc you should primarily add it to https://github.com/autokey/autokey/blob/125cc83f96f14c3cd0cb6b390fd7d7f4abd18540/setup.py#L181

The debian maintainer (if there was one) would be responsible for setting deb requirements from the pip files

**Comment by dlk3** [comment]
Just seeing this issue now.  My PR (#992) for the "develop" branch includes a fix for this issue as I need Python 3.13 compatibility to run AutoKey on Fedora 41.  I decided to use the [puremagic](https://pypi.org/project/puremagic/) module in place of imghdr as it is one of the options recommended [in the official Python documentation](https://docs.python.org/3/library/imghdr.html).  Any solution will do, in my opinion, I just wanted to call your attention to this so that you all can work out what approach it is you want to take, if you decide to pull in my PR.

**Comment by Elliria** [comment]
Thanks for jumping in here, @dlk3. Luckily, we hadn't implemented it yet since we hadn't heard anything further on it. Since GitHub recommends the [puremagic](https://pypi.org/project/puremagic/) solution you're using, we can abandon the `imagesize` solution without needing to undo anything and then use the puremagic instead.

**Comment by arscynic** [comment]
> https://github.com/autokey/autokey/issues/961#issuecomment-2489217891: To avoid modifying the installed autokey code, I just installed the missing dependency […]

For Arch Linux users:
```
pacman -S python-pip
pip install standard-imghdr --break-system-packages
```

<details><summary>Why --break-system-packages?</summary>
Otherwise I get the error below:

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
</details>

**Comment by ericzolf** [comment]
This is exactly how I would NOT do it, exactly because you might break your system mixing up DNF (APT, or whatever) and PIP installed python packages. 
I can't speak for autokey but https://github.com/rdiff-backup/rdiff-backup/blob/master/tools/create_venv.sh shows how to create a virtual env and use bindep to install non-python dependencies.

**Comment by arscynic** [comment]
> This is exactly how I would NOT do it, exactly because you might break your system mixing up DNF (APT, or whatever) and PIP installed python packages. I can't speak for autokey but https://github.com/rdiff-backup/rdiff-backup/blob/master/tools/create_venv.sh shows how to create a virtual env and use bindep to install non-python dependencies.

My "system" was broken anyway because of this update. Anyway, if I understand correctly then virtual environments are for compartmentalizing different projects that may need different version of the same libraries, or any such permutation which prevents one new/old library from breaking separate projects. However, in my case, it doesn't pertain a project, but two system-wide available pieces of software, AutoKey and Input Remapper. 
Also, the error instruction on how to use a virtual environment confuses me more than it elucidates: 
```
create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
```
Yes, I should learn how it works, but my priority now was to quickly get these two programs to work again.

**Comment by rayvermey** [comment]
> > [#961 (comment)](https://github.com/autokey/autokey/issues/961#issuecomment-2489217891): To avoid modifying the installed autokey code, I just installed the missing dependency […]
> 
> For Arch Linux users:
> 
> ```
> pacman -S python-pip
> pip install standard-imghdr --break-system-packages
> ```
> 
> Why --break-system-packages?

Thanks! This solved it for me!!!

**Comment by Elliria** [comment]
### Fixed
This was fixed in [pull request #1076](https://github.com/autokey/autokey/pull/1076) in the development code and will be in the next release.

@josephj11, should we close it since it's fixed or leave it open since the fix isn't in an official release yet?

**Comment by josephj11** [comment]
@Elliria Good question. I would guess that leaving it open is better because people don't usually search closed PRs and might file duplicate issues.

The problem is keeping track of all of these.

Maybe we could open a meta issue/PR that says it fixes all such pending issues and then merge it (or whatever will work) after 0.97.0 (or the same with a subsequent release) goes live.  To do that, it might require us to commit something with a PR so there's something to merge. Could even be a dummy file.

**Comment by Elliria** [comment]
Yeah, the problem with leaving it open is that it will seem as though a fix is still needed, which it isn't, resulting in more of the unnecessary pull requests that we've already been getting. Anyone who needs the fix for this issue can receive support from us in the form of a work-around recommendation to do [pull request #1076](https://github.com/autokey/autokey/pull/1076)'s edit to the `lib/autokey/scripting/highlevel.py` file in their own stable copy of **AutoKey** or... if they're feeling frisky... take their chances by running a clone of that PR or any PR that has come after it, although that latter part should come with a **huge** warning since the current code-base is still **very** unstable.

**Comment by Elliria** [comment]
We'd be better off closing this as fixed (in the **develop** branch) and pointing anyone who creates new, similar issues to this issue than we are in having to examine and handle the flurry of PRs that will likely not stop until we do.

**Comment by josephj11** [comment]
Already merged in #1076 for release in 0.97.0 and several alternative PRs under consideration.
