### ISSUE TITLE
Sporadic missing characters when using "keyboard" input method into Thunderbird or Firefox

### ISSUE THREAD

**Issue by sicherist** [autokey/autokey#984]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [X] autokey-qt
- [ ] beta
- [X] bug
- [X] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [X] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Kubuntu 24.04 LTS

### Which AutoKey GUI did you use?

Qt

### Which AutoKey version did you use?

0.96.0

### How did you install AutoKey?

From Github DEB Package.

### Can you briefly describe the issue?

When pasting a phrase using "keyboard" into thunderbird or firefox often characters are missing.

### Can the issue be reproduced?

Not on every try but often.

### What are the steps to reproduce the issue?

1. Create a phrase in Autokey-qt with input method "keyboard". For example "Sehr geehrte Damen und Herren,"
3. Compose a new email message in thunderbird
4. paste your phrase. It doesn't matter if by expanding an abbreviation or selecting the phrase from menu

### What should have happened?

"Sehr geehrte Damen und Herren," should be pasted

### What actually happened?

Sometimes it works, but often characters are missing. For example "Sehr geehrt Damen und Heren,"

### Can you provide the output of the AutoKey command?

```bash
/usr/bin/autokey-qt:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
2024-12-09 14:32:34,480 INFO - autokey.UI_common_functions - Commandline program "visgrep" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "visgrep" exists on your system and is in the $PATH seen by Autokey.
2024-12-09 14:32:34,480 INFO - autokey.UI_common_functions - Commandline program "png2pat" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "png2pat" exists on your system and is in the $PATH seen by Autokey.
2024-12-09 14:32:34,480 INFO - autokey.UI_common_functions - Commandline program "xte" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "xte" exists on your system and is in the $PATH seen by Autokey.
2024-12-09 14:32:34,480 INFO - autokey.UI_common_functions - Commandline program "xmousepos" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "xmousepos" exists on your system and is in the $PATH seen by Autokey.
2024-12-09 14:32:34,480 INFO - autokey.qtapp - Initialising application
2024-12-09 14:32:34,500 INFO - autokey.qtapp - Initialise global hotkeys
2024-12-09 14:32:34,500 INFO - autokey.configmanager.configmanager - Loading config from existing file: /home/roland/.config/autokey/autokey.json
2024-12-09 14:32:34,500 INFO - autokey.configmanager.version_upgrading - Checking if upgrade is needed from version 0.96.0
2024-12-09 14:32:34,503 DEBUG - autokey.configmanager.configmanager - Loading folder at '/home/roland/.config/autokey/data/My Phrases'
2024-12-09 14:32:34,503 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2024-12-09 14:32:34,503 DEBUG - autokey.monitor - Adding watch for /home/roland/.config/autokey/data/My Phrases
2024-12-09 14:32:34,503 DEBUG - autokey.monitor - Adding watch for /home/roland/.config/autokey/data/My Phrases/Ebay alt
2024-12-09 14:32:34,503 DEBUG - autokey.monitor - Adding watch for /home/roland/.config/autokey/data/My Phrases/Verjus
2024-12-09 14:32:34,503 INFO - autokey.configmanager.configmanager - Successfully loaded configuration
2024-12-09 14:32:34,503 DEBUG - autokey.monitor - Adding watch for /home/roland/.config/autokey/data
2024-12-09 14:32:34,503 DEBUG - autokey.monitor - Adding watch for /home/roland/.config/autokey
2024-12-09 14:32:34,503 DEBUG - autokey.configmanager.configmanager - Global settings: {'isFirstRun': False, 'serviceRunning': True, 'menuTakesFocus': False, 'showTrayIcon': True, 'sortByUsageCount': False, 'promptToSave': False, 'enableQT4Workaround': False, 'interfaceType': 'XRecord', 'undoUsingBackspace': True, 'windowDefaultSize': [922, 716], 'hPanePosition': 260, 'columnWidths': [316, 49, 114], 'showToolbar': True, 'notificationIcon': 'autokey-status', 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'triggerItemByInitial': False, 'disabledModifiers': [], 'scriptGlobals': {}, 'gtkTheme': 'classic', 'gtkExpandedRows': [], 'pathLastOpen': '0'}
2024-12-09 14:32:34,503 INFO - autokey.service - Starting service
2024-12-09 14:32:34,513 DEBUG - autokey.interface - Enabling sending using Alt-Grid
2024-12-09 14:32:34,513 DEBUG - autokey.interface - Modifier masks: {<Key.SHIFT: '<shift>'>: 1, <Key.CONTROL: '<ctrl>'>: 4, <Key.ALT: '<alt>'>: 8, <Key.ALT_GR: '<alt_gr>'>: 128, <Key.SUPER: '<super>'>: 64, <Key.HYPER: '<hyper>'>: 64, <Key.META: '<meta>'>: 8, <Key.NUMLOCK: '<numlock>'>: 16}
2024-12-09 14:32:34,548 DEBUG - autokey.iomediator.iomediator - Set modifier Key.CAPSLOCK to False
2024-12-09 14:32:34,548 DEBUG - autokey.iomediator.iomediator - Set modifier Key.NUMLOCK to True
2024-12-09 14:32:34,549 DEBUG - autokey.interface - Grabbing hotkey: ['<super>'] 'k'
2024-12-09 14:32:34,549 DEBUG - autokey.interface - Grabbing hotkey: ['<shift>', '<super>'] 'k'
2024-12-09 14:32:34,549 DEBUG - autokey.interface - Grabbing hotkey: ['<ctrl>', '<shift>', '<super>'] '<'
2024-12-09 14:32:34,549 DEBUG - autokey.interface - __flushEvents: Entering event loop.
2024-12-09 14:32:34,549 INFO - autokey.iomediator.iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2024-12-09 14:32:34,554 INFO - autokey.interface - XRecord interface thread starting
2024-12-09 14:32:34,555 INFO - autokey.service - Service now marked as running
2024-12-09 14:32:34,555 DEBUG - autokey.qtui.notifier - Creating system tray icon notifier.
2024-12-09 14:32:34,557 INFO - autokey.qtui.notifier - Creating static context menu actions.
2024-12-09 14:32:34,558 DEBUG - autokey.qtui.notifier - Show tray icon enabled in settings: True
2024-12-09 14:32:34,558 INFO - autokey.qtui.notifier - Rebuilding model item actions, adding all items marked for access through the tray icon.
2024-12-09 14:32:34,558 DEBUG - autokey.qtui.popupmenu - Sorting phrase menu by item name/title
2024-12-09 14:32:34,558 DEBUG - autokey.qtui.popupmenu - Sorting phrase menu by item name/title
2024-12-09 14:32:34,558 DEBUG - autokey.qtui.popupmenu - Sorting phrase menu by item name/title
2024-12-09 14:32:34,559 DEBUG - autokey.qtui.popupmenu - Sorting phrase menu by item name/title
2024-12-09 14:32:34,563 DEBUG - autokey.qtui.notifier - About to show the tray icon.
2024-12-09 14:32:34,567 INFO - autokey.qtui.notifier - System tray icon notifier created.
2024-12-09 14:32:34,567 DEBUG - autokey.qtui.centralwidget - CentralWidget instance created.
2024-12-09 14:32:34,617 DEBUG - autokey.qtui.dialogs.hotkeysettings - Loaded item folder 'My Phrases', key: <, modifiers: ['<ctrl>', '<shift>', '<super>']
2024-12-09 14:32:34,617 DEBUG - autokey.qtui.dialogs.hotkeysettings - Loaded item folder 'My Phrases', key: <, modifiers: ['<ctrl>', '<shift>', '<super>']
2024-12-09 14:32:34,618 DEBUG - autokey.qtapp - Creating DBus service
2024-12-09 14:32:34,618 DEBUG - autokey.qtapp - Service created
2024-12-09 14:32:40,593 DEBUG - autokey.iomediator.iomediator - Key.CONTROL pressed
2024-12-09 14:32:40,672 DEBUG - autokey.service - Raw key: 'a', modifiers: [<Key.CONTROL: '<ctrl>'>], Key: a
2024-12-09 14:32:40,672 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:32:41,134 DEBUG - autokey.service - Raw key: 'c', modifiers: [<Key.CONTROL: '<ctrl>'>], Key: c
2024-12-09 14:32:41,135 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:32:41,982 DEBUG - autokey.iomediator.iomediator - Key.CONTROL released
2024-12-09 14:32:42,387 DEBUG - autokey.service - Raw key: <Key.DELETE: '<delete>'>, modifiers: [], Key: Key.DELETE
2024-12-09 14:32:42,387 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:32:48,562 DEBUG - autokey.service - Raw key: 's', modifiers: [], Key: s
2024-12-09 14:32:48,562 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:32:48,563 DEBUG - autokey.service - Input queue at end of handle_keypress: deque(['s'], maxlen=150)
2024-12-09 14:32:48,790 DEBUG - autokey.service - Raw key: 'g', modifiers: [], Key: g
2024-12-09 14:32:48,790 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:32:48,790 DEBUG - autokey.service - Input queue at end of handle_keypress: deque(['s', 'g'], maxlen=150)
2024-12-09 14:32:49,063 DEBUG - autokey.service - Raw key: 'd', modifiers: [], Key: d
2024-12-09 14:32:49,064 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:32:49,066 DEBUG - autokey.service - Input queue at end of handle_keypress: deque(['s', 'g', 'd'], maxlen=150)
2024-12-09 14:32:49,257 DEBUG - autokey.service - Raw key: 'h', modifiers: [], Key: h
2024-12-09 14:32:49,258 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:32:49,258 INFO - autokey.service - Matched Phrase "Sehr geehrte Damen und Herren" having abbreviations "['sgdh']" against current input
2024-12-09 14:32:49,264 DEBUG - autokey.iomediator.iomediator - Send via event interface
2024-12-09 14:32:49,265 DEBUG - autokey.service - Input queue at end of handle_keypress: deque([], maxlen=150)
2024-12-09 14:32:49,273 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:32:49,276 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:32:49,279 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:32:49,282 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:32:49,284 DEBUG - autokey.interface - Sending string: 'Sehr geehrte Damen und Herren,'
2024-12-09 14:32:49,289 DEBUG - autokey.interface - Send special key: ['<enter>']
2024-12-09 14:32:49,291 DEBUG - autokey.interface - Send special key: ['<enter>']
2024-12-09 14:33:02,850 DEBUG - autokey.service - Raw key: 's', modifiers: [], Key: s
2024-12-09 14:33:02,850 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:33:02,850 DEBUG - autokey.service - Input queue at end of handle_keypress: deque(['s'], maxlen=150)
2024-12-09 14:33:03,057 DEBUG - autokey.service - Raw key: 'g', modifiers: [], Key: g
2024-12-09 14:33:03,057 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:33:03,057 DEBUG - autokey.service - Input queue at end of handle_keypress: deque(['s', 'g'], maxlen=150)
2024-12-09 14:33:03,891 DEBUG - autokey.service - Raw key: 'd', modifiers: [], Key: d
2024-12-09 14:33:03,892 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:33:03,892 DEBUG - autokey.service - Input queue at end of handle_keypress: deque(['s', 'g', 'd'], maxlen=150)
2024-12-09 14:33:03,935 DEBUG - autokey.service - Raw key: 'h', modifiers: [], Key: h
2024-12-09 14:33:03,935 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:33:03,935 INFO - autokey.service - Matched Phrase "Sehr geehrte Damen und Herren" having abbreviations "['sgdh']" against current input
2024-12-09 14:33:03,943 DEBUG - autokey.iomediator.iomediator - Send via event interface
2024-12-09 14:33:03,943 DEBUG - autokey.service - Input queue at end of handle_keypress: deque([], maxlen=150)
2024-12-09 14:33:03,953 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:33:03,956 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:33:03,958 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:33:03,960 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:33:03,962 DEBUG - autokey.interface - Sending string: 'Sehr geehrte Damen und Herren,'
2024-12-09 14:33:03,966 DEBUG - autokey.interface - Send special key: ['<enter>']
2024-12-09 14:33:03,968 DEBUG - autokey.interface - Send special key: ['<enter>']
2024-12-09 14:33:33,966 DEBUG - autokey.service - Raw key: 's', modifiers: [], Key: s
2024-12-09 14:33:33,967 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:33:33,967 DEBUG - autokey.service - Input queue at end of handle_keypress: deque(['s'], maxlen=150)
2024-12-09 14:33:34,220 DEBUG - autokey.service - Raw key: 'g', modifiers: [], Key: g
2024-12-09 14:33:34,220 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:33:34,220 DEBUG - autokey.service - Input queue at end of handle_keypress: deque(['s', 'g'], maxlen=150)
2024-12-09 14:33:34,452 DEBUG - autokey.service - Raw key: 'd', modifiers: [], Key: d
2024-12-09 14:33:34,452 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:33:34,456 DEBUG - autokey.service - Input queue at end of handle_keypress: deque(['s', 'g', 'd'], maxlen=150)
2024-12-09 14:33:34,550 DEBUG - autokey.service - Raw key: 'h', modifiers: [], Key: h
2024-12-09 14:33:34,550 DEBUG - autokey.service - Window visible title: 'Verfassen: (kein Betreff) - Thunderbird', Window class: 'Msgcompose.thunderbird-esr'
2024-12-09 14:33:34,550 INFO - autokey.service - Matched Phrase "Sehr geehrte Damen und Herren" having abbreviations "['sgdh']" against current input
2024-12-09 14:33:34,562 DEBUG - autokey.iomediator.iomediator - Send via event interface
2024-12-09 14:33:34,562 DEBUG - autokey.service - Input queue at end of handle_keypress: deque([], maxlen=150)
2024-12-09 14:33:34,570 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:33:34,572 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:33:34,574 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:33:34,577 DEBUG - autokey.interface - Send special key: [<Key.BACKSPACE: '<backspace>'>]
2024-12-09 14:33:34,579 DEBUG - autokey.interface - Sending string: 'Sehr geehrte Damen und Herren,'
2024-12-09 14:33:34,583 DEBUG - autokey.interface - Send special key: ['<enter>']
2024-12-09 14:33:34,584 DEBUG - autokey.interface - Send special key: ['<enter>']
2024-12-09 14:33:50,240 DEBUG - autokey.iomediator.iomediator - Key.CONTROL pressed
^X2024-12-09 14:33:52,053 DEBUG - autokey.service - Raw key: 'x', modifiers: [<Key.CONTROL: '<ctrl>'>], Key: x
2024-12-09 14:33:52,053 DEBUG - autokey.service - Window visible title: 'Downloads : autokey-qt — Konsole', Window class: 'konsole.konsole'
2024-12-09 14:33:52,622 DEBUG - autokey.service - Raw key: 'c', modifiers: [<Key.CONTROL: '<ctrl>'>], Key: c
2024-12-09 14:33:52,622 DEBUG - autokey.service - Window visible title: 'Downloads : autokey-qt — Konsole', Window class: 'konsole.konsole'
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 302, in customEvent
    callback(*args)
  File "/usr/lib/python3/dist-packages/autokey/qtui/centralwidget.py", line 625, in _add_item
    self.widget.scrollToBottom()
KeyboardInterrupt
2024-12-09 14:33:52,945 DEBUG - autokey.iomediator.iomediator - Key.CONTROL released
2024-12-09 14:33:56,222 DEBUG - autokey.iomediator.iomediator - Key.CONTROL pressed
2024-12-09 14:33:57,015 DEBUG - autokey.iomediator.iomediator - Key.CONTROL released
2024-12-09 14:33:58,981 DEBUG - autokey.iomediator.iomediator - Key.CONTROL pressed
^C2024-12-09 14:33:59,091 DEBUG - autokey.service - Raw key: 'c', modifiers: [<Key.CONTROL: '<ctrl>'>], Key: c
2024-12-09 14:33:59,091 DEBUG - autokey.service - Window visible title: 'Downloads : autokey-qt — Konsole', Window class: 'konsole.konsole'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 295, in customEvent
    def customEvent(self, event):

KeyboardInterrupt
2024-12-09 14:33:59,494 DEBUG - autokey.iomediator.iomediator - Key.CONTROL released
2024-12-09 14:34:02,255 DEBUG - autokey.iomediator.iomediator - Key.CONTROL pressed
^X2024-12-09 14:34:02,330 DEBUG - autokey.service - Raw key: 'x', modifiers: [<Key.CONTROL: '<ctrl>'>], Key: x
2024-12-09 14:34:02,330 DEBUG - autokey.service - Window visible title: 'Downloads : autokey-qt — Konsole', Window class: 'konsole.konsole'
^X2024-12-09 14:34:03,013 DEBUG - autokey.service - Raw key: 'x', modifiers: [<Key.CONTROL: '<ctrl>'>], Key: x
2024-12-09 14:34:03,013 DEBUG - autokey.service - Window visible title: 'Downloads : autokey-qt — Konsole', Window class: 'konsole.konsole'
2024-12-09 14:34:03,295 DEBUG - autokey.iomediator.iomediator - Key.CONTROL released
2024-12-09 14:34:37,413 DEBUG - autokey.qtui.notifier - Triggered system tray icon with reason: 3
2024-12-09 14:34:37,413 INFO - autokey.qtapp - Displaying configuration window
2024-12-09 14:34:40,946 INFO - autokey.qtapp - Shutting down
2024-12-09 14:34:40,948 INFO - autokey.service - Service shutting down
2024-12-09 14:34:40,949 DEBUG - autokey.iomediator.iomediator - IoMediator shutting down
2024-12-09 14:34:40,949 DEBUG - autokey.interface - XInterfaceBase: Try to exit event thread.
2024-12-09 14:34:40,949 DEBUG - autokey.interface - XInterfaceBase: Event thread exit marker enqueued.
2024-12-09 14:34:40,949 DEBUG - autokey.interface - XInterfaceBase: self.shutdown set to True. This should stop the listener thread.
2024-12-09 14:34:41,847 DEBUG - autokey.interface - __flushEvents: Left event loop.
2024-12-09 14:34:41,848 DEBUG - autokey.iomediator.iomediator - Waiting for IoMediator thread to end
2024-12-09 14:34:41,849 DEBUG - autokey.iomediator.iomediator - IoMediator shutdown completed
2024-12-09 14:34:41,849 INFO - autokey.configmanager.configmanager - Persisting configuration
2024-12-09 14:34:41,849 INFO - autokey.configmanager.configmanager - Backing up existing config file
2024-12-09 14:34:41,850 DEBUG - autokey.monitor - Reporting IN_MODIFY event at /home/roland/.config/autokey/autokey.json~
2024-12-09 14:34:41,851 INFO - autokey.configmanager.configmanager - Finished persisting configuration - no errors
2024-12-09 14:34:41,851 DEBUG - autokey.monitor - Reporting IN_MODIFY event at /home/roland/.config/autokey/autokey.json
2024-12-09 14:34:41,852 DEBUG - autokey.service - Service shutdown completed.
2024-12-09 14:34:42,853 INFO - autokey.monitor - Shutting down file monitor
2024-12-09 14:34:42,853 DEBUG - autokey.qtapp - All shutdown tasks complete... quitting
```

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #984</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @sicherist</code> (replace <code>20</code> with the amount, and <code>@sicherist</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by Elliria** [comment]
This is a known issue in some programs, like **Firefox** and **LibreOffice**. AutoKey sends characters faster than a human being would type them and some programs aren't set up to handle that. Someone recently had the issue in **Thunderbird** and there are [several suggestions in that issue that you can try](https://github.com/autokey/autokey/issues/872), with **Paste using clipboard (Ctrl+V)** being most likely to solve the issue.

You mentioned that this is a phrase. If you can't get the phrase to work with the above suggestions, you could try turning the phrase into a script instead and inserting `time.sleep(.1)` statements into it to cause a delay between each character, adjusting the interval to a different number than **.1** if that doesn't work. If you need help turning the phrase into a script, let us know and we'll be glad to help.

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @sicherist !

This is "just the way things are". The problem is in the receiving application windows, not in AutoKey.

You can learn more about dealing with it successfuly in our [wiki](https://github.com/autokey/autokey/wiki/Emitting-Keyboard-Events). For extreme situations, see [this](https://github.com/autokey/autokey/wiki/Advanced-Scripts#function-to-type-text-slowly).

For support and  to discuss anything AutoKey related, visit us on our [Google Group](https://github.com/autokey/autokey/wiki/Community) or Gitter.

This issue should be closed.

**Comment by sicherist** [comment]
Thank you! I preferred "keyboard" because it even works in the terminal and ctrl-v would "litter" my clipboard with phrases. But "shift+insert" seems to work just fine for me. However "keyboard" worked well until not long ago. Do you happen to know if this typing-speed-limitation in firefox or thunderbird is intentional or a  bug?

**Comment by josephj11** [comment]
Yepp. The Firefox address bar  has been that way forever and now it looks like Thunderbird (still loosely affiliated with Mozilla) has joined the party. 

It's not really a bug. How fast are normal users going to type in a location field (or in any application)? AutoKey types at machine speed.

Aside from using shit+insert, you can use a script instead of a  phrase for something that also needs to work in a terminal. Terminal users need to be able to type raw Ctrl+C  and Ctrl+V, so copy and paste are Ctrl+Shift+C and Ctrl+Shift+V. So your script has to retrieve the window class and decide which key sequence to emit. (This is tricky. If you need a negative window filter, e.g. anything _except_ a terminal, that's hard to do correctly in AutoKey.)

Another solution would be to have two identical phrases with the same trigger(s), but with different window filters so the right sequence is emitted.

**Comment by Elliria** [comment]
We had played around with regex a while back, @josephj11, and I think we found that if you use this regular expression as the **Window Filter**, you can, for example, exclude all Firefox windows:
```python
^((?![Ff]irefox).)*$
```
In this case, the `[Ff]irefox` part would be replaced with the name of the desired window.

I've also got some scripts that check the window class or the window title before deciding what to do. It seems those aren't in the wiki, so I'll add them.

The wiki doesn't seem to have any example scripts that check the window class or the window title before deciding what to do. I'll add some.

**Comment by Elliria** [comment]
* The [Filter window by class](https://github.com/autokey/autokey/wiki/Basic-Scripts#filter-window-by-class) example scripts have been added to the wiki.
* The [Filter window by title](https://github.com/autokey/autokey/wiki/Basic-Scripts#filter-window-by-title) example scripts have been added to the wiki.

**Comment by josephj11** [comment]
All AutoKey window filters are  Python regexes.

I'm not up on Python regexes, but that looks like it says "not Firefox". If that's the case, it won't work because the window title probably doesn't have "Firefox" in it and will satisfy the regex. There was a more convoluted way to get around that probem.

Long ago, someone wrote code to replace window filters with Python scripts that were much more  flexible, but the code got  lost. I don't think it ever made it into a PR.

**Comment by Elliria** [comment]
Yep. It was just an example. In this case, to exclude all Thunderbird windows, the **Window filter** for the phrase would be:
```python
^((?![Tt]hunderbird).)*$
```

And for the code to replace window filters with Python scripts as an alternative, look at the comment just above your comment. I added them to the wiki and provided the links up there yesterday.

**Comment by josephj11** [comment]
@Elliria Not quite what I was talking about. The code I'm referring to was going to be internal to AutoKey and be accessed from the GUI instead of or in addition to being able to specify a window filter the way it works now. The user would write a arbitray script returning true or false that would determine if the trigger would be honored. If not, then other actions with the same trigger would be abe to evaluate if they should be invoked or if the trigger should be unaffected by AutoKey.

I thought @xpusostomos  wrote the code, but was unable to find it when I looked for it.

As for the regex, I vaguely recall @BlueDrink9 discussing this quite a while ago. I believe he showed some regex magic that would get around the flaw in AutoKey design which compares the regex to the title and to the class and succeeds if either one matches. This doesn't usually cause problems with positive window filters, but it makes negative windoow filters rather challenging to get right.

**Comment by Elliria** [comment]
Ah, okay. I didn't realize we were talking about an AutoKey feature here. Is this what you were looking for? https://github.com/autokey/autokey/issues/161#issuecomment-683361293

**Comment by josephj11** [comment]
Wow! That's exactly it. Maybe someday, someone will ressurect this code. We'd have to add it to te UI as an option to preserve all the legacy scripts. I haven't thought about it a lot, but it seems lke it would open up all sorts of possibiities.

**Comment by Elliria** [comment]
The **help wanted** label you added to the issue might just do the trick to give it some fresh attention. I just changed the color of the **help-wanted** label from **#c2e0c6** to **#ff00ff** (hot pink) so it catches the eye more easily.
