### ISSUE TITLE
AttributeError Exception: 'ConfigManager' object has no attribute 'workAroundApps'

### ISSUE THREAD

**Issue by dlk3** [autokey/autokey#99]
## Classification:
Bug

## Reproducibility:
Always

## Summary
The Fedora 25 distribution packaged version of autokey has stopped working recently, after recent system updates.  This is true on both of the two Fedoa 25 / XFCE systems that I use, a desktop and a laptop.  I removed the distribution package from the laptop and installed autokey-py3 using pip.  When I try to use an define a phrase with an abbreviation trigger and try to use that abbreviation trigger in a browser field or in an edit session autokey throws an AttributeError exception.  Prior to installing I had deleted the ~/.config/autokey directory.

## Steps to Reproduce
- rm -fr ~/.config/autokey
- Define a phase with an abbreviation trigger
- Try to use that abbreviation in a browser form or editor application

## Expected Results
The phase should replace the abbreviation characters

## Actual Results
The abbreviation characters are removed but the phase is not written, autokey throws an exception.

## Version
AutoKey-Py3 version 0.90.4
Installed via: pip3.6
Distro:  Fedora 25, XFCE desktop

## Notes
 This is the relevant portion of autokey-gtk -l output:

2017-09-08 12:43:39,486 DEBUG - service - Received mouse click - resetting buffer
2017-09-08 12:43:42,021 DEBUG - service - Raw key: ';', modifiers: [], Key: ;
2017-09-08 12:43:42,021 DEBUG - service - Window visible title: 'Mail - Google Chrome', Window class: 'google-chrome.Google-chrome'
2017-09-08 12:43:42,022 DEBUG - service - No phrase/script matched hotkey
2017-09-08 12:43:42,022 DEBUG - service - Input stack at end of handle_keypress: deque([';'], maxlen=150)
2017-09-08 12:43:42,803 DEBUG - service - Raw key: 'w', modifiers: [], Key: w
2017-09-08 12:43:42,803 DEBUG - service - Window visible title: 'Mail - Google Chrome', Window class: 'google-chrome.Google-chrome'
2017-09-08 12:43:42,803 DEBUG - service - No phrase/script matched hotkey
2017-09-08 12:43:42,804 DEBUG - service - Input stack at end of handle_keypress: deque([';', 'w'], maxlen=150)
2017-09-08 12:43:43,069 DEBUG - service - Raw key: 'e', modifiers: [], Key: e
2017-09-08 12:43:43,069 DEBUG - service - Window visible title: 'Mail - Google Chrome', Window class: 'google-chrome.Google-chrome'
2017-09-08 12:43:43,069 DEBUG - service - No phrase/script matched hotkey
2017-09-08 12:43:43,070 DEBUG - service - Input stack at end of handle_keypress: deque([';', 'w', 'e'], maxlen=150)
2017-09-08 12:43:43,198 DEBUG - service - Raw key: 'b', modifiers: [], Key: b
2017-09-08 12:43:43,198 DEBUG - service - Window visible title: 'Mail - Google Chrome', Window class: 'google-chrome.Google-chrome'
2017-09-08 12:43:43,198 DEBUG - service - No phrase/script matched hotkey
2017-09-08 12:43:43,199 DEBUG - iomediator - Send via event interface
2017-09-08 12:43:43,199 DEBUG - service - Input stack at end of handle_keypress: deque([], maxlen=150)
2017-09-08 12:43:43,199 DEBUG - service - Ignored locking error in handle_keypress
2017-09-08 12:43:43,199 DEBUG - interface - Send special key: ['<backspace>']
2017-09-08 12:43:43,200 DEBUG - interface - Send special key: ['<backspace>']
2017-09-08 12:43:43,200 DEBUG - interface - Send special key: ['<backspace>']
2017-09-08 12:43:43,200 DEBUG - interface - Send special key: ['<backspace>']
2017-09-08 12:43:43,201 DEBUG - interface - Sending string: 'Web meeting: http://bit.ly/XXXXXXX  The meeting password is "XXXXXXX"'
2017-09-08 12:43:43,201 ERROR - interface - Error in X event loop thread
Traceback (most recent call last):
  File "/home/ibmadmin/.local/lib/python3.6/site-packages/autokey/interface.py", line 141, in __eventLoop
    method(*args)
  File "/home/ibmadmin/.local/lib/python3.6/site-packages/autokey/interface.py", line 610, in __sendString
    self.__checkWorkaroundNeeded()
  File "/home/ibmadmin/.local/lib/python3.6/site-packages/autokey/interface.py", line 895, in __checkWorkaroundNeeded
    w = self.app.configManager.workAroundApps
AttributeError: 'ConfigManager' object has no attribute 'workAroundApps'
2017-09-08 12:43:46,234 DEBUG - service - Received mouse click - resetting buffer

**Comment by dlk3** [comment]
I commented out lines 609 and 610 in interface.py to bypass this exception.  That allows autokey to attempt to output the phrase but it also results in a new exception message for each character as it tries to send it.  I have attached a complete debug log showing an entire session:
[autokey.log.zip](https://github.com/autokey-py3/autokey/files/1288726/autokey.log.zip)

**Comment by troxor** [comment]
Does this affect current `git HEAD` ?

**Comment by dlk3** [comment]
Right.  So that's what I tried first actually.  But when I install and then try to run the git version I get an immediate exception and it doesn't even start.  It looks like to me that there's a dependency on something called "AppIndicator3" and I don't have a Python 3 version of that on my system.  I don't see a Fedora 25 package for it (the Ptyhon 2 package is python-appindicator so I'd expect that the Python 3 version would be python3-appindicator but there's nothing like that.)  I've searched the distribution repo and pip for likely packages, done a Google search, and I can't find anything that looks like it would give me this AppIndicator3 thing.  If you guys have any suggestions ...

Here's the exception I'm getting when I try to start autokey-gtk:

Traceback (most recent call last):
  File "/home/ibmadmin/.local/bin/autokey-gtk", line 11, in <module>
    load_entry_point('autokey==0.93.10', 'console_scripts', 'autokey-gtk')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ibmadmin/.local/lib/python3.6/site-packages/autokey-0.93.10-py3.6.egg/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/ibmadmin/.local/lib/python3.6/site-packages/autokey-0.93.10-py3.6.egg/autokey/gtkapp.py", line 31, in <module>
    from autokey.gtkui.notifier import get_notifier
  File "/home/ibmadmin/.local/lib/python3.6/site-packages/autokey-0.93.10-py3.6.egg/autokey/gtkui/notifier.py", line 22, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

**Comment by xircon** [comment]
```
3 extra/sni-qt 0.2.6-4 [installed]
5 community/libappindicator-gtk2 12.10.0-12 [installed]
6 community/libappindicator-gtk3 12.10.0-12 [installed]
10 multilib/lib32-libappindicator-gtk3 12.10.0-9 [installed]
```
This is what I have installed on Manjaro, that references appindicator.  it appears not to be a python package...

**Comment by dlk3** [comment]
@xircon Thanks for the hint, that helped me get things working.
@troxor The git HEAD version does not have the problem that I originally reported.

Details:
After installing the Fedora 25 package called libappindicator-gtk3 the git version of autokey-py3 was able to run.  It works as well as the prior versions did.  (There are still some quirks but those existed previously and are not in scope for this bug report.)  The only issue with the git version is that the toolbar icon is no longer the familiar "A", it is what looks kind of like a terminal icon instead.  I'm gonna ignore that and consider this here report closed.
